### ISSUE TITLE
Yo! Who wants in on this?

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/TorZillaPrint#1]
@claustromaniac @earthlng @overdodactyl (Pat, I'll invite you as admin of this repo with write access if you would like). Pat: nicked your PBMode detection code and didn't attribute you (readme not done).

First thing I need help with is how to turn the html file into a live github.io page - like earthlng's one (see below)

Super early days, and sure, we could split the css and js into separate files. I haven't even written the readme, but the basic idea is that we can get all the information in one hit, in logical groups. Too often, I cannot get all the relevant information about a FP aspect in one place. A typical example would be screen information, and despite earthlng's efforts [here](https://earthlng.github.io/testpages/screen_information.html), which built on [this](http://browserspy.dk/screen.php) it's incomplete. I've already added some more screen and window objects. And there's more listed in comments in the html, such as DPI, brightness, etc and including reading every value from an iframe as well - but I would start topics for each section.

And just FF and TB specific (no need to cater for Chrome, IE, Edge etc shit). It doesn't have to be fast, it just has to get the job done (but anyone who wants to make it more elegant, and my code is ugly AF, go ahead)

I'm not a JS person at all - I can barely read it (but I do have decades of coding in other languages way way back, so I can kinda muddle my way thru with trial and error)! Anyway, I set up a groovy color pastel palette and style and it's just a case of starting to build it all in. With attributes of course, because there is a massive load of scripts out there we can re-purpose.

![torzilla](https://user-images.githubusercontent.com/16656956/50432631-1712c480-08cb-11e9-8165-d728ff152eac.png)

**Comment by claustromaniac** [comment]
Nice!

TBH I think both :earth_asia: and :bird: will be of more help than me with this project (if they decide to take part), but sure, count me in. I'm sure we can pull off something cool if we do this together.

**Comment by Thorin-Oakenpants** [comment]
I updated the pic in OP to give you an idea of what sections would be - the order can change. I'm building in all the math soon (which might be useless since we're only looking at FF code base, so TB and FF *should* never differ - but it's one of those things that need testing.

Hope we don't need more than 12 sections .. fuuuuuck, I forgot about . just kidding.

**Comment by claustromaniac** [comment]
https://ghacksuserjs.github.io/TorZillaPrint/TorZillaPrint.html

For future reference, it's from the [Settings](https://github.com/ghacksuserjs/TorZillaPrint/settings).

**Comment by overdodactyl** [comment]
Neat idea..definitely interested!!

Sorry I've been MIA - have been a bit busy lately

**Comment by Thorin-Oakenpants** [comment]
@overdodactyl no worries mate .. someone had to deliver all those presents

When you have a second, see around line 80+ I have three scripts which if you un-comment out the `console.log` lines, will output the info to console. But anything I do with them returns a type error `document.getElementById(...) is null`.

And in (around lines 180), I get `reference error` x `is not defined`. 
```
  //document.getElementById("bName").innerHTML = browser.name;
  //document.getElementById("bVersion").innerHTML = browser.name;
  //document.getElementById("lVersion").innerHTML = layout.version;
  //document.getElementById("lName").innerHTML = layout.name;
  //document.getElementById("osName").innerHTML = os.name;
```

I sound like a complete and utter noob and feel like an idiot. I think I understand what's going on in each case, but I can't seem to find examples that fix it (I'm learning with a bit of trial and error)

PS: I want this to be completely free of external libraries (if that's the right word), but if we do have to have them, then they need to be first party

No hurry: I need a break, and some food

**Comment by Thorin-Oakenpants** [comment]
@overdodactyl : https://github.com/ghacksuserjs/TorZillaPrint/invitations

**Comment by claustromaniac** [comment]
I propose that we move the CSS and JS out of the HTML. That way we can work in branches and avoid editing the same file at the same time. The end result is also easier to read (for me at least).

**Comment by overdodactyl** [comment]
Is this the info you want to present in ~180 pants?

https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_nav_all

You can see other options `navigator` provides by running 

```js
console.log(navigator)
```

in the console.

More info here:

https://www.w3schools.com/js/js_window_navigator.asp

**Comment by overdodactyl** [comment]
>`browser.name`

I'm not sure where this info should be coming from...were you looking at a function like this?

https://www.gregoryvarghese.com/how-to-get-browser-name-and-version-via-javascript/

**Comment by claustromaniac** [comment]
I have yet to touch even a single line of this because I've been pretty busy with other stuff, but I have another pretty important proposal to make in the meantime: the doc is currently indented with an irregular mix of tabs and spaces, all Picasso style (dat art :jeans:!). We should pick tabs or spaces and be consistent, otherwise people will hate us :question: I don't mind using spaces, but I prefer tabs. 

So... tabs :tada: or spaces :heart: ?

**Comment by overdodactyl** [comment]
I think right now I have me text editor set up so when I press tab it gives two spaces...but its easy to change, so I'm good with whatever :)

Checkout #4 when you guys get a chance...I tried to split up the files and tidy things up a bit.  Let me know if you like that direction or prefer the current route.

**Comment by Thorin-Oakenpants** [comment]
I'm PABLO!!  last week I was escobar (lots of drugs man!), this week I'm picasso. Don't knock the pablos man!

**Comment by Thorin-Oakenpants** [comment]
I'll close this, and start a clean topic for the screen info table

**Comment by Thorin-Oakenpants** [comment]
> I'm sure we can pull off something cool if we do this together.

So where is everyone? I wonder when @earthlng the JS wizard will return, or if he's even interested. I'll just keep chipping away at 5 miles per hour...

**Comment by overdodactyl** [comment]
>So where is everyone?

I'm in the middle of moving, so I haven't had much free time to help out

**Comment by Thorin-Oakenpants** [comment]
@KOLANICH .. don't star my little test repo, star this one instead

**Comment by Thorin-Oakenpants** [comment]
> I'm in the middle of moving

:snail: :)
