### ISSUE TITLE
Not ranting, but...

### ISSUE THREAD

**Issue by claustromaniac** [ghacksuserjs/TorZillaPrint#11]
I'm sorry I almost don't have time to contribute right now (it's that time of the year and all)... With that being said, can we please give the JS part a basic level of abstraction to make things easier to read and work on without disturbing each other's work, especially considering that there are like 5 people with admin rights ATM?

I would:
- separate the UI-related stuff from the logic using functions with significant names
- add a `misc.js` for common/reusable functions and general stuff (this is where most of the abstraction would come from... heck we can even split this one into multiple parts if we want)
- load *_only_* the UI-handling script from the HTML, and load all the other scripts from within *that* script using `import` statements

Not only it should make collaboration easier, the code will be shorter and the site will perform better, too... the *only* drawback I see is that it won't be compatible with old browsers, but it seems Pants doesn't care about browsers other than FF & Tor, so I don't care either.

I would love to do this myself but I can't until the dust settles a bit because it would be a major rework and I can't avoid conflicts if you keep making an average of 20+ direct comits to the master branch every day (the time window is too small).

Once that is done we can split duties more easily (fe I can take care of the abstraction, since it is what I'm decent at). I can make functions or other structures for you to use. This may sound needlessly complex but in reality it should make the overall work easier than what you're doing right now.

Alternatively, we could just make a few small-ish commits with those basic structural changes I outlined above (loading X files from Y) and we can separate duties from that point onward. The site won't build until we make all the necessary changes, but who cares? I sure don't.

I don't know, it's just how I do things. If you don't like the idea let me know and I'll surrender to your workflow (or however you wanna call it). I promise I'll try not to bitch about it. And sorry if this makes me sound touchy or something; I always work alone (1st time I'm part of a "team" TBH).

**Comment by claustromaniac** [comment]
Actually, there's shitty support for `import/export` statements (modules) and we don't need them, but we can still do a similar separation. [This](https://github.com/ghacksuserjs/TorZillaPrint/compare/basic-example) is a first super basic example that doesn't even provide any significant level of abstraction, but would already be a significant improvement IMO.

**Comment by overdodactyl** [comment]
I'm all for this idea 👍 

With so many collabs we may need to make better use of branches/PRs rather than direct commits if it gets to crazy

**Comment by claustromaniac** [comment]
Yeah, that would help too, and we could even start making use of the other GitHub features like assignments and such. I'm not saying each of us should take care of individual tasks on our own (we can still discuss everything), but it would help to know who's modifying which files at any given time.

**Comment by Thorin-Oakenpants** [comment]
Just go for it guys. I'm an old school [OO](https://en.wikipedia.org/wiki/Object-oriented_programming) girl myself (or as I like to call myself a Pretty Object Orientated Princess)

Just do it you two and then I can update my local files and keep hammering away

**Comment by kkapsner** [comment]
The acronym of "Pretty Object Orientated Princess" is not that nice... ;)

As for the canvas part I will make a branch where I work on it and then merge it to the master from time to time. As for the integration in the UI I will adjust whatever you decide to use.

**Comment by claustromaniac** [comment]
At least he didn't use that backronym to name an [*extension*](https://addons.mozilla.org/en-US/firefox/addon/privacy-oriented-origin-policy/)... You gotta admit it Pants, you like it. I know you like it!

**Comment by Thorin-Oakenpants** [comment]
not ranting but ... not addressed
- navigator.connection broke as mentioned elsewhere
- new: I added anchors for each table `tbl1` etc, and they work up to and including tbl5 and then
 - at tbl6 and on they all stop at the same point, one line above the start of table 6 = math
 - https://ghacksuserjs.github.io/TorZillaPrint/TorZillaPrint.html#tbl5 .. nice
 - https://ghacksuserjs.github.io/TorZillaPrint/TorZillaPrint.html#tbl6 (thru to 12) .. fucked

**Comment by Thorin-Oakenpants** [comment]
ps, we should probably use anchors that make sense e.g #math in case we move tables around

**Comment by claustromaniac** [comment]
Yea I hear that, and lately I've been hearing it coming out of my own mouth very often... it's strange, the better I get at doing stuff the worse I seem to feel about myself. 

Why do I bother? I should smoke weed and masturbate instead.

**Comment by Thorin-Oakenpants** [comment]
cats can masturbate? .. anyway, can we close this now

**Comment by claustromaniac** [comment]
![3jwacyt-1-768x576](https://user-images.githubusercontent.com/20734810/50551387-87c53280-0c77-11e9-83c7-306721be443f.jpg)

(you asked)

**Comment by Thorin-Oakenpants** [comment]
re-opened: this also broke my `chrome://` tor detection

**Comment by Thorin-Oakenpants** [comment]
all I think it needs is a timer/delay. When I first did
```
checkImage("about:logo", "Firefox");
checkImage("resource://normandy-content/about-studies/img/shield-logo.png", "Tor Browser");
```

Obviously testing in TB, it would assign "Firefox" from the first test, but only land "Tor Browser if there was a slight delay (in the js I put about:logo first and the resource TB test last). That seemed to do the trick.

Ideas?

**Comment by Thorin-Oakenpants** [comment]
well the last two went perfect .. it's a bit hit and miss. Wonder what happens if we push it out to 10 seconds or something

**Comment by claustromaniac** [comment]
> actually that's not it. I think canvas prompts and/or canvas code has changed how/when things run?

That shouldn't be the case because the `canvas.js` is the last script to run ATM.

**Comment by Thorin-Oakenpants** [comment]
what if useragent came after canvas in the scripts order bottom of html? I have no idea .. ok ... i see you mentioned that while I was typing .. this is a tad weird

**Comment by claustromaniac** [comment]
let me try something...

**Comment by Thorin-Oakenpants** [comment]
IDK .. the last 3 tor closes/starts .. and the last 6 new identities .. they all worked

**Comment by Thorin-Oakenpants** [comment]
and then one more try and it didn't .. good lord.

**Comment by Thorin-Oakenpants** [comment]
PS: you can't replicate it locally because RFP doesn't kick in with local shit

**Comment by claustromaniac** [comment]
https://claustromaniac.github.io/TorZillaPrint/TorZillaPrint.html

I rolled back all commits after 0e07900 in my fork just for testing. See if it works reliably there (if it doesn't the problem already existed).

**Comment by claustromaniac** [comment]
(be sure to clear the cache)

**Comment by Thorin-Oakenpants** [comment]
its working because there is no canvas loading - I added that after https://github.com/ghacksuserjs/TorZillaPrint/commit/0e079003ef223ab80abcf62cf333595f65ad327c

**Comment by claustromaniac** [comment]
ok let's try to narrow it down...

**Comment by Thorin-Oakenpants** [comment]
aww man ..

New TB opened, loaded claustro TZP - detected TB. did a refresh, detected FF, did a refresh got TB

It's not reliable regardless of canvas. We need to do it someway else

**Comment by Thorin-Oakenpants** [comment]
> 
> 
> ok let's try to narrow it down...

Yeah. Canvas is a red herring, but lets use your live version to fine tune it

**Comment by claustromaniac** [comment]
I dropped only the commits related to `canvas.js`. Try again.

**Comment by Thorin-Oakenpants** [comment]
I wonder if the exit node is caching anything? Its inconsistent - I just got Tor Browser for TZP on a new TB instance, first load.

claustro TZP seems to be working fine, as was everything before canvas. IDK man, I think I might start the beersies early (and take my pants off)

**Comment by Thorin-Oakenpants** [comment]
What if you stick canvas in yours, and add a button in the `[chrome://] browser` section which when clicked calls first firefox check, then Tor check

I think the solution is to roll the test into one: that is if about:config = true then test tor

**Comment by Thorin-Oakenpants** [comment]
bullshit pseudo code example
```js
function fucknows(){
 if checkImage("about:logo", "we don't need this parameter any more") === true { "it's a boy"
  then if checkImage ("resource://normandy-content/about-studies/img/shield-logo.png", "blah") === true {
   "it's a girl" }
 }
}

**Comment by claustromaniac** [comment]
Actually, I think it has to do with the onload event... I'll try to rewrite the function when I can, but I may have to do some unrelated stuff first (don't be surprised if I disappear several hours)

**Comment by Thorin-Oakenpants** [comment]
> don't be surprised if I disappear several hours

Dude... I'm naked and getting drunk ... see you in 24 hrs :)  unless you want me see me earlier, all naked and drunk?

**Comment by Thorin-Oakenpants** [comment]
^^ ps: it'll be interesting to see the css only version of this

**Comment by overdodactyl** [comment]
>I think it has to do with the onload event

Am I missing something here, I thought we removed the unload event?

The js is looking much better by the way :)

>it'll be interesting to see the css only version of this

I'll look at adding that!

**Comment by claustromaniac** [comment]
@Thorin-Oakenpants I updated the fork again, see if it works well now.

> The js is looking much better by the way :)

We can make it look even better :grinning:

**Comment by claustromaniac** [comment]
That 500ms-long delay shouldn't be necessary at all... I don't get it. We should probably look for a different way to do this. Will be great if :bird: can pull it off with CSS only.

**Comment by Thorin-Oakenpants** [comment]
I certainly do .. sucking down beers right now sans pants

**Comment by claustromaniac** [comment]
wait a sec... I think my neuron started working again for a while (kinda, I still need to sleep)... if you get `Firefox` on Tor it means Tor has the `about:logo`. Is that the whole point of the delay? It would make sense for the two images to take a different amount of time to load if they are different.. I think that's the reason this is unreliable. If that's the case I can fix it. BRB

**Comment by claustromaniac** [comment]
OK, I *did* rewrite the function now. See if it works.

**Comment by claustromaniac** [comment]
BTW we could put some placeholder text there, like "Loading..." while the page is still loading...

**Comment by Thorin-Oakenpants** [comment]
both TB and FF have the about:logo .. but only TB has the second one (resource://whatever) .. so the test is

if it has about:logo then it's FF, and then see if we can refine that by detecting TB .. which is what I said up [earlier](https://github.com/ghacksuserjs/TorZillaPrint/issues/11#issuecomment-450598927) for the test, to roll it into one function rather than calling it twice. The logic/order is correct

```
if about:logo = true
   var whatami = "FF";
   if resource:whatever = true
         var whatami = "TB"
   else
        do nothing
   end if
else
  do nothing
end if
``

**Comment by Thorin-Oakenpants** [comment]
OK, I tested three times, new TB instance, with a refresh each and it's all working spot on - so go ahead and commit that

**Comment by Thorin-Oakenpants** [comment]
> should we add the placeholder

nah .. I have yet to do the readme (but have adraft) and the TZP page will have a tiny blurb at the top - it's **only** designed for FF and TB .. so we should always return something (until both of them plug the resource chrome leaks). and also, I want all cells to be empty unless we had success reporting something.
