### ISSUE TITLE
need a function to de-stringify

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/TorZillaPrint#18]
I need a function that takes this:

[{"type":"weekday","value":"Tuesday"},{"type":"literal","value":", "},{"type":"month","value":"January"},{"type":"literal","value":" "},{"type":"day","value":"8"},{"type":"literal","value":", "},{"type":"year","value":"2019"},{"type":"literal","value":", "},{"type":"hour","value":"8"},{"type":"literal","value":":"},{"type":"minute","value":"21"},{"type":"literal","value":":"},{"type":"second","value":"38"},{"type":"literal","value":" "},{"type":"dayPeriod","value":"PM"},{"type":"literal","value":" "},{"type":"timeZoneName","value":"Coordinated Universal Time"}]

and returns pairs of values and literals as a string
- "Tuesday" + " " + "January" + " " + "8" + "," etc
- should give "Tuesday, January 8, 2019, 8:22:30 PM Coordinated Universal Time"

**Comment by kkapsner** [comment]
```
function deStringify(data){
    return data.map(function(entry){return entry.value;}).join("");
}
```
should do the job.

**Comment by Thorin-Oakenpants** [comment]
awesome .. on it now .. will bitch if it doesn't work :)

**Comment by Thorin-Oakenpants** [comment]
TypeError: data.map is not a function.

Here's the items I have (well I changed it to varMESSY for ya)
```js
var dateUsed = new Date();
var dateFormatted = new Intl.DateTimeFormat(undefined, { weekday: "long", month: "long", day: "numeric", year: "numeric", hour: "numeric", minute: "numeric", second: "numeric", hour12: true, timeZoneName: "long" });
varMESSY = JSON.stringify(dateFormatted.formatToParts(dateUsed));
```

this outputs something like (without the line breaks)
```
[
  {"type":"weekday","value":"Tuesday"},
  {"type":"literal","value":", "},
  {"type":"month","value":"January"},
  {"type":"literal","value":" "},
  {"type":"day","value":"8"},
  {"type":"literal","value":", "},
  {"type":"year","value":"2019"},
  {"type":"literal","value":", "},
  {"type":"hour","value":"11"},
  {"type":"literal","value":":"},
  {"type":"minute","value":"40"},
  {"type":"literal","value":":"},
  {"type":"second","value":"25"},
  {"type":"literal","value":" "},
  {"type":"dayPeriod","value":"PM"},
  {"type":"literal","value":" "},{"type":"timeZoneName","value":"GMT"}
]
```
The test is that formatToParts doesn't leak locale (or use the wrong date time), but it's ugly AF to read., so I want to output it back in a readable format. I don't know this stuff (sorry, I wasted my life on being in Info Systems and SQL), so I'm not sure how to fix it .. array? A bit lost. Any help when you have time would be cool - thanks

I did some searching .. I think this output is an array

**Comment by claustromaniac** [comment]
Interesting how the format differs from the format of...
```js
(new Date(Date.now())).toString()
```

**Comment by Thorin-Oakenpants** [comment]
at some stage, the tor guys and others will check the work

**Comment by Thorin-Oakenpants** [comment]
thanks :cat2:

**Comment by claustromaniac** [comment]
> I hope that doesn't compromise anything. 

If the leak is in [`Intl.DateTimeFormat.prototype.formatToParts()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat/formatToParts), I suppose it should be irrelevant how you parse the output to convert it into a string. I'm not sure if that is what is being tested, though (you tell me). I'm just using my awesome deduction skills.

BTW, I wouldn't call kkapsner's function `deStringify` because it doesn't actually parse a string. Technically, it converts an array of objects that contain `value` properties into a single string.

> Can you elaborate?

compare to the value of `NOTMESSY` above
```js
console.log((new Date()).toString());
```

**Comment by Thorin-Oakenpants** [comment]
OK i changed the function name.

```js
console.log(cleanify(dateFormatted.formatToParts(dateUsed)));
console.log((new Date()).toString());
```

```
Wednesday, January 9, 2019, 4:47:00 AM GMT  <-- cleanified
Wed Jan 09 2019 04:47:00 GMT+0000 (UTC)  <- toString
```

That's because dateFormatted is using options to force long names for days and months, and 12hr cycles etc. That's what most of the `[long]` ones are about. I mean look at `Intl.DateTimeFormat` = `1/9/2019`. that's fine, but it doesn't let us know if the locale is being leaked in it

in FF63+ there was a change to date time now being computed from ICU or something something. So the diff between GMT and UTC will drop .. they all become Coordinated Universal Time. That diff doesn't matter anyway
