### ISSUE TITLE
roadmap of functionality & features

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/TorZillaPrint#19]
snip

**Comment by Thorin-Oakenpants** [comment]
@tomrittervg https://github.com/ghacksuserjs/TorZillaPrint/invitations

**Comment by Thorin-Oakenpants** [comment]
just thinking about it as well, a separate page to load/paste blobs seems best, because 1) you'll need a wider page than eg TB's 1000px, and 2) the css real time measurements would change - although it's only two items (for now)

**Comment by Thorin-Oakenpants** [comment]
The date/time entries would always be different in comparisons. There are only two dates used:
`dateFormatted` (used in several places for Intl.DateTimeFormat) and a `dateUsed` (everywhere else). We could hard those to the same date/time - yes/no?

**Comment by KOLANICH** [comment]
Is it something similar to panopticlick and fingerprint2.js? If it is, why not to reuse their code?

**Comment by KOLANICH** [comment]
>and fp2js doesn't show detail

It hashes them, but in order to hash one needs to get the data.



>But I have a font test here that uses a fallback font and measures stuff to determine what was loaded, and defeats doc fonts=0. 

I have used GitHub search on the repo and have not found any uses of `measureText` and `getBoundingClientRect` API. H9w do you measure fonts? Also read https://github.com/KOLANICH/Article-2015-Dull-captaincy-or-the-way-Tor-Project-fights-browser-fingerprinting

**Comment by Thorin-Oakenpants** [comment]
FTFY
> But I have a font test **here** (***on my local pc***) that ...

I get an element's `offsetWidth` with the fallback font, then load each font and compare the new `offsetWidth` ... if it differs the font is present, if not, you don't have it (which *seems* to be what they are doing here: https://github.com/EFForg/panopticlick/blob/master/static/fp2.js - except it only ever reports 2 fonts for me, whereas mine returns 50+).

I'm not even sure I will use it, it takes about 1 to 2 secs to run thru 1000 fonts (in a unicode text file). I will drum up some other tests using different methods and see what is fastest and most elegant etc

> and https://github.com/EFForg/panopticlick/pulls/KOLANICH may be useful too.

nice. I am currently building the devices section, and some of these are on that list - SpeechSynthesis, web speech, etc ..

**Comment by KOLANICH** [comment]
>I get an element's offsetWidth with the fallback font, then load each font and compare the new offsetWidth ... 


Thank you, I have not known about this property.

It [may make sense to replace that to `getBoundingVlientRect`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/offsetWidth). 

Also take a look at https://bugzilla.mozilla.org/show_bug.cgi?id=1450564 .
