### ISSUE TITLE
Math: can people please post their results

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/TorZillaPrint#21]
OK, so there are at least two Math results that I'm fairly sure (especially when combined as a set) give-away that you are using Firefox.  What I do not have is any 32 or 64 Linux machines, or a Mac, or even Win10 and Edge - so I'm limited

Also: there may be variations in some of the Math results (within Firefox) that reveal OS - not convinced on that one though (I think this used to be the case). So please post the entire math section results

Here are the two values I am interested in for detecting FF (the image if from Opera)
![math](https://user-images.githubusercontent.com/16656956/50968020-c063d800-14d1-11e9-86c5-c1600fcceed8.png)

PS: I only have chrome portable, and they only come in 32bit. IE was tested when I remoted into a client's machine to do some work (can't run IE on my machine). I will remote in again and check IE 32 vs 64 bit to clarify.

Update: FF checked on Win7 & Android (me), Mac (overdodactyl), Linux (kkapsner )

### :large_blue_circle: exmpl(1) FF = 1.7182818284590455

:small_orange_diamond: 1.718281828459045
- `Win7 64bit`: Opera 57, Chrome 71 32bit, IE 11
- `Mac`: Safari

### :large_blue_diamond: sinh(1) FF = 1.1752011936438016

:small_orange_diamond: 1.1752011936438014
- `Win7 64bit`: Opera57, Chrome 71 32bit
- `Mac`: Safari

:small_orange_diamond: 1.1752011936438013
- `Win7 64bit`: IE11

### :large_blue_diamond: looking for...
- `Linux 32bit`: various
- `Linux 64bit`: various
- `Safari`: various
- `Win10`: various

----

So if anyone can test and post results for other Platform & Browser combos that would be good.

**Comment by kkapsner** [comment]
Firefox Linux 64 bit:

asinh(1) | 0.8813735870195429
acosh(1e300) | Infinity
atanh(0.5) | 0.5493061443340548
expm1(1) | 1.7182818284590455
cbrt(100) | 4.641588833612778
log1p(10) | 2.3978952727983707
sinh(1) | 1.1752011936438016
cosh(10) | 11013.232920103324
tanh(1) | 0.7615941559557649

**Comment by Thorin-Oakenpants** [comment]
what does `console.log(Math.tan(-1e300));` give?

**Comment by kkapsner** [comment]
-1.4214488238747245

**Comment by Thorin-Oakenpants** [comment]
nvm - i added a math browser test and even though I'm 99% sure that either would do, my logic is that **both** must return the unique values, and I'm happy that this 100% covers it.

As for some math functions in FF indicating the platform, I downloaded and read the entire internet (or close to it), and can conclude that it was possible, but is no longer.

So I'll close this
