### ISSUE TITLE
building: cookies & storage

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/TorZillaPrint#22]
ideas / todo
* [ ] persistent storage `supercookie` logic
   - try and read a particular storage name eg TPZ and return it's value - do this for **all** types possible.
   - If it was found, say so e.g.
      - `found existing value: abc`
   - if all were sanitized then say so and set all with a new random value e.g
      - `nothing found, setting new random value: def`
   - if at least one existing value was found, those that weren't, re-spawn it e.g.
      - `nothing found, resetting existing value: abc`

I like this idea to show what has persisted, e.g when users use an extension to clear cookies and localStorage, but leave orphaned data behind

---
original post

I'm not sure where I'm going with this, so any insight/feedback would be good. I know that these can be controlled on a site by site basis, and do not make for good fingerprint entries, but it's all good tests for persistent storage, and I'll probably expand it to include Files

[edit: removed the long ramble]

~~/soz for the long ramble~~

**Comment by gorhill** [comment]
> The cookie testing script

That code is executed client-side -- on your computer, hence the cookies are visible. uMatrix prevents the server from receiving the cookies through `Cookie` header.

**Comment by Thorin-Oakenpants** [comment]
^^ ahh .. OK .. that makes total sense :)

**Comment by Thorin-Oakenpants** [comment]
http://browserspy.dk/offline.php .. the local storage test script has errors, so that explains that difference
