### ISSUE TITLE
building: DOMRect

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/TorZillaPrint#24]
This is just to get the ball rolling:

1st question: is this what we should call it (as per pic below: `ClientRect`? or `DOMRect`? And of course the relevant js file would match. I'll defer to the experts.

Assuming @kkapsner is happy to share/help ... I don't mean to take anything away from CB's own tests linked in the extension toolbar icon menu - and that's also why I am listing the extension in the footer (users of the extension already have a test provided for them, and people who don't have the extension may find it from here)

I looked at the code, and I came up with this:
![clientrect](https://user-images.githubusercontent.com/16656956/51378138-7a77c700-1b04-11e9-850c-07090657ef08.png)

I haven't committed it (or indeed wasted time adding `ids`), and there is also one new css rule. The question is (and I am not an expert) is how do you fill these in. I see the canvas one just calls a function to fill in data at the end by finding `tbl8`

I'm not entirely sure, but I came up with this:
- there are 4 methods used (we can just change the sub-header names if I got them out of order)
- each method uses 3 tests
- each test gets 8 results

so I thought of counters and we use a prefix `cr` to make them unique: so when doing method 1, test 1, results 1 to 8 would be cr111 cr112 - cr118, second test would be cr121, cr122 etc, and the hash field could be called `cr` + method counter + `hash` (or whatever) eg `cr1hash`. Hope that makes sense

**Comment by Thorin-Oakenpants** [comment]
Thanks. DOMRect sound good to me for the title then. The four hashes show the *ClientRect* so that's enough to fix any confusion I think.

Now I just have to work out how to do it based on your code (you do realize I haven't touched JS for almost 20 years, right?). I'll get there... :snail:

**Comment by Thorin-Oakenpants** [comment]
@kkapsner : I hope I've done this right: as yu can see from the above commit, I added the same content as your iframe src, but as a div (the css properties are identical and in the index.css)

see current: https://github.com/ghacksuserjs/TorZillaPrint/blob/master/js/domrect.js

I've output the four hashes and am yet to work out how to apply the "table output" into the td ids. I'll get there :snail: **BUT**... the hashes in mine keep changing .. depending on where I have scrolled to and refresh etc

![divdomrect](https://user-images.githubusercontent.com/16656956/51466627-8a8ce200-1d62-11e9-9bce-38b332fc7940.png)

Does this mean I *have* to use an iframe so it can't move around in the parent doc?

**Comment by Thorin-Oakenpants** [comment]
All done. But (especially locally, this is with the TZP as is, not a single test file), I sometimes get zero results when I do a refresh. Having a hard time getting this to happen with the live version, but I wonder:

- is the position of the `<script>` in the right place. In other words should it be higher in order to capture the onload event of the iframe document?
- is onload the only way to go, or the best way in this giant test page?
- does it matter if css is listed before scripts? I would assume that the browser knows what its doing and gets what it needs first?

currently
```html
  <script src="js/main.js"></script>
  <script src="js/screen.js"></script>
  <script src="js/useragent.js"></script>
  <script src="js/language.js"></script>
  <script src="js/headers.js"></script>
  <script src="js/cookies.js"></script>
  <script src="js/devices.js"></script>
  <script src="js/math.js"></script>
  <script src="js/canvas.js"></script>
  <script src="js/domrect.js"></script>
  <script src="js/media.js"></script>
  <script src="js/misc.js"></script>
```

**Comment by Thorin-Oakenpants** [comment]
actually it's really hit or miss at times if the code executes - but I'll open a new issue

**Comment by kkapsner** [comment]
I'm actually surprised that this does not work reliably. I think the problem is that the iframe content load very fast and the onload fires before the domrect.js is loaded/compiled/evaluated.
One solution would be to actually set the src of the iframe element within the JS. This should then always work.

**Comment by Thorin-Oakenpants** [comment]
see #27 

I think I just found my problem with the empty values - just did a commit. I've been playing in my test repo but I the acid test is here. At the moment it seems to be working with `load` and I'm about to clear everything, restart various Firefoxes and Tor Browser and see if I can get the `timer` one to trigger as a fallback

But your solution actually sounds better - how do I do that?

**Comment by Thorin-Oakenpants** [comment]
> One solution would be to actually set the src of the iframe element within the JS

That does the trick. Have tried for a hundred times with refreshes, clearing everything, reloading, changing identities if in Tor Browser, shift-reloading, rapid reloading .. you name it I tried it, lots .. and I cannot get it to fail to load - before I could get it to  happen within a few goes .. so it's all looking good
