### ISSUE TITLE
js: concatenating two promises

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/TorZillaPrint#26]
```js
// storage manager properties
  if ("storage" in navigator) {
    try {
      navigator.storage.persist().then(function(persistent) {
        if (persistent) dom.storageMProp = "persistent";
        else dom.storageMProp = "not persistent"});
      // StorageManager.estimate(), StorageEstimate.quota;
      navigator.storage.estimate().then(estimate => {
        console.log(`${estimate.usage} of ${estimate.quota} bytes`);
      });
    }
    catch (err) {dom.storageMProp = "no: catch(err)"};
  }
  else {dom.storageMProp = "no"};
```

in the above, I want to get `persistent` or `not persistent` and then append (with a space) the usage out of quota

The above code is live. If you run it, you can see the storage manager properties field is filled in. And the console will output something like "0 of 2147483648 bytes"

But no matter what I do, I can't seem to combine those two values (persist & the usage/quota) e.g to variables and concatenate them. I tried turning each one into a separate function to return something. Nothing I do seems to work. Smashing my head on a brick wall here.

**Comment by Thorin-Oakenpants** [comment]
this page might be easier: https://thorin-oakenpants.github.io/testing/

![meh](https://user-images.githubusercontent.com/16656956/51436569-8dff6b00-1c87-11e9-81fe-b9d222494194.png)

**Comment by claustromaniac** [comment]
```js
// storage manager properties
  if ("storage" in navigator) {
    try {
      navigator.storage.persist().then(function(persistent) {
        if (!persistent) dom.storageMProp = "not ";
      // StorageManager.estimate(), StorageEstimate.quota;
        navigator.storage.estimate().then(estimate => {
          dom.storageMProp.textContent += `persistent ${estimate.usage} of ${estimate.quota} bytes`;
        });
      });
    }
    catch (err) {dom.storageMProp = "no: catch(err)"};
  }
  else {dom.storageMProp = "no"};
```

**Comment by Thorin-Oakenpants** [comment]
wait .. yu changed it

**Comment by Thorin-Oakenpants** [comment]
the first one worked though .. anyway, will update to the latest one, which also works

**Comment by Thorin-Oakenpants** [comment]
I don't know why you swapped the persistent vs not persistent results .. maybe you need a nap :)

**Comment by Thorin-Oakenpants** [comment]
I dunno man .. I reverted it all to the one before the last one, and now I don't know where we're at .. seems to work though
