### ISSUE TITLE
widgets

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/TorZillaPrint#33]
I know you guys are busy: release week and all, so just when and if you ever get the time...

I'm not entirely sure what I'm doing here: hence @tomrittervg and @acatarineu . I'm also Linux useless, so ignore my ignorance. You can apply a "desktop environment", and that provides a GTK, but users can customize it: so you could have "debian gnome"'s with different GTKs?

Bugzillas?: 
- [1411425](https://bugzilla.mozilla.org/show_bug.cgi?id=1411425)  Remove full-native theming for content
- [1397996](https://bugzilla.mozilla.org/show_bug.cgi?id=1397996) scrollbar width

So I added some "widget" stuff: I just added stuff I thought might provide more entropy, so some are not technically widgets, I guess. **hash** at the top of the pic, detailed data under `show details`

![widget1](https://user-images.githubusercontent.com/16656956/57415202-cf8e3480-71ea-11e9-93b5-2b226201f467.png)

Here's the iframe: https://ghacksuserjs.github.io/TorZillaPrint/iframes/widgets.html
![widget2](https://user-images.githubusercontent.com/16656956/57415294-298efa00-71eb-11e9-9e68-6fb67bdd8b71.png)

If you look at the iframe's source, I set some css to make everything normal and set a font and size.

Here are some results: (debn=debian, opnS=openSuse etc) All my VMs are default installs, FF's and TBs are vanilla profiles (sorry some of them are a tad old: been a couple of months since I fired them up)

### Values used

```
      wdItem.offsetWidth + " x " + wdItem.offsetHeight + ", " +
      wdItem.clientWidth + " x " + wdItem.clientHeight + ", " +
      wdItem.scrollWidth + " x " + wdItem.scrollHeight + ", " +
      getComputedStyle(wdItem).getPropertyValue("font-family") + ", " +
      getComputedStyle(wdItem).getPropertyValue("font-size");
```

### Firefox

```
win7 FF: 134f754a5274f29ed90b1cdcc5774554649db613 / 68/67/66/65: both win32+win64 OS
wn10 FF: b8b94ccca469ecd345ba511ce8b3782341f91c24 / 65
^^ text + datetime-local *widths differs (6 values)
 
mint FF: 4c93b9df05661d7e61b8598d434eb9921e6511a6 / 66 Mint64bit \ WTF?
mint FF: 39ab4281b86294d3d9b3608931bce05540e43c7e / 64 Mint32bit /
^^ didn't compare individual results (yet)

debn FF: e7059a42b8d986d0d904e8ec8bf1da7d528f4ddb / ESR
opnS FF: 0385a56d32ff5cf51185dd90a94146436dad1a3d / ESR
ubun FF: 370f4f64ab2493c0df08222a6634bdf5a89202b1 / 63
```

Seems like Win7 vs Win10 is detectable. Also Mint32bit vs Mint64bit is different (same release, same default setup: linuxmint-19.1-cinnamon-32bit, linuxmint-19.1-cinnamon-64bit). Win7 and Mint are the only 32 + 64 bits OSes I can compare by architecture, so I wonder if other Linux distros suffer the same fate?

### Tor Browser

```
win7 TB: 99c2da7da72a4938c6c6482348653f7e1c063844 / 8.0.8 +8.5a11
wn10 FF: 0830717e1aaa5a0e6e580486ce82d101149f93a7 / 8.0.6
^^ text + datetime-local *widths differs (6 values)

mint TB: db396c608bca2f2490005ec0d9721768daab20dd / 8.0.6 32+64bit
debn TB: c58b2be3f8ebb93926f61cd2a3a17df3b73ee1cf / 8.0.6
opnS TB: 635c3847c5ee0fed1dac785e8c84bdc80a4b0c58 / 8.0.6
ubun TB: 868d4d939ae4b549d0ef2d7c5f983f5cc7e814b3 / 8.0.6
```

Exact same issue with Win7 vs Win10.

### Notes

I assume these five items are not widgets?
- progress bar, iframe, image = Times New Roman as per css, so they're not using "widgets"
- datetime, text area = monospace

otherwise the font returned leaks entropy (same for TB + FF unless stated)
- win7: MS Shell Dlg \32
- wn10: MS Shell Dlg \32
- mint: Noto Sans
- debn: Cantarell
- opnS: Sans (TB) Noto Sans (FF)
- ubun: Ubuntu

I will have to recheck and catalog everything, to see exactly what changes. Because I'm sure that some of the non-widgets change values. I'll recheck. But the problem is zoom can screw things up.

If I just use the ones that use those unique'ish font names, and only return the font-name and ~~line-height~~ font-size, then zoom doesn't play a part. But then I lose the entropy in some of the width/height changes (e.g Win7 vs Win10). I guess I could split them into a widget hash and an element hash - I think that's what I'll do.

### Help

Am I doing this right, did I screw up the css to standardize the playing field? Any other widgets to add? Should I drop anything (e.g I think image is always 24px). Was this helpful?

**Comment by Thorin-Oakenpants** [comment]
NOTES to myself:

progress bar, iframe, image create extra noise and complexity
 - if the font changes (if not set or present)
 - progress bar even the w/h changes (but not iframe or image)
 - stick to actual widgets
 - note for later: progress + image are not affected by zoom, iframe is
 - follow up on elements in a different entropy test > i.e these elements are more about fonts than anything else

---

of the 9 widgets, zoom affects width/height for all of them, but in different combos

WINDOWS
 - offset: all affected except color
 - client+scroll: all affected except button
 - combobox offsetheight (+scrollheight) = not affected (the heights are the same, so we only need one)
 - text : clientheight (+scrollheight) = not affected (the heights are the same, so we only need one)

LINUX
 - see if the same cobmos happen on linux

---

remove duplicity?
 - text+datetime-local = same
 - checkbox+radio = same (move them next to each other
 - leave in for now

change order
 - widgets: order monospace vs the other font
 - porperties: put font-family, font-size first
 - depending on linux zoom tests, only output w/h that is not affected by zoom

Hopefully this will give us a zoom-resistant, style-resistant test to see how deep the GTK rabbit hole goes

**Comment by tomrittervg** [comment]
Had someone look at this, and they had the following to say:

1. "I assume these five items are not widgets? (progress bariframe, image, datetime and text area)" - actually only iframe and image are not technically widgets.
2. Without running a lot of tests himself, he couldn't say off-hand if the CSS is successfully leveling the playing field as asked in the "Help" section.
3. Regarding any other widgets to add: :shorlander put together a comprehensive page with our widgets. You may want to take a look at it: http://stephenhorlander.com/form-controls.html
4. We're working on removing native styling for our widgets and using our own, consistent styling. It would be very interesting to know whether "unstyled" widgets also suffer from fingerprinting issues. You can try this by setting the widgets to "-moz-appearance: none;", which is what :shorlander did on the left side of his page.

**Comment by Thorin-Oakenpants** [comment]
^^ Cool :+1: I'll check it out later, How TF did I forget about the slider widget? :) I noticed in my testing that the progress bar liked to change from green to blue sporadically on loads: weird, but I see where the colors come from.

I also did a lot of testing (in nilla profiles) on the old page with the styling and long story short, every measurement was affected by zoom (except button clientWidth and the redundant scrollWidth: but I found that one of my extensions, CSS Exfil, modified that!!).

I can't always get the correct zoom if retina/hdpi is on: zoom detection is unreliable. So I ditched the measurements. I can of course still record that and assume zoom is 100% (as per new tabs with RFP) and in reality regardless of zoom/hdpi, that's the fingerprint. And just output the entire lot rather than what I did below (see next post). And I will test `-moz-*` and add in the items from stephen (nice work: I might just grab that entire page). And I still want to do an "element" entropy test (e.g iframe shows entropy across platforms).

FYI: zoom tests re: widths/heights
```
order: offset, client, scroll

LINUX: Mint Cinnamon
checkbox, radio:
   30: 53 x 53, 53 x 53, 53 x 53
  100: 16 x 16, 16 x 16, 16 x 16
button:
   30: 103 x 60, 16 x 20, 16 x 20
  100:  42 x 29, 16 x 17, 16 x 17
  300:  25 x 21, 16 x 17, 16 x 17
color:
   30: 103 x 40, 16 x  0, 16 x  7
  100:  64 x 23, 38 x 11, 38 x 11
  300:  64 x 23, 55 x 19, 55 x 19
combobox:
   30: 160 x 62, 50 x 22, 50 x 22
  100:  48 x 31, 15 x 19, 15 x 19
  300:  22 x 23, 11 x 19, 11 x 19
text, datetime-local:
   30: 218 x 55, 164 x 22, 164 x 22
  100: 188 x 29, 172 x 19, 172 x 19
  300: 177 x 22, 172 x 19, 172 x 19
datetime:
   30: 156 x 55, 103 x 22, 103 x 22
  100: 122 x 29, 106 x 19, 106 x 19
  300: 115 x 22, 109 x 19, 109 x 19
textarea:
   30: 182 x 80, 175 x 73, 175 x 73
  100: 156 x 44, 154 x 42, 154 x 42
  300: 153 x 33, 153 x 33, 153 x 33

so far only button clientwidth (+scrollwidth=redundant) = stable

WINDOWS7:
checkbox, radio:
  100: 13 x 13, 13 x 13, 13 x 13
  300:  9 x  9,  9 x  9,  9 x  9
button:
   30: 36 x 37, 16 x 17, 16 x 17
  100: 22 x 22, 16 x 16, 16 x 16
  300: 18 x 18, 16 x 16, 16 x 16
color:
   30: 64 x 23, 44 x  3, 44 x  7
  100: 64 x 23, 58 x 17, 58 x 17
  300: 64 x 23, 62 x 21, 62 x 21
combobox:
  100: 31 x 20, 31 x 20, 31 x 20
  300: 19 x 19, 19 x 19, 19 x 19
text, datetime-local:
  100: 143 x 22, 141 x 20, 141 x 20
  300: 138 x 18, 137 x 17, 137 x 17
datetime:
  100: 120 x 22, 118 x 20, 118 x 20
  300: 116 x 18, 115 x 17, 115 x 17
textarea:
  100: 183 x 53, 181 x 51, 181 x 51
  300: 164 x 37, 163 x 36, 163 x 36

regardless of these tests, we only want to look at 
button clientwidth (+scrollwidth=redundant) which seems stable

WINDOWS7 (my main FF)
button:
  100: 22 x 22, 18 x 18, 18 x 18
  300: 18 x 18, 14 x 14, 14 x 14
what causes this:
- css exfil extension
```

**Comment by Thorin-Oakenpants** [comment]
Currently: when the items are the same, the first 7 items are combined. Note the os output at the top of the pic
![2](https://user-images.githubusercontent.com/16656956/57558517-7a2e6080-736d-11e9-80d2-4a63d34db202.png)

and if I code one as a different result..
![3](https://user-images.githubusercontent.com/16656956/57558667-1b1d1b80-736e-11e9-884a-ce16dbf45ca4.png)

which isn't perfect, because in this example, the font didn't change, only the size, but I still changed the os guess in the top line. I'll fix that BUT .. it might be entirely pointless

## QUESTIONs
- are all widgets always tied to the same font i.e the ones that use "Roboto" or "MS Shell Dlg\32"
- can widget fonts be changed within a Firefox session (e.g a gtk pref or a theme)

If the answer to those are yes and no respectively, then that makes things simpler

**Comment by Thorin-Oakenpants** [comment]
FYI: some output results
```js
      if (wdFFN.slice(0,12) == "MS Shell Dlg") {wdOS = "Windows"}
      else if (wdFFN == "Roboto") {wdOS="Android"}
      else if (wdFFN == "-apple-system") {wdOS="Mac"}
      else {
        // refine Linux to spook the F out of people
        if (wdFFN == "Ubuntu") {wdOS="Linux [Ubuntu?]"}
        else if (wdFFN == "Cantarell") {wdOS="Linux [Debian?]"}
        else if (wdFFN == "Noto Sans") {wdOS="Linux [Mint? openSUSE?]"}
        else if (wdFFN == "Sans") {wdOS="Linux [openSUSE? + Tor Browser?]"}
        else if (wdFFN == "DejaVu Sans") {wdOS="Linux [Xfce?]"}
        else {wdOS="Linux [font: " + wdFFN + "]"};
```

**Comment by Thorin-Oakenpants** [comment]
I know what I'll do. I will use stephen's list of 23 items, instead of my 9 items. I will group them by font (like I did above). I'll output a hash for font-family+font-size, and a hash for measurements. Then I'll loop three more times for each of the four columns. Depending on the results, we should be able to normalize the playing field (and ignore zoom) to produce an entropy test for later.

I think I've misunderstood the test here.

**Comment by Thorin-Oakenpants** [comment]
FYI: My original test on the main page
- now detects changes to font and font-size individually
- if font or font-size differ, then the detail output becomes multi-line, otherwise it is combined (cosmetics! I know!)
- simplifies the OS output to OS + [font], where OS = android, mac, linux, or windows. If the font is not consistent it outputs `unknown [font: mixed values]`
- this test is style-resistant and zoom-resistant :)

The [extra's page](https://ghacksuserjs.github.io/TorZillaPrint/extra.html) (linked at the top of the main test)
- the `chrome://` test no longer runs on load
- have started to build a `widgets / form controls` test
- this test will encompass everything as per last post
- gimme a few days (or a week)

**Comment by Thorin-Oakenpants** [comment]
> * gimme a few days (or a week)

or a couple of months

**Comment by Thorin-Oakenpants** [comment]
> or a couple of months

or half a year 😀  .. been working on this (and another one for elements which is huge)

**Comment by Thorin-Oakenpants** [comment]
no need to keep this open, it's tracked in my todo list issue
