### ISSUE TITLE
DOMRect help required

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/TorZillaPrint#35]
@kkapsner 

Since this has your name attached to it, I want to make sure it's right. While I don't care about chromium, I also don't want it to give incorrect results, which is what I'm getting. I'm sure it's something simple, but it's beyond me

Here's the issue

Both FF `file:///` and `http*` tests return the correct results :heavy_check_mark: 
![dr-ff](https://user-images.githubusercontent.com/16656956/57975486-7c21a080-79b9-11e9-9257-36bdf63b1151.png)

Chrome (and Opera) `http*` tests do not :x:
![dr-chromium](https://user-images.githubusercontent.com/16656956/57975509-b8ed9780-79b9-11e9-9992-31eb38391d39.png)

Chrome (and Opera) `file:///` tests return an error
![dr-error](https://user-images.githubusercontent.com/16656956/57975524-3b765700-79ba-11e9-85da-c170687cedcc.png)

```
   return Array.from(docDR.querySelectorAll("*[id^=rect]"));  //line 13
   //return Array.from(docDR.querySelectorAll(".testRect"));  // your test page code
```

The iframe html is the same as yours, all six elements have a class `testRect` but the id's are different. So if I replace my line with yours, then the **local file** works (i.e no errors, not sure about the actual value being correct), but then the firefox **local file** now returns the wrong value. I did not upload the change and test it over http, because clearly there is something else going on here

TIA

**Comment by kkapsner** [comment]
The error in file:/// could be a protection thing.

I see two differences between my and you iframe html:
# rect2 does not have the testRect class and that's why FF changed the line
# you have a different docType which might result in different rendering of the white spaces. HTML 5 and XHTML have some differences in their specs. Exchange the docType and then check what you get.

**Comment by Thorin-Oakenpants** [comment]
- fixed missing class on one of the rects: that'll make the results correct when I use your line
- made doc type match yours - this fixed FF using your line on file:///
- switched to your line

It still fails file on chromium, and I suspect that's a security issue. I'll upload the changes and see what happens

**Comment by Thorin-Oakenpants** [comment]
**FF**
- yours, TZP http, file:/// = all the same result, no errors

Chromium
- yours, TZP http = the same, no errors
- file:/// = security error: so yup, it's a chromium thing

Thanks for your help. I think I'll append a red `[file:///]` - it's really only for myself, as I can can caught out with checking hashes for entropy (did it once with canvas), so if FF ever decide to add the same security as chromium, then I'm covered

**Comment by kkapsner** [comment]
You're welcome. Glad you sorted this out.

**Comment by Thorin-Oakenpants** [comment]
^^ Thanks :beers: 

BTW - there's some interesting webGL shit going on at Tor Browser
- https://trac.torproject.org/projects/tor/ticket/30531
- https://trac.torproject.org/projects/tor/ticket/30537
- https://trac.torproject.org/projects/tor/ticket/30541

**Comment by kkapsner** [comment]
WebGL was always not well treated in the fingerprinting protection. But that's in the nature of WebGL as it's so close to the GPU. Also the protection that CB offers is not as good as for the normal canvas.
