### ISSUE TITLE
make sure webgl2 is correctly reported

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/TorZillaPrint#37]
https://trac.torproject.org/projects/tor/ticket/30541#comment:6

> TB: Also your test shows ...  webgl2: supported ... but webgl2 shouldn't be allowed

I'm not sure if this is TB's issue, or the code

@kkapsner just @'ing you, but let me do some tests when I get time. There are a bunch of webgl prefs I can flip in Firefox, which I will test first, in a vanilla profile - including a webgl2 pref.

TB testing is trickier. It's alpha and there are more parameters (eg slider, click to play).

**Comment by Thorin-Oakenpants** [comment]
gk [said](https://trac.torproject.org/projects/tor/ticket/30541#comment:8)
> We explicitly set `webgl.enable-webgl2` to false to make sure no WebGL2 APIs are accessible.

Right .. which is one of the prefs I was going to test, see OP. @kkapsner FYI

**Comment by Thorin-Oakenpants** [comment]
FF69 tests: working as advertised
prefs:
- `webgl.disabled` (false = enabled, true=disabled)
- `webgl.enable-webgl2`(^^ the reverse)

vanilla FF69

- both enabled: both = supported
- both disabled:  both = not supported
- `webgl` disabled, `webgl2` enabled: both = not supported
- `webgl` enabled, `webgl2` disabled: webgl: supported, webgl2: not supported

**Comment by kkapsner** [comment]
So nothing to do?

**Comment by Thorin-Oakenpants** [comment]
Nope: I just tested TB8.5 and TB9.0a1 and cannot replicate the poster's issue. AFAIC the check is solid AF :+1:

**Comment by Thorin-Oakenpants** [comment]
OK .. cypherpunks [said](https://trac.torproject.org/projects/tor/ticket/30541#comment:13) try a VM .. now this makes more sense. I just tested Firefox at this stage, and while I couldn't replicate his/her result yet when webgl=allowed but webgl2=not-allowed (I need to test Tor Browser), it does show webgl2 as not supported, when both prefs are enabled, and do still get a readPixels value.

I think we should detect this "error" and output a different value for webgl2 when this happens to increase entropy (could it be used to detect VMs? IDK). i.e detect FEATURE_FAILURE on SetDimensions

In my Windows 10 VM with FF
- :x: both enabled: `webgl` supported `webgl2` not supported
   * ^^ see pic: get getContext and <SetDimensions> errors
- :heavy_check_mark: both disabled: both = not supported
- :heavy_check_mark: `webgl` disabled, `webgl2` enabled: both = not supported (webgl = master switch)
- :heavy_check_mark: `webgl` enabled, `webgl2` disabled: webgl: supported, webgl2: not supported 
   * ^^ only get the getContext errors

big ass screenshot

![VM](https://user-images.githubusercontent.com/16656956/58601295-b4f22d00-8277-11e9-838a-b74a2b86a4a3.png)

I think it's here around [line 52](https://github.com/ghacksuserjs/TorZillaPrint/blob/master/js/canvas.js#L52)
```js
  catch (e){
   // we could catch e.message and output something different?
    return type + ": not supported";
  }

```

@kkapsner

**Comment by Thorin-Oakenpants** [comment]
Edit: ^^ or I'm reading that wrong, and webgl2 is indeed blocked? Maybe that's what we should output: supported, not supported, or blocked

**Comment by kkapsner** [comment]
The thing is that there are two things: first the hardware and operating system/drivers must support webgl2 and then it has to be enabled in Firefox. If either of these two requirements are not met "not supported" is shown as the browser cannot use it.

As far as I know some special settings have to be done in the VM to make webGL2 work there. So the output is correct and we have no way to tell where webGL2 is disabled.

**Comment by Thorin-Oakenpants** [comment]
Thanks for the info. Totally get that the output in this FF example is correct: i.e. FF won't use it so therefore "not supported". There's *probably* more entropy to be gained here, but I need to wait for TB9.0a2 with the webgl fixes to land.

Normally, when I return something is enabled/disabled that's a reference to Firefox and usually a pref, and can be as easy as e.g `navigator.cookieEnabled == true` .. after that something may block it = more entropy.

Not saying that there is an easy is `wegl2` pref enabled test. You're the expert. And I'll have to see what TB does with those errors: maybe they suppressed them which is why cypherpunks said with webgl2 disabled it was reported as supported. That's what sparked this topic.

I could trap the error and output something like `supported [but blacklisted]`?

Once again, thanks for your input :+1:

**Comment by Thorin-Oakenpants** [comment]
@kkapsner just something for you to look at

- https://www.usenix.org/conference/usenixsecurity19/presentation/wu
- paper: https://www.usenix.org/system/files/sec19fall_wu_prepub.pdf
- addon: https://github.com/UniGL

Basically, control floating-point operations and you reduce the FP to one. Out of my depth, but there you go. Build the addon and see what happens? I'd be keen to test drive it in Dev/Nightly in my VMs

**Comment by kkapsner** [comment]
Interesting. But as far as I understand the addon it does not provide any protection. It's just a demo of the compiler.

**Comment by Thorin-Oakenpants** [comment]
AFAIK this is resolved. I added error entropy to the canvas webgl output and I will investigate further when I add the webgl section in my todo list issue (i.e the error entropy in VMs and with different slider settings and/or some webgl pref flips)
