### ISSUE TITLE
reminder: targeted font lists

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/TorZillaPrint#43]
I'm making this up as I go along: also Arthur's original list is old: e.g it doesn't even include San Francisco: the default system font since MacOS 10.11

Running massive font lists is slow and pointless. We already know that Tor Browser uses a whitelist in Windows and Mac (Linux I need to check: uses `font.conf`), Android IDK yet.

I have split the enumerate fonts into two: **targeted** (small) and **large** (all).
- Large is simply to show that without a whitelist, it's easy to pick up on extra fonts: e.g those provided by Adobe, or custom added by the end user.
- Large is also a fallback test I can use to compare targeted with to see if I missed anything
- Targeted is aimed at seeing what entropy exists with whitelists. Using MS documentation of supplied fonts per OS, various font families have expanded or been added/removed: and entropy exists when some Windows OS's have `Arial Narrow` and some don't , but both have `Arial` etc.

So **targeted** lists are based on the OS (which I can 100% reliably detect)

Example: Windows
   * include everything in Tor Browser's whitelist
   * fix the typo for `JengHei` (with no h) to `JhengHei` (TB will do so as well)
   * add the two Mozilla supplied emoji fonts: one in FF, one in TB (TB are meant to whitelist theirs)
   * add all `Noto Sans` language fonts which TB like to bundle, including some for future proofing for new language packs
   * build master list: 444 fonts supplied with Windows: Win7 or higher
      * see here: https://docs.microsoft.com/en-us/typography/fonts/windows_7_font_list and subsequent releases
   * add all fonts (from the master list) for each font family in the whitelist: e.g `Arial` -> add `Arial Narrow`, `Arial Black` etc: this should leak entropy over different OS releases
   * add in some system fonts: maybe these can't be blocked or are used by the UI: examples: `Times`, `Roman`, `Small Fonts`, `Courier` - need to investigate this a bit more

Now we end up with a targeted windows list of 197 fonts vs running the large list of approx 1400 which adds no extra entropy (or shouldn't)

ToDo:
* [x] set a global os variable based on auto-run tests when the page loads
* [x] build the targeted win list: 197
* [ ] build the targeted mac list: from 10.9+ master list: i have apple docs to build this
* [ ] build the targeted linux list : not sure how to do this: need to add Heebo, Roboto* for starters
* [ ] build the targeted android list : still researching: have an idea
* [x] when running targeted, select the right list based on global os variable [done, just need to switch it on, currently hard-coded an example windows list]
* [ ] re-do the large list:
      * include everything from the targeted lists
      * add "a few" popular fonts from other programs (no idea on what basis Arthur made his list)
      * we don't need too many, since the point about entropy is already made
      * e.g fpjs2 checks 64 fonts

So hopefully, I will end up with four fast small lists to "test" tor browser with, and one large one to catch anything that falls through: e.g: so far all my Windows tests on TB: both large and targeted - same result per machine/vm.

---

Followups:
 * [ ] https://bugzilla.mozilla.org/show_bug.cgi?id=1121643#c84 - as already mentioned, I found some fonts not in the whitelist (windows) that were still detected: Roman, Times, Small Fonts, Courier ... 
 * [ ] https://bugzilla.mozilla.org/show_bug.cgi?id=1121643#c64 (see quote below)

> If your system is running the DirectWrite font backend (i.e. if hardware acceleration is enabled), then Arial Black is not a valid font-family name (it's a face within the extended Arial family) - see: [644385](https://bugzilla.mozilla.org/show_bug.cgi?id=644385)
> 
> The same applies to other faces in your list such as Segoe UI Light and Segoe UI Semibold; and others are legacy bitmap-only or vector fonts (e.g. FixedSys, HELV, Terminal) that DirectWrite does not support. So those fonts will not appear as available, regardless of the presence of the whitelist.

**Comment by Thorin-Oakenpants** [comment]
Source: https://docs.microsoft.com/en-us/typography/fonts/windows_7_font_list
 - and subsequent entries on the left hand side menu

<details><summary>444 Windows 7, 8, 8.1, 10 Fonts</summary><p>

```
Aharoni Bold
Aldhabi
Andalus
Angsana New
Angsana New Bold
Angsana New Bold Italic
Angsana New Italic
AngsanaUPC
AngsanaUPC Bold
AngsanaUPC Bold Italic
AngsanaUPC Italic
Aparajita
Aparajita Bold
Aparajita Bold Italic
Aparajita Italic
Arabic Typesetting
Arial
Arial Black
Arial Bold
Arial Bold Italic
Arial Italic
Arial Nova
Arial Nova Bold
Arial Nova Bold Italic
Arial Nova Cond
Arial Nova Cond Bold
Arial Nova Cond Bold Italic
Arial Nova Cond Italic
Arial Nova Cond Light
Arial Nova Cond Light Italic
Arial Nova Italic
Arial Nova Light
Arial Nova Light Italic
BIZ UDGothic
BIZ UDGothic Bold
BIZ UDMincho Medium
BIZ UDPGothic
BIZ UDPGothic Bold
BIZ UDPMincho Medium
Bahnschrift
Batang
BatangChe
Browallia New
Browallia New Bold
Browallia New Bold Italic
Browallia New Italic
BrowalliaUPC
BrowalliaUPC Bold
BrowalliaUPC Bold Italic
BrowalliaUPC Italic
Calibri
Calibri Bold
Calibri Bold Italic
Calibri Italic
Calibri Light
Calibri Light Italic
Cambria
Cambria Bold
Cambria Bold Italic
Cambria Italic
Cambria Math
Candara
Candara Bold
Candara Bold Italic
Candara Italic
Candara Light
Candara Light Italic
Comic Sans MS
Comic Sans MS Bold
Comic Sans MS Bold Italic
Comic Sans MS Italic
Consolas
Consolas Bold
Consolas Bold Italic
Consolas Italic
Constantia
Constantia Bold
Constantia Bold Italic
Constantia Italic
Corbel
Corbel Bold
Corbel Bold Italic
Corbel Italic
Corbel Light
Corbel Light Italic
Cordia New
Cordia New Bold
Cordia New Bold Italic
Cordia New Italic
CordiaUPC
CordiaUPC Bold
CordiaUPC Bold Italic
CordiaUPC Italic
Courier New
Courier New Bold
Courier New Bold Italic
Courier New Italic
DFKai-SB
DaunPenh
David
David Bold
DengXian Bold
DengXian Light
DilleniaUPC
DilleniaUPC Bold
DilleniaUPC Bold Italic
DilleniaUPC Italic
DokChampa
Dotum
DotumChe
Ebrima
Ebrima Bold
Estrangelo Edessa
EucrosiaUPC
EucrosiaUPC Bold
EucrosiaUPC Bold Italic
EucrosiaUPC Italic
Euphemia
FangSong
FrankRuehl
Franklin Gothic Medium
Franklin Gothic Medium Italic
FreesiaUPC
FreesiaUPC Bold
FreesiaUPC Bold Italic
FreesiaUPC Italic
Gabriola
Gadugi
Gadugi Bold
Gautami
Gautami Bold
Georgia
Georgia Bold
Georgia Bold Italic
Georgia Italic
Georgia Pro
Georgia Pro Black
Georgia Pro Black Italic
Georgia Pro Bold
Georgia Pro Bold Italic
Georgia Pro Cond
Georgia Pro Cond Black
Georgia Pro Cond Black Italic
Georgia Pro Cond Bold
Georgia Pro Cond Bold Italic
Georgia Pro Cond Italic
Georgia Pro Cond Light
Georgia Pro Cond Light Italic
Georgia Pro Cond Semibold
Georgia Pro Cond Semibold Italic
Georgia Pro Italic
Georgia Pro Light
Georgia Pro Light Italic
Georgia Pro Semibold
Georgia Pro Semibold Italic
Gill Sans Nova
Gill Sans Nova Bold
Gill Sans Nova Bold Italic
Gill Sans Nova Cond
Gill Sans Nova Cond Bold
Gill Sans Nova Cond Bold Italic
Gill Sans Nova Cond Italic
Gill Sans Nova Cond Lt
Gill Sans Nova Cond Lt Italic
Gill Sans Nova Cond Ultra Bold
Gill Sans Nova Cond XBd
Gill Sans Nova Cond XBd Italic
Gill Sans Nova Italic
Gill Sans Nova Light
Gill Sans Nova Light Italic
Gill Sans Nova Ultra Bold
Gisha
Gisha Bold
Gulim
GulimChe
Gungsuh
GungsuhChe
Impact
Ink Free
IrisUPC
IrisUPC Bold
IrisUPC Bold Italic
IrisUPC Italic
Iskoola Pota
Iskoola Pota Bold
JasmineUPC
JasmineUPC Bold
JasmineUPC Bold Italic
JasmineUPC Italic
Javanese Text
KaiTi
Kalinga
Kalinga Bold
Kartika
Kartika Bold
Khmer UI
Khmer UI Bold
KodchiangUPC
KodchiangUPC Bold
KodchiangUPC Bold Italic
KodchiangUPC Italic
Kokila
Kokila Bold
Kokila Bold Italic
Kokila Italic
Lao UI
Lao UI Bold
Latha
Latha Bold
Leelawadee
Leelawadee Bold
Leelawadee UI
Leelawadee UI Bold
Leelawadee UI Leelawadee UI
Leelawadee UI Semilight
Levenim MT
Levenim MT Bold
LilyUPC
LilyUPC Bold
LilyUPC Bold Italic
LilyUPC Italic
Lucida Console
Lucida Sans Unicode
MS Gothic
MS Mincho
MS PGothic
MS PMincho
MS UI Gothic
MV Boli
Malgun Gothic
Malgun Gothic Bold
Malgun Gothic Semilight
Mangal
Mangal Bold
Marlett
Meiryo
Meiryo Bold
Meiryo Bold Italic
Meiryo Italic
Meiryo UI
Meiryo UI Bold
Meiryo UI Bold Italic
Meiryo UI Italic
Microsoft Himalaya
Microsoft JhengHei
Microsoft JhengHei Bold
Microsoft JhengHei Light
Microsoft JhengHei Regular
Microsoft JhengHei UI
Microsoft JhengHei UI Bold
Microsoft JhengHei UI Light
Microsoft JhengHei UI Regular
Microsoft New Tai Lue
Microsoft New Tai Lue Bold
Microsoft PhagsPa
Microsoft PhagsPa Bold
Microsoft Sans Serif
Microsoft Tai Le
Microsoft Tai Le Bold
Microsoft Uighur
Microsoft Uighur Bold
Microsoft YaHei
Microsoft YaHei Bold
Microsoft YaHei Light
Microsoft YaHei UI
Microsoft YaHei UI Bold
Microsoft YaHei UI Light
Microsoft Yi Baiti
MingLiU
MingLiU-ExtB
MingLiU_HKSCS
MingLiU_HKSCS-ExtB
Miriam
Miriam Fixed
Mongolian Baiti
MoolBoran
Myanmar Text
Myanmar Text Bold
NSimSun
Narkisim
Neue Haas Grotesk Text Pro
Neue Haas Grotesk Text Pro Bold
Neue Haas Grotesk Text Pro Bold Italic
Neue Haas Grotesk Text Pro Italic
Neue Haas Grotesk Text Pro Medium
Neue Haas Grotesk Text Pro Medium Italic
Nirmala UI
Nirmala UI Bold
Nirmala UI Semilight
Nyala
PMingLiU
PMingLiU-ExtB
Palatino Linotype
Palatino Linotype Bold
Palatino Linotype Bold Italic
Palatino Linotype Italic
Plantagenet Cherokee
Raavi
Raavi Bold
Rockwell Nova
Rockwell Nova Bold
Rockwell Nova Bold Italic
Rockwell Nova Cond
Rockwell Nova Cond Bold
Rockwell Nova Cond Bold Italic
Rockwell Nova Cond Italic
Rockwell Nova Cond Light
Rockwell Nova Cond Light Italic
Rockwell Nova Extra Bold
Rockwell Nova Extra Bold Italic
Rockwell Nova Italic
Rockwell Nova Light Italic
Rockwell Nova Rockwell
Rod
Sakkal Majalla
Sakkal Majalla Bold
Sanskrit Text
Segoe MDL2 Assets
Segoe Print
Segoe Print Bold
Segoe Pseudo
Segoe Script
Segoe Script Bold
Segoe UI
Segoe UI Black
Segoe UI Black Italic
Segoe UI Bold
Segoe UI Bold Italic
Segoe UI Emoji
Segoe UI Historic
Segoe UI Italic
Segoe UI Light
Segoe UI Light Italic
Segoe UI Semibold
Segoe UI Semibold Italic
Segoe UI Semilight
Segoe UI Semilight Italic
Segoe UI Symbol
Shonar Bangla
Shonar Bangla Bold
Shruti
Shruti Bold
SimHei
SimSun
SimSun-ExtB
Simplified Arabic
Simplified Arabic Bold
Simplified Arabic Fixed
Sitka Banner
Sitka Banner Bold
Sitka Banner Bold Italic
Sitka Banner Italic
Sitka Display
Sitka Display Bold
Sitka Display Bold Italic
Sitka Display Italic
Sitka Heading
Sitka Heading Bold
Sitka Heading Bold Italic
Sitka Heading Italic
Sitka Small
Sitka Small Bold
Sitka Small Bold Italic
Sitka Small Italic
Sitka Subheading
Sitka Subheading Bold
Sitka Subheading Bold Italic
Sitka Subheading Italic
Sitka Text
Sitka Text Bold
Sitka Text Bold Italic
Sitka Text Italic
Sylfaen
Symbol
Tahoma
Tahoma Bold
Times New Roman
Times New Roman Bold
Times New Roman Bold Italic
Times New Roman Italic
Traditional Arabic
Traditional Arabic Bold
Trebuchet MS
Trebuchet MS Bold
Trebuchet MS Bold Italic
Trebuchet MS Italic
Tunga
Tunga Bold
UD Digi Kyokasho N-B
UD Digi Kyokasho N-R
UD Digi Kyokasho NK-B
UD Digi Kyokasho NK-R
UD Digi Kyokasho NP-B
UD Digi Kyokasho NP-R
Urdu Typesetting
Urdu Typesetting Bold
Utsaah
Utsaah Bold
Utsaah Bold Italic
Utsaah Italic
Vani
Vani Bold
Verdana
Verdana Bold
Verdana Bold Italic
Verdana Italic
Verdana Pro
Verdana Pro Black
Verdana Pro Black Italic
Verdana Pro Bold
Verdana Pro Bold Italic
Verdana Pro Cond
Verdana Pro Cond Black
Verdana Pro Cond Black Italic
Verdana Pro Cond Bold
Verdana Pro Cond Bold Italic
Verdana Pro Cond Italic
Verdana Pro Cond Light
Verdana Pro Cond Light Italic
Verdana Pro Cond SemiBold
Verdana Pro Cond SemiBold Italic
Verdana Pro Italic
Verdana Pro Light
Verdana Pro Light Italic
Verdana Pro SemiBold
Verdana Pro SemiBold Italic
Vijaya
Vijaya Bold
Vrinda
Vrinda Bold
Webdings
Wingdings
Yu Gothic Bold
Yu Gothic Light
Yu Gothic Medium
Yu Gothic Regular
Yu Gothic UI Bold
Yu Gothic UI Light
Yu Gothic UI Regular
Yu Gothic UI Semibold
Yu Gothic UI Semilight
Yu Mincho Demibold
Yu Mincho Light
Yu Mincho Regular
```

</p></details>

**Comment by Thorin-Oakenpants** [comment]
@tomrittervg Are some system fonts, such as those used by the UI, always available? Where would I find this per OS?

Followups:
 * [ ] https://bugzilla.mozilla.org/show_bug.cgi?id=1121643#c84 - as already mentioned, I found some fonts not in the whitelist (windows) that were still detected: Roman, Times, Small Fonts, Courier ...

**Comment by tomrittervg** [comment]
The code has a case that if no whitelisted font was found, the whitelist is ignored: https://searchfox.org/mozilla-central/rev/5e830ac8f56fe191cb58a264e01cdbf6b6e847bd/gfx/thebes/gfxPlatformFontList.cpp#326

Other than that, I do not see anything about giving exceptions to fonts.

**Comment by Thorin-Oakenpants** [comment]
Yeah. I knew that - https://github.com/ghacksuserjs/ghacks-user.js/blob/master/user.js#L804 - which is why I made sure to have a value in there :) It's definitely not ignoring the whitelist, because otherwise it would find lots, not just those I listed above

**Comment by tomrittervg** [comment]
It's not just that it has to be non-empty, it has to have a font you have on your system. You said "tested with a whitelist that was just a single non-existent font" - that's going to have the behavior of ignoring the whitelist as if the pref was empty.

**Comment by Thorin-Oakenpants** [comment]
OK, I'll test that .. but 99% sure it won't make a difference because these fonts show up in TB with the TB whitelist, and they're not listed in that whitelist. There's something else going on here

**Comment by Thorin-Oakenpants** [comment]
@tomrittervg 

Well .. it **used to work** that way. I just checked in FF67 (but can't seem to replicate it in nightly)

See the 18 fonts found by both methods: that's the 18 fonts not in TB whitelist, listed above

![FontStuff](https://user-images.githubusercontent.com/16656956/66711201-eecf5600-ed76-11e9-9c5b-a5459d5ccdf5.png)

---
Vanilla FF71: windows
- ✅ both methods return 69/144 fonts in the whitelist test and 105/475 in the os test
- ✅ these include the aforementioned 18 fonts: Courier, Helvetica, Small Fonts etc

Add whitelist pref and TB's windows value
-  ✅ all four tests return 63/144
-  ✅ these include the aforementioned 18 fonts which are NOT in the whitelist

Change whitelist to `Times New Roman` for example
- ❌ not perfect results: fpjs gets 15 of the 18 fonts, and can't find `Times New Roman`
-  ✅ fallback gets all 18 fonts and `Times New Roman`

if I test with `Arial` as the only font
- ❌ not perfect: fpjs2 gets 16 of the 18 fonts and finds `Arial Black` + `Arial Narrow` (but not `Arial`)
-  ✅ fallback gets all 18 fonts and detects `Arial`, `Arial Black`, `Arial Narrow`

I've known this for a while: the fallback method is totally more reliable: it's almost bulletproof: but I'm testing rather extreme setups here.

So, not sure what changed between 67 and 71: but the UI doesn't go to hell like in the pic. And clearly my non-existent font trick doesn't work anymore: but using single font in the system does with arthur's fallback font method.

Still: why does FF still detect these 18 fonts which are not in the whitelist

**Comment by Thorin-Oakenpants** [comment]
no need to keep this open, it's tracked in my todo list issue

**Comment by KOLANICH** [comment]
>Using MS documentation of supplied fonts per OS, various font families have expanded or been added/removed

It depends on presence of MS Office. If Office is installed, its fonts (Calibri, Cambria, etc) are available in XP and 7 if I remember right. But in 10 these fonts are shipped with the OS.

**Comment by Thorin-Oakenpants** [comment]
Yeah. The full OS targeted list *should* include them all: but there's still an issue with specific fonts per language setup: see https://bugzilla.mozilla.org/show_bug.cgi?id=1582687

This is why I am only really targeting the whitelisting feature in TB by OS. AFAIConcerned, any setup that doesn't protect fonts in some way, is probably unique if we dig deep enough (excluding out of the box vm's, platforms). There's already lots of entropy in TB in window fonts as it is.

Long story short, the only way to truly defeat this is to bundle all the fonts and block all system fonts.

Building in these font tests is low priority for me: it's already proven. I'm going to provide one that detects entropy within a font: e.g. Times New Roman or Arial - by detecting glyphs as they get added per release (from windows 7 on): so it'll be like: e.g 20 versions
- glyph1, glyph2, ... gylph20
- true, true, true, false = version x
- true, true, true, true, false = version y

Not sure how effective it will be: depends if software/os patches update them and what each OS ships with. But it is entropy. I'm using Times New Roman since that is the default en-US font. This is on my todo list
