### ISSUE TITLE
js newbie calling kkapsner

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/TorZillaPrint#48]
@kkapsner ... so I have this really ugly hack where I'm concatenating parts, but I don't know how many parts there are

```js
		function concat_parts(length, value) {
			// must an more elegant way to do this: languages vary in number of parts
			let output = "";
			let rtf2 = new Intl.RelativeTimeFormat(undefined, {style: "long", numeric: "auto"});
			let rtf3 = rtf2.formatToParts(length, value);
			try {
				output = rtf3[0].value + rtf3[1].value + rtf3[2].value + rtf3[3].value;
			} catch(e) {
				try {
					output = rtf3[0].value + rtf3[1].value + rtf3[2].value;
				} catch(e) {
					try {
						output = rtf3[0].value + rtf3[1].value;
					} catch(e) {
						output = rtf3[0].value;
					}
				}
			}
			return output;
		};
```

Notes:
- I only call the function if `[formatToParts] Intl.RelativeTimeFormat` is supported (**you need FF70+**)
- I'm doing multiple tests and concatenating them

example
```js
			let tmp18 = concat_parts("-1", "year")
				+ ", " + concat_parts("-3", "week")
				+ ", " + concat_parts("-1", "hour")
				+ ", " + concat_parts("45", "second")
				+ ", " + concat_parts("1", "day")
				+ ", " + concat_parts("1", "quarter");

```

and this gives me my output: e.g
- `last year, 3 weeks ago, 1 hour ago, in 45 seconds, tomorrow, next quarter`

so back to the first bit of code: the problem is I don't know how many parts there are: i.e different languages can have a different number of parts depending on the arguments
- e.g. (made up example) for `"-1", "year"` english might be two parts, but hungarian three parts

Phew .. almost there .. is there a simple check here to return the number of parts and cover ever possible language in do while x=0 loop then till end of parts?

**Comment by Thorin-Oakenpants** [comment]
here, this might make more sense

<details><summary>single file test with multiple languages</summary><p>

```html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<title>join parts</title>
<style>
body {background-color: white; color: black;}
</style>
</head>
<body>

<br>
<div><b>english us</b><br><span id="en"></span></div>
<div><b>spanish:</b><br><span id="es"></span></div>
<div><b>german:</b><br><span id="de"></span></div>

<script>
	let tmp18 = "";
	// FF70+: Intl.RelativeTimeFormat formatToParts
	function concat_parts(language, length, value) {
		// must an more elegant way to do this: languages vary in number of parts
		let output = "";
		let rtf2 = new Intl.RelativeTimeFormat(language, {style: "long", numeric: "auto"});
		let rtf3 = rtf2.formatToParts(length, value);
		try {
			output = rtf3[0].value + rtf3[1].value + rtf3[2].value + rtf3[3].value + " [4]";
		} catch(e) {
			try {
				output = rtf3[0].value + rtf3[1].value + rtf3[2].value + " [3]";
			} catch(e) {
				try {
					output = rtf3[0].value + rtf3[1].value + " [2]";
				} catch(e) {
					output = rtf3[0].value + " [1]";
				}
			}
		}
		return output;
	};
	function get_values(l) {
		tmp18 = concat_parts(l, "-1", "year")
			+ ", " + concat_parts(l, "-3", "week")
			+ ", " + concat_parts(l, "-1", "hour")
			+ ", " + concat_parts(l, "45", "second")
			+ ", " + concat_parts(l, "1", "day")
			+ ", " + concat_parts(l, "1", "quarter");
		return tmp18
	}

	document.getElementById("en").innerHTML = get_values("en-US");
	document.getElementById("es").innerHTML = get_values("es");
	document.getElementById("de").innerHTML = get_values("de");

</script>
</body>
</html>
```

</p></details>

output

![meh](https://user-images.githubusercontent.com/16656956/70581639-c2d22480-1baf-11ea-9977-5542ffb84592.png)

as you can see when we use `"-3", "week"` .. in en-us it's 2 parts but 3 in spanish and german.

The issue is my hacky code is 1) hacky and 2) doesn't cover klingon which might be 20 parts

**Comment by Thorin-Oakenpants** [comment]
MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RelativeTimeFormat/formatToParts

What use is this if coders don't know how many parts there are, and what each part stands for. See the MDN example for "in 10 seconds"

**Comment by Thorin-Oakenpants** [comment]
nvm .. as per usual I need MOAR coffee .. its an array and I can get the length. Thanks 💋

**Comment by Thorin-Oakenpants** [comment]
I enjoy these chats I have to myself ... I should get out more

**Comment by kkapsner** [comment]
I know this. You talk to someone to get advice on a problem. And as you finish you find the solution yourself. Just the action of formulating the problem so that somebody else understands it often helps by itself.
