### ISSUE TITLE
canvas: detect API block

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/TorZillaPrint#52]
@kkapsner 

So, locally not live, I detect when CB is causing measureText problems via error trapping: settings
- general: block everything
- API: canvas: protect `input` or `everything`
- this is the only setting (using file:// if that makes a diff) where I can get CB to cause a problem

note: the hash in the pic is a sha1 of an `empty string`, but that's not how I detect `measureText` is blocked in some way, I use a try/catch when I set `ctx.font` property (ctx was set earlier: `ctx = canvas.getContext("2d")` with no problems)

![hellyeah](https://user-images.githubusercontent.com/16656956/75895295-57ee5d80-5e2d-11ea-9876-92cf5ac3019a.png)

---

What I've noticed is that the canvas section which you wrote fails silently and is all empty. I'd still like to output something for display, but more importantly, in terms of fingerprinting, we still need values

The setting I used so far (I think a few different configs for canvas might cause it), is
- general: block

![hellnah](https://user-images.githubusercontent.com/16656956/75895735-f67abe80-5e2d-11ea-86cc-e7b5b94e22d3.png)

I did see something in the console at one stage when I was testing configs for my measureText, but not anymore. I can't tell if all the tests ran properly and just didn't output anything by design

Can you have a look? First that all tests are actually run/aborted correctly - and if aborted, how I can catch that to output something - TIA

**Comment by kkapsner** [comment]
The block mode is very much detectable. `ctx` will be undefined and code will fail left and right. So no surprises there.

I created a pull request for the canvas section.

**Comment by Thorin-Oakenpants** [comment]
Awesome - I'll merge it later for testing and build it into my local copy - I just wasn't sure where to apply the checks

**Comment by Thorin-Oakenpants** [comment]
merged: just did a quick test (obviously with no RFP):
- General> `block everything`
- APIs> only canvas is enabled, setting is default  "readout"

ignore the RFP notation/colors: I will check/fix those up later
 - `957c80fa4be3af7e53b40c852edf96a090f09958cc7f832aaf9a9fd544fb69a8` for isPointInPath is the correct hash for RFP returns, that's interesting that blocking canvas is the same

So these look right
- toBlob => error message
- getImageData => error message
- winding => changes to not supported
- `webgl` - it's not canvas, and we pick up on webgl being blocked already

**not sure about these** ❓ 
- `toDataBlob` : how do I trigger that being blocked?
- `mozGetAsFile` - I will test on an older Firefox
- `isPoint*` - not sure if this is by design: i.e it still produces a hash and it happens to match RFP
- `fillText` + `strokeText` <-- still returns supported - this dffers from `winding` which changes

pic: top is with CB, bottom is no CB
![canvas-block](https://user-images.githubusercontent.com/16656956/76136961-555b5600-602f-11ea-8304-3ee60648a689.png)

**Comment by Thorin-Oakenpants** [comment]
-  General> block everything
-  APIs> only canvas is enabled, setting is "block everything"

looks good
![canvas-block](https://user-images.githubusercontent.com/16656956/76137201-ecc1a880-6031-11ea-9c54-d9c011e83ba5.png)

**Comment by Thorin-Oakenpants** [comment]
^^ Right, so it's the input vs readout differences => difference results = entropy = excellent AF

For the six items RFP items (the five shown + mozGetAsFile when it's supported), i.e the canvas hashs - the RFP notation is correct and should still be shown

So I **think** we're all good here  - right? As always, excellent work kapsner 💋

**Comment by Thorin-Oakenpants** [comment]
hmm .. I just tested with RFP enabled as well and seems like CB (at least in this test) still affects the results. My understanding was that if RFP is being applied, CB doesn't kick in .. 

or was that only when you don't General > block ?

**Comment by kkapsner** [comment]
> So I **think** we're all good here - right?

I think as well. Especially after you answered your own question.

**Comment by Thorin-Oakenpants** [comment]
agreed - we're good on the output and any entropy in that - closing

but still intrigued why isPoint* returns same as RFP

**Comment by Thorin-Oakenpants** [comment]
- Instead of adding RFP notation to just the six possible hash values, I now do it for all of them (canvas, not webgl)
- to kept the lengths down I strip the e.name if it is TypeError (All of canvas errors that have an e.name reported are TypeError). So far, webGL errors are not a TypeError, and if it was, the lack of a e.name would be the entropy.
- mozGetAsFile takes into account that it was dropped in FF74

So overall, I think this looks a little cleaner/spacier [note: i have trimmed the pic, so you're not seeing the whole width], and is more informative

I'll upload the changes when I do my big batch of stuff from the last month

top: general block, api = input or everything
middle: general block, api = readout
bottom: general fake api = immaterial / or FF without RFP or CB
![canvas](https://user-images.githubusercontent.com/16656956/76163842-a5c2d880-6141-11ea-8a9b-70879c5607c8.png)
