### ISSUE TITLE
expand on textMetrics vs DOMRect

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/TorZillaPrint#55]
snip

**Comment by kkapsner** [comment]
About which additional text metrics are you thinking?

**Comment by Thorin-Oakenpants** [comment]
the lot :)

**Comment by kkapsner** [comment]
All these new measures are all covered by CB in the latest version. And the test page also outputs a "all" hash and a hash for the different properties individually.

As this all depends heavily on the font rendering I would expect that there is some entropy in these (that's why I included them in CB). But I have no real world data (and at the moment no time to fetch some).

So I think it's a good idea to investigate into that direction with TZP. What is useful to display really depends on real world data. So to have it as granular as possible at the start would help to get an overview. It the entropy is in fact not that high you can reduce the display later.
Also the red/green notation should be adapted to the real world findings.

PS: the high diff on android is interesting and I think your assumptions about the subpixels sounds reasonable. But on desktop it's still good and telling these two apart is quite easy.

**Comment by Thorin-Oakenpants** [comment]
> As this all depends heavily on the font rendering

Yup. My thinking is that textMetrics are for fonts, so adding it to the already existing unicode glyphs is perfect. That same test already had a `getBoundingClientRects` for kicks. But I guess I got side-tracked on this diffs issue - which I'm really beginning to think is not needed (but can still do) as the entropy of that is already present

And then thinking about it more, the unicode glyphs setup also seemed like a good spot to analyze domrect: but I half-assed it and added only one more method

I guess this ticket was to convince myself that the current test is a bit sh^t :)

> But I have no real world data

The unicode glyph list causes entropy with just offsetHeight. To truly know we would have to eliminate the font (use a downloadable font), probably eliminate devicePixelRatio in controlled tests - maybe math + floats play a part in these high precision measurements - maybe the graphics card. IDK. All I know is that bundling all these together is making a nasty FP.

---

OT: My aim is to
- get all these tests created and perfected
- build a backend for users to submit to
    - it would only submit Firefox/Tor Browser ESR68+ which I can 100% detect with JS
- the data from drive-by submitters would give an idea of the how many **different results** a given metric produces
- the frontend would also include a reporting side for slicing and dicing data
- the backend/frontend could handle "experiments"
   - e.g. if Mozilla pushed one: so we could get one result per browser to try and get some idea of the actual real world entropy
   - and if it was hosted on a mozilla domain they could use even make it a privileged domain and push special powers (e.g. getting architecture, os version)
  - or as an experiment extension it could also get extra info for analysis: not as a FPing metric but in order to see what causes the entropy

And I was hoping for more people (with better skills and knowledge than me) would help - PS: thanks ever so much for your help kkapsner :kiss: .. but here I am, over a year later, still trying to finish off the first part :) And some parts have to wait until it has it's own domain (http headers, ciphers)

I strongly believe that without Firefox specific data, we're in the dark a fair bit - and can't make informed decisions. Trying to infer anything from sites like amiunique or panoticlick etc are a waste of time. Anti-FPing seems to have mostly hit a roadblock at Mozilla since FF60 and it's taken a backseat. And most tickets/ideas still open are stalled due to lack of knowing what to do.

I guess I'll have to ramp up my efforts, and stop bike shedding

**Comment by Thorin-Oakenpants** [comment]
@kkapsner - I think I'm going to need some guidance here

So part one: get textMetrics
- width: that's good (and we can use that to compare to domrect later)
- the rest I'm having trouble with

in my code I loop `j` chars thru `i` styles
mgo = true by default and fails if measuretext is blocked (or canvas?) - not sure if I want this now if I am doing multiple textMetrics (I don't think it's any faster to skip than it is to error)
```js
//earlier
let canvas = dom.ugCanvas, ctx = canvas.getContext("2d")

// inside the loops
				// measure
				if (mgo) {
					try {
						ctx.font = "normal normal 22000px " + (j == 0 ? "none" : styles[j])
						let tm = ctx.measureText(c)
						m = tm.width
						measure.push( (j==0 ? cp+"-" : "" ) + m)
						unique.push(m)
						// debug fist char, first style
						if (j == 0 && i == 0) {
							console.debug("width", m )
							console.debug("actualBoundingBoxLeft", tm.actualBoundingBoxLeft)
							console.debug("actualBoundingBoxRight", tm.actualBoundingBoxRight)
							console.debug("actualBoundingBoxAscent", tm.actualBoundingBoxAscent)
							console.debug("actualBoundingBoxDescent", tm.actualBoundingBoxDescent)
							// undefined
							console.debug("fontBoundingBoxAscent", tm.fontBoundingBoxAscent)
							console.debug("fontBoundingBoxDescent", tm.fontBoundingBoxDescent)
							console.debug("emHeightAscent", tm.emHeightAscent)
							console.debug("emHeightDescent", tm.emHeightDescent)
							console.debug("hangingBaseline", tm.hangingBaseline)
							console.debug("alphabeticBaseline", tm.alphabeticBaseline)
							console.debug("ideographicBaseline", tm.ideographicBaseline)
						}
					} catch(err) {mgo = false}
				}
```

this gives me
![console](https://user-images.githubusercontent.com/16656956/77363610-f560f100-6d4a-11ea-9537-6e5f64f19fc7.png)

Now obviously I don't want `undefined`. 
- https://developer.mozilla.org/en-US/docs/Web/API/TextMetrics
- https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/textBaseline

And (second link) I'm also wondering what is the significance (and how) to get 
- baselines = ['top', 'hanging', 'middle', 'alphabetic', 'ideographic', 'bottom']

**Comment by Thorin-Oakenpants** [comment]
ahhh ... Nightly 76 still has these prefs at default false. If I flip em on...

`dom.textMetrics.baselines.enabled`
```
hangingBaseline 1287.2234762979685
alphabeticBaseline -0
ideographicBaseline -195.48532731376974
```

`dom.textMetrics.fontBoundingBox.enabled`
```
fontBoundingBoxAscent 1782
fontBoundingBoxDescent 433
```

dom.textMetrics.emHeight.enabled
```
emHeightAscent 1609.0293453724605
emHeightDescent -390.9706546275395
```

So that explains that bit

**Comment by Thorin-Oakenpants** [comment]
@kkapsner  ok .. give it a whirl if you want

![textmetrics](https://user-images.githubusercontent.com/16656956/77379468-ab8b0180-6d70-11ea-80a0-91c3ece02eae.png)

- I *think* the code could be a lot more elegant. streamlined: so open to ideas
- all 12 textMetric results rely on canvas 2d: so if that is blocked nothing is ever added to each result array, and the hash of those arrays tells me that the items are blocked
- you can set settings to block everything (general) and (apis>everything) but untick `canvas 2d` - to get canvas to work but each textMetric to be blocked
    - there's quite a few possible combinations of settings here and I ended up with `width` returning the string "undefined" and the number of unique measureText.widths was `1` :) - I now pick up on this and output it (and also don't output diffs to console.log)
    - I cannot tell the difference between when CB blocks or the method is not supported: they both return `undefined` (not a string)
   - ^^ but for the four `actualBounding` methods, they are FF74+ with no prefs (AFAIK) behind them, so based on the FF version, I can correctly output "not supported" or "blocked"
   - ^^ the other seven methods are behind prefs
- the textMetrics hash (i.e the one not in details) is a hash of the hashes (i.e. not a hash of every single result)
- perf doesn't seem to be affected much: I guess most of the time was already spend selecting elements and setting chars etc
- the domrect diffs etc are still compared to width: nothing's changed with that

I was hoping to be able to tell the difference between not supported and blocked - any ideas - e.g. throwing an error?

**Comment by Thorin-Oakenpants** [comment]
> but for the four actualBounding methods, they are FF74+ with no prefs (AFAIK) behind them

ok, so this has a pref too: `dom.textMetrics.actualBoundingBox.enabled`

**Comment by Thorin-Oakenpants** [comment]
So I have a way to 100% with no false positives, always detect randomization in `measureText.width` .. and I'm 99.9999% sure you can't beat code around it. It might also apply to the other textMetrics. And I think I can use this to also detect randomization in some/all domrect

If you're interested, sing out - @kkapsner

**Comment by kkapsner** [comment]
> So I have a way to 100% with no false positives, always detect randomization

Interesting approach. I could code around it... but it would get slow as hell. Especially when you start to combine different characters and not repeating the same one.

I will look at the other stuff later.

**Comment by Thorin-Oakenpants** [comment]
> ME: and I'm 99.9999% sure you can't code around it
> KK: I could code around it... but it would get slow as hell

Yeah. I meant it's an arms race and/or too problematic/complex to code against. I don't need to use the same char, because multiple chars can have the same width: try `a` and `c` for example (at least with Times New Roman). The thing is I'm just using the codepoint list for simplicity. Not all chars are good for this: some (left to right?) give false positives (hence why I stopped testing at character 11 in the array), and not all will return enough decimal places to pick anything up, and not all chars can be rendered (0 width). But I only need to find one confirmation.

Or I could just add the individual results of x random chars vs the combined of them (I assume this would work since kerning isn't a factor). I'm only using doubling for it's simplicity

**Comment by Thorin-Oakenpants** [comment]
@kkapsner 

https://thorin-oakenpants.github.io/testing/textmetrics.html

I had a look at actualBoundingBox, and I think I found an implementation flaw in how CB randomizes these. Just look at the html source code. The char list is just a,b,c etc, but I did test it with the unicode glyphs list.
- the results are unique pairings of `decimal places : last 1 or 2 decimal digits`
   - this excludes results with zero decimal places, cuz we don't care about them
- they always seem to be in multiples of `25` (i.e `.5` is treated as `.50`) 
- they always seem to max out at 7 decimal places
- same results (max decimal places, and last digits)
  - on windows with pixel ratio 1
  - on android with pixel ratio 2.602378423482394872 or whatever
  - changing default font from Times New Roman to Arial and others ( I tried a dozen)

There are some exceptions I found when adding the unicode gylphs (they're in the source code commented out)
- one char produces `13: 32` in BoxRight
- changing from Times New Roman to Arial produces `1: 8`, also in BoxRight, and a `13: 32` (not sure if this the same char as `13: 32`)

So the combo of some characters (left to right?) and fonts can cause these rules to break: the rules being 7 decimal places max, decimal places ending in multiples of 25 (treating 5 as 50)

When you enable CB's textMetric protection: see if you can spot the difference

**Comment by Thorin-Oakenpants** [comment]
I keep saying "left to right" in a few of my last comments .. I meant the opposite - I should really list exactly what those characters are to determine what it is that makes them false positives

**Comment by Thorin-Oakenpants** [comment]
I'm not going to add in any actualBounding checks becaue I believe you can easily make sure to change the length (including exceeding 13 decimal places) and to end in multiples of 25 is the real result is the same.

But I need to rethink the width randomizing detection. Initially I just checked for the first item that was 13 decimal places that failed. But then I thought, what if nothing is 13 decimals - so I did the lot, regardless of decimal places and found three of those chars gave false positives (on my machine), the first was item 11, so I limited it to the first 11 items (0-10) - which is what is currently live - but it gives me a false positive on android.

I'm thinking using the unicode glyphs list is problematic, and instead using the standard western/latin alphabet should always work .. `a,b,c etc'

That said, I find it interesting that 2x the value fails on Android vs Windows: and this in itself could be more entropy

**Comment by Thorin-Oakenpants** [comment]
hey kap ... FYI: does any of this make sense to you ... https://adtechmadness.wordpress.com/2020/03/27/detecting-privacy-badgers-canvas-fp-detection/

**Comment by kkapsner** [comment]
Sorry to get back to this topic to late...

> All I know is that bundling all these together is making a nasty FP.

Totally agree. The fingerprinters just do not use it up to now as there are much lower hanging fruits.

> Now obviously I don't want `undefined`.

You can check out https://github.com/kkapsner/CanvasBlocker/blob/master/test/textMetricsTest.js#L13 to see how I dealt with this issue. This way you can distinguish between blocked and not supported.

> And (second link) I'm also wondering what is the significance (and how) to get

This is just a property you can set on the context to specify how text is drawn. There should be no entropy in it.
But the values in the text metrics have.

> When you enable CB's textMetric protection: see if you can spot the difference

I do not get any output (despite the "random") on https://thorin-oakenpants.github.io/testing/textmetrics.html

> hey kap ... FYI: does any of this make sense to you ... https://adtechmadness.wordpress.com/2020/03/27/detecting-privacy-badgers-canvas-fp-detection/

Yes, it makes sense. That exactly the type of problem why CanvasBlocker is Firefox only. Without `exportFunction` you have a hard time to be stealthy.

**Comment by Thorin-Oakenpants** [comment]
> I do not get any output (despite the "random") on https://thorin-oakenpants.github.io/testing/textmetrics.html

So here's a vanilla FF (77)

<details><summary>no protection</summary><p>

```
actualBoundingBoxAscent
3: 75
4: 25
5: 25
5: 75
6: 75
7: 25
7: 75
actualBoundingBoxDescent
2: 25
4: 75
5: 75
6: 25
6: 75
7: 25
7: 75
actualBoundingBoxLeft
2: 25
3: 25
3: 75
4: 25
4: 75
5: 25
5: 75
6: 25
6: 75
7: 25
7: 75
actualBoundingBoxRight
2: 75
3: 75
4: 25
4: 75
5: 25
5: 75
6: 25
6: 75
7: 25
7: 75

width
control: 1775.4000244140625 (887.7000122070312)
test: 1775.4000244140625
result: not random
```

</p></details>

<details><summary>with protection</summary><p>

```
actualBoundingBoxAscent
12: 14
12: 16
12: 32
12: 37
13: 05
13: 16
13: 33
13: 34
13: 54
13: 88
13: 89
actualBoundingBoxDescent
13: 05
13: 44
13: 51
13: 67
14: 18
14: 34
14: 56
14: 66
14: 74
14: 85
14: 95
15: 34
15: 35
15: 64
2: 25
actualBoundingBoxLeft
12: 41
12: 96
13: 16
13: 44
13: 78
14: 03
14: 04
14: 07
14: 08
14: 16
14: 23
14: 24
14: 28
14: 33
14: 34
14: 37
14: 38
14: 52
14: 62
14: 69
14: 74
14: 75
14: 79
14: 81
14: 83
14: 85
14: 86
14: 91
14: 92
14: 93
14: 98
15: 06
15: 16
15: 27
15: 31
15: 52
15: 56
15: 57
15: 59
15: 64
15: 69
15: 74
15: 75
15: 77
15: 85
15: 94
2: 25
actualBoundingBoxRight
11: 59
12: 14
12: 16
12: 24
12: 26
12: 31
12: 42
12: 62
12: 65
12: 68
12: 69
12: 76
12: 84
12: 91
13: 03
13: 04
13: 08
13: 12
13: 13
13: 17
13: 18
13: 21
13: 22
13: 31
13: 33
13: 34
13: 35
13: 38
13: 43
13: 45
13: 48
13: 49
13: 53
13: 55
13: 56
13: 61
13: 65
13: 66
13: 68
13: 73
13: 74
13: 77
13: 78
13: 79
13: 81
13: 87
13: 89
13: 94
13: 95
13: 96
13: 97
14: 94
2: 75

width
control: 1775.4046756989171 (887.7023378494586)
test: 1775.3975686017243
result: random
```

</p></details>

The difference is that, at least on my Windows (and android: I forget the exact results and I will get around to more testing) is that `actualBounding`* never seems to exceed 7 decimal places, and always ends in a multiple of `25` - which makes detection of CB protection rather easy. I don't want to add this to TZP, since I believe you can easily make sure you randomness preserves this rule:
- do not increase the decimal places
- if the result ends in a multiple of .25, then continue to do the same

I'm just using the basic alphabet here (a,b,c etc) as some gylphs don't follow these "rules"

I don't know why the test page doesn't work for you?

**Comment by kkapsner** [comment]
I found why there was nothing visible for me: on Linux all the measures are integers...

If you look at the binary number it's way easier to know what's going on there: the smallest fraction is a 128th. I think I can code around that.

**Comment by Thorin-Oakenpants** [comment]
> I found why there was nothing visible for me: on Linux all the measures are integers

I really should update my VMs and do more testing - not that it would make a difference to how I would have detected randomness: i.e I would not detect false positives. But that's interesting that false negatives would occur. I wonder if this result can be used to add more entropy

> the smallest fraction is a 128th. I think I can code around that

Only if it makes sense. Detecting randomness is just binary (true/false) - and may affect the amount of randomness available in a small decimal placed results (i.e by always being a multiple of `0.0078125` = 1/128) ... and may slow things down

and therein lies the answer:
```js
 if (measurement % 0.0078125 > 0) {
   isRandom = true
}
```

**Comment by Thorin-Oakenpants** [comment]
> This way you can distinguish between blocked and not supported.

Thanks 💋 and now it's been added: and the entropy added into the overall hash (even when canvas is blocked), along with entropy as to whether or not the prefs are at default

for all 12 values (although to be honest width doesn't have a pref)
- I always calculate the hash: even when it's an empty array (e.g not supported or canvas is blocked) or an array of blank values (e.g. blocked)
- I can now display whether it is "not supported" vs "blocked", and this is appended to the hash for that method
- because I know the FF version, for each method (excl width), I can also display when the pref is not at default: i.e supported vs not supported depending on the version, this too is appended to the hash for that method
- and when canvas is blocked, I still output supported vs non-supported (including non-default notation), and this too is appended to the hash

Here's FF75 with CB blocking **some** textMetrics, and I also enabled emHeight and fontBoundingBox in prefs from default false to true

![pic1](https://user-images.githubusercontent.com/16656956/79343709-4add8780-7f1e-11ea-945b-32a02dc7751a.png)

and here's the combined hash
```
combined TM hash 
da39a3ee5e6b4b0d3255bfef95601890afd80709_blocked
7bc077692d4196982921fa6c4fcc08d424a03cd3_blocked standard
768e94add9710debdadd8e72ace130fc0813affa
4ac004e5e23bd3bc902af62717d6637447780b5d
7bc077692d4196982921fa6c4fcc08d424a03cd3_blocked standard
da39a3ee5e6b4b0d3255bfef95601890afd80709_not supported standard
7bc077692d4196982921fa6c4fcc08d424a03cd3_blocked unusual
7bc077692d4196982921fa6c4fcc08d424a03cd3_blocked unusual
f9cfdb4cf7e708435e79a9a0040be93377cbd573_not blocked unusual
7bc077692d4196982921fa6c4fcc08d424a03cd3_blocked unusual
da39a3ee5e6b4b0d3255bfef95601890afd80709_not supported standard
da39a3ee5e6b4b0d3255bfef95601890afd80709_not supported standard
```

---

And here's when canvas is blocked

![pic2](https://user-images.githubusercontent.com/16656956/79343695-444f1000-7f1e-11ea-96da-4f47268cb8ec.png)


```
combined TM hash 
da39a3ee5e6b4b0d3255bfef95601890afd80709_no canvas standard
da39a3ee5e6b4b0d3255bfef95601890afd80709_no canvas standard
da39a3ee5e6b4b0d3255bfef95601890afd80709_no canvas standard
da39a3ee5e6b4b0d3255bfef95601890afd80709_no canvas standard
da39a3ee5e6b4b0d3255bfef95601890afd80709_no canvas standard
da39a3ee5e6b4b0d3255bfef95601890afd80709_no canvas standard
da39a3ee5e6b4b0d3255bfef95601890afd80709_no canvas unusual
da39a3ee5e6b4b0d3255bfef95601890afd80709_no canvas unusual
da39a3ee5e6b4b0d3255bfef95601890afd80709_no canvas unusual
da39a3ee5e6b4b0d3255bfef95601890afd80709_no canvas unusual
da39a3ee5e6b4b0d3255bfef95601890afd80709_no canvas standard
da39a3ee5e6b4b0d3255bfef95601890afd80709_no canvas standard
```

if you haven't guessed already, `da39a3ee5e6b4b0d3255bfef95601890afd80709` is the sha1 of an empty array, and `7bc077692d4196982921fa6c4fcc08d424a03cd3` is the sha1 of an array of 256 (43 chars x 6 styles) blank values (so you end up with a string of commas, commas being the default in `.join()` )

however, I've just noticed that my no canvas hashes need to actually have the supported/not-supported part added: I'll add that

**Comment by Thorin-Oakenpants** [comment]
https://thorin-oakenpants.github.io/testing/textmetrics.html

This is my windows desktop. Left is no spoofing, right is CB. The char list used is the unicode glyphs one in out tests with the alphabet lower, upper, numbers, and then some chars like `~`, `!`, `@` etc. I put the unicode chars first so any troublesome ones we can refer to the index number

![tm](https://user-images.githubusercontent.com/16656956/79492325-59f03280-800f-11ea-96d1-b80e79947c08.png)

On android, I get `6,1,1,0,4` - holy cow, it includes `T` and `Y`
On desktop, I get
 - `5,0,0,0,1` Times New Roman
 - `5,0,0,0,17` Arial - those 17 are all from the unicode glyphs list
 - `3,0,0,0,3` Batang
 - '3,0,0,0,17` Gautami - those 17 are all from the unicode glyphs list

I might build in some basic short hash so it's easy to see if the actual chars changed, but I think it's safe to say that the unicode list just causes false positives

I'll expand this to include the other textMetrics

**Comment by Thorin-Oakenpants** [comment]
Fedora 32bit : Deja Vu Serif (default)
![tm_fedora32-dejavuserif](https://user-images.githubusercontent.com/16656956/79534509-5211ac00-806a-11ea-9584-2b458e906646.png)

That's a lot of integers

**Comment by Thorin-Oakenpants** [comment]
interesting: here's a mac (using the unicode glyphs list)
![mac](https://user-images.githubusercontent.com/16656956/83828977-66b90a80-a6d1-11ea-8f4d-588454031590.png)

**Comment by kkapsner** [comment]
As soon as I find a good way to not change the number of decimals while faking I will change CB in that way.

**Comment by Thorin-Oakenpants** [comment]
actually...
- if decimals is not 0 or 7 or 13 or 14 = lies
- if 13 or 14 decimals, if no instances of `33` or `66` = very likely lies

If lies then randomized, else if very likely lies is greater than 5 out of 43 tests then randomized

Seems like a solid algorithm to me
