### ISSUE TITLE
webGL

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/TorZillaPrint#56]
snip

**Comment by Thorin-Oakenpants** [comment]
here's my lame attempt so far

```js
function get_webgl_basics() {
	let t0 = performance.now()
	function getWebglContext(canvas){
		try { 
			return canvas.getContext("webgl") || canvas.getContext("experimental-webgl")
		} catch(e) {}
		return null;
	};
	let canvas = document.createElement('canvas');
	let gl = getWebglContext(canvas);
	if (gl) {
		let ext = gl.getExtension('WEBGL_debug_renderer_info');
		if(ext) {
			console.log ( "WebGL Version: " + gl.getParameter(gl.VERSION) )
			console.log ( "Shading Language Version: " + gl.getParameter(gl.SHADING_LANGUAGE_VERSION) )
			console.log ( "WebGL Vendor: " + gl.getParameter(gl.VENDOR) )
			console.log ( "WebGL Renderer: " + gl.getParameter(gl.RENDERER) )
			console.log ( "WebGL Unmasked Vendor: " + gl.getParameter(ext.UNMASKED_VENDOR_WEBGL) )
			console.log ( "WebGL Unmasked Renderer: " + gl.getParameter(ext.UNMASKED_RENDERER_WEBGL) )
		}
	} else {
		console.log("you suck")
	}
	// perf
	if (logPerf) {debug_log("webgl basics",t0)}
}
```

![lame](https://user-images.githubusercontent.com/16656956/77124610-40bd8b80-6a3b-11ea-91f6-f8585fe9eabc.png)

**Comment by kkapsner** [comment]
The CB test page for webGL shows if CB supports webGL - not the browser. So the "supported" code is not useful for TZP.

The readPixels is already an image hash with webGL - so this can be reused/moved.

webGL and webGL2 should get two different hashes and I also think that a details section is not necessary.

**Comment by Thorin-Oakenpants** [comment]
>  shows if CB supports webGL - not the browser

Ahh. OK .. *now* it makes sense :)

> The readPixels is already an image hash with webGL - so this can be reused/moved

Cool. At this stage I quite like the webgl image under canvas. There is another angle (pun intended) with webgl and images, that is performant heavy and multiple images and maybe this could be added down the track as a manual run

> details

The only reason I output details is for analysis. If I can keep the output small'ish, or at least store it as a variable (copy to clipboard button, output to console). I just don't know how much of all that stuff is variable between FPrints. I mean if's just what properties are supported then it's likely not a factor, but if the values of those properties change, then they are

**Comment by kkapsner** [comment]
I think the values are mostly dependent on the actual GPU.

**Comment by Thorin-Oakenpants** [comment]
@kkapsner (I don't know if I should keep @ ing you, since you're a watcher)

I moved webgl next to canvas and (moved domrect above those) - that's all live. Locally I have removed the readPixels test and webgl getContext support results from the canvas.js. I have a webgl.js where I have added those in.

here's a pic
![webgl](https://user-images.githubusercontent.com/16656956/82442672-a0620280-9a8f-11ea-8791-aae5f311430b.png)

Ignore the fact that the output is on a line that says `[webgl] - as compared to `[webgl2]`. My question is: is the readPixel test result the same sort of test you do for the image here: https://canvasblocker.kkapsner.de/test/webGL-Test.html
 - i.e do I need the current test, if I implement the ones on your webGL test page?

PS: my parameters will be a hash of the lot, but I will also display the vendor/renderers separately, since those are covered by RFP (and I can notate them)

**Comment by Thorin-Oakenpants** [comment]
Not sure if you're aware, but I was doing some testing
 - https://ghacksuserjs.github.io/TorZillaPrint/TorZillaPrint.html#webgl
 - `fake/block-everything` and `fake/block-input` is horrendous perf: there's console errors about incorrect getContext - but there is eventually an output and it seems randomized
```
/* CB readPixels NOTES

General: block everything
	- APIs: block nothing
		- real hash
	- APIs: block readout
		- 9d685aec3519df3fad6dc21f695ee5aac942fe680d768dd198745fd31501d21b
	- APIs: block everything
		- webgl not supported
	- APIs: block input
		- webgl not supported

General: fake
	- APIs: block nothing
		- real hash
	- APIs: block readout
		- random hash
	- APIs: block everything
		- random, but CB console errors and takes a long time
	- APIs: block input
		- random, but CB console errors and takes a long time
*/
```

**Comment by Thorin-Oakenpants** [comment]
also `block-everything/block-readout`
 - `9d685aec3519df3fad6dc21f695ee5aac942fe680d768dd198745fd31501d21b`
 - that's what I get, is that a standard hash for this js script across all platforms: I mean if you can't get the readout, then that must be a blank hash? right?

**Comment by kkapsner** [comment]
> My question is: is the readPixel test result the same sort of test you do for the image here: https://canvasblocker.kkapsner.de/test/webGL-Test.html
> 
>     * i.e do I need the current test, if I implement the ones on your webGL test page?

They are similar but not the same. My page uses toBlob for the image hash and not readPixels. I did that so I can compare to the offscreen canvas test. I would not include offscreen canvas tests in TZP at the moment as it's crashes the tab for me every time I want to draw anything in the offscreen canvas.

>     * `fake/block-everything` and `fake/block-input` is horrendous perf: there's console errors about incorrect getContext - but there is eventually an output and it seems randomized

Knew that it has worse performance but not that it was that bad. I will look into that. (The getContext error is an easy fix.)

>     * I mean if you can't get the readout, then that must be a blank hash? right?

Yes, it's the hash of a blank buffer.

**Comment by Thorin-Oakenpants** [comment]
the idea
```
[re-run]       hash: `overall properties hash`
         getContext: webgl: supported, webgl2: supported
         vendor etc: blah [RFP]
       rendered etc: blah [RFP]
   welgl parameters: hash [a/b/c]
  welgl2 parameters: hash [a/b/c]

             --- render ---
               hash: `overall render hash`
         readPixels: hash [colors]
      [webgl] image: hash [size]
     [webgl2] image: hash [size]

            --- checks ---
[run]       iframe1: hash [match] (compared to overall render)
            iframe2: hash [match]
         offscreen?: hash [match]
            worker?: hash [match]
```

- the parameters is all parameters, but I want to display the vendor/renderer + unmasked since RFP covers them (including when they aren't there!)
- most likely don't need the "a/b/c" see https://amiunique.org/fp - IDK: I would think all FF users on the same version would be the same
   - a: 24 different extensions
   - b: 25 different general parameters analyzed
   - c: 36 different shaders precisions analyzed
- not sure on the colors or size, esp if it slows it down
- not sure on auto-running the checks
   - depends on the perf hit. Generally if everything's already in memory...

Something like that. I can muddle my way thru the top section

---

I do have a question though
- I added a `sha256_string` function
- I used it to make manual audio test hashes the same length (so the section is consistent)
- The perf is OK. It's about 5-to-10ms and only the last of the three tests matters because the first two get calculated as the next test is running
- I also use it for the overall hash in canvas: the perf sucks: it's like 40-to-50ms

I downloaded a 3rd party minimized js (https://github.com/brillout/forge-sha256), it's 4.5kb, and I guess yet another file for TZP to fetch. It halved the time, but it unfortunately errors with the audio hashes. It shaved 3ms off audio (so big deal), but it halved the canvas and webgl one. The difference between them is most likely because audio is manual and nothing else is running: but canvas is trying to do its thing at the same thing as webgl, fonts, and auto-audio

I'd rather not have yet another file to fetch (and I want to merge a few of the others js files together: especially all the workers ones). Here's what I have:

```js
async function sha256_str(str) {
	const buf = await crypto.subtle.digest("SHA-256", new TextEncoder("utf-8").encode(str))
	return Array.prototype.map.call(new Uint8Array(buf), x=>(('00'+x.toString(16)).slice(-2))).join('')
}
```

Is there a faster way? All these I am passing a string, but that string is generated from an array. Can I build a faster sha256_array(array). Or can I build my array on the fly as the right type?

**Comment by kkapsner** [comment]
> Knew that it has worse performance but not that it was that bad.

It's the canvas section that is slow. The input mode needs more computation.

>     * IDK: I would think all FF users on the same version would be the same

They are different for me... (FF 76.0.1) I think this is more dependent on the graphics card and its driver.

>     * not sure on the colors or size, esp if it slows it down

Size is fast. Colour is slower. And they should be correlated somehow.

> I downloaded a 3rd party minimized js

The native implementation of SHA-256 should be faster than any JS implementation. Your timing measurement is slightly flawed. You start the timing before the asynchronous calls (i.e. the hashing) it will also include all the other synchronous calls that are made after that.
Example: you have 5 tasks that all take 10ms. Task 1 has a asynchronous call at the end. So this is the timing line for task 1:
Timing for task 1 starts -> synchronous calls of task 1 run -> asynchronous calls of task 1 are registered -> synchronous calls of task 2 to 5 run -> as the synchronous calls are done the next "tick" can run and will execute the asynchronous (JS) calls of task 1 (the real computation may already be done) -> timing for task 1 ends
So the total time will include all the time for task 2 to 5. So not 10ms but ~50ms.
The "tick" in between may also take some time (in that time rendering and display is done).

So if you compare performance between implementation changes you should only run one test to get better data.


> Is there a faster way? All these I am passing a string, but that string is generated from an array. Can I build a faster sha256_array(array). Or can I build my array on the fly as the right type?

Using Uint32Array instead of Uint8Array could make it slightly faster

**Comment by Thorin-Oakenpants** [comment]
> They are different for me... (FF 76.0.1) I think this is more dependent on the graphics card and its driver.

What's different? compared to what? AFAIK, for webgl (just like canvas), the hash/color/size would be stable except when randomizing - that's the FP.  Getting the colors isn't going to add any more entropy. I mean if the colors change, the hash would be different. What's it good for is some sort of bucketing of sizes to detect randomizing settings (if you can detect the randomising)

But yeah, now that you say it: sure: some video cards might return loads more colors than some 10 year old budget laptop. And that probably increases the size. Still, it would add anything that the hash hasn't already.

Size is interesting because one size can = many hashs

Something to think about :)


----------

Ahh OK: I had something like this (they all had their own timers started right before the promise)

```
let t45 = performance.now()
Promise.all([
	sha256_str(hash.join())
]).then(function(result){
	dostuff
	perf =  new performance.now() - t45
})
```

But I see what you mean. I should pass the current time to the sha256 function and do it there? 
```
Promise.all([
	sha256_str(hash.join(), "audioA",performance.now())
]).then(function(result){
	dostuff
})

await function sha256_str(string, testname, starttime) {
	const stuff
	let result = other stuff
	perf = performance.now()-starttime
	return result
}
```

Just interested to see if I got that right for the future. But it's probably a moot point? All that would show is that all the sha256 calculation times are fairly stable (e.g. 10ms each)?

My perf output is to always be right after the final results have been output to the web page: hence why they're inside the promise's function

**Comment by kkapsner** [comment]
> What's different?

The different extensions, different general parameters analyzed and different shaders precisions analyzed. Compared to your numbers.

> What's it good for is some sort of bucketing of sizes to detect randomizing settings (if you can detect the randomising)

I agree. Should not help.

> I should pass the current time to the sha256 function and do it there?

That would have the same problem. Measuring timing with asynchronous functions is tricky. You would have to measure every synchronous part separately and then add the times. But you are not able to measure the native functions (in that case the native hashing).
It would all be a little bit messy - as you have the `rerun` buttons I would simply use the numbers they provide to compare different implementations.

> All that would show is that all the sha256 calculation times are fairly stable (e.g. 10ms each)?

I think it would show that the native implementation is much faster.

> My perf output is to always be right after the final results have been output to the web page: hence why they're inside the promise's function

I totally get the point why you did it that way. It's just not valid to compare synchronous and asynchronous functions that way.

**Comment by Thorin-Oakenpants** [comment]
> Measuring timing with asynchronous functions is tricky

That's all I needed to know. Clearly an novice apprentice is not expected to handle this.

Yup, the re-run buttons mean I can test sections and even specific functions (using the logPerf var in globals.js ) without everything trying to run at the same time. I do test that way: and just average the results. Overall, because canvas takes so long, its harder to pick up on the perf

---

> The different extensions, different general parameters analyzed and different shaders precisions analyzed. Compared to your numbers.

now I'm lost, not really :) Let me backtrack :) Yeah, `24, 25, 36` is what I got in Nightly 78. It's probably what I get in all my FF's on this machine since FF60: I might test that: any changes would be to core webgl code I guess.

- me: most likely don't need the "a/b/c" see https://amiunique.org/fp - IDK: I would think all FF users on the same version would be the same 
   - ^ that's a count of each type of parameter: not the values of them
- kk: They are different for me... (FF 76.0.1) I think this is more dependent on the graphics card and its driver.
- me: What's different? compared to what?
- kk: see above

Right. The graphics card parts a large part. But they shouldn't change between tests (unless a web ext can block/randomize what it uses). I said **per browser version** (because clearly webgl core changes are made from time to time) - I guess that should be per browser version **and device/card** then.

I was under the impression that this was a list that doubled as what is supported - but I guess it's what is supported by your graphics card? I've been looking at https://github.com/CesiumGS/webglreport for a long time, but clearly until I code things up for easy comparisions - I'm just making assumptions

Displaying the count doesn't really matter, the parameters hash already takes care of that.

**Comment by Thorin-Oakenpants** [comment]
Here's some test results
 - https://amiunique.org/fp
 - a single point in time: same PC/OS, same graphics card + drivers
 - all FF's practically vanilla test profiles

```
ESR60, FF60-66
   - 22 ext, 25 general, 36 shaders
FF67, ESR68, FF68-  78
   - 23 ext, 25 general, 36 shaders
ESR68, FF68-76, Beta77, Dev77, Nightly78
   - 24 ext, 25 general, 36 shaders
```

Just the number of extensions increased, which I assume is Firefox adding more support, updating the version of webgl

**Comment by kkapsner** [comment]
> I guess that should be per browser version **and device/card** then.

Yes - I think so as well.

> the parameters hash already takes care of that.

Yes - if the count change the hash will change as well.

**Comment by Thorin-Oakenpants** [comment]
I still think outputting the numbers is interesting: so I can see what affect things like VMs or various pref tweaks have (IDK, but disabling hardware acceleration springs to mind? and web render? and various webgl prefs maybe). Not for entropy (which is in the overall hash) but purely from a test results perspective and analysis. It shouldn't add any perf issues
