### ISSUE TITLE
domrect: don't use an iframe

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/TorZillaPrint#61]
calling @kkapsner 

So I changed **where** I measure domrect. I no longer use an iframe. Instead I use a fixed overlay which I unhide, measure, and then hide again. You never see it. Fixed so it's always in the same spot regardless of where on the page you are. And now domrect's perf is around 6ms :) Instead of waiting all that time for the iframe to load - and I don't have to worry about iframes being blocked, or removing the iframe (for reruns), etc.

Seriously .. it's blazingly fast :) You could do the same

pic is HTTPS, not local
![speedy](https://user-images.githubusercontent.com/16656956/82153446-f730c780-9856-11ea-8a54-c9676630bf1e.png)

---
The overlay test matched the iframe in text, but the three widgets **had different figures**. Wrapping the iframe contents in another div fixes that. If you modify your iframe source to match, then we can have the same hashes (which we used to, and is always a good check)

And if we ever needed to check if an iframe matched (to detect spoofing or something), then, well you would want them to be the same, obviously.

However, if you don't want iframes and want to go super speedy like me, then just match my css :)

---

view-source:https://canvasblocker.kkapsner.de/test/domRectIFrame.html

change that ^^ to the below and you should get the same figure that TZP gives
- new bits are the #overlay style and everything in the body being wrapped in the new div

```html
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<link href="testIcon.svg" type="image/png" rel="icon">
<link href="testIcon.svg" type="image/png" rel="shortcut icon">
<style>
#overlay {
  position: fixed;
  top: 10;
  left: 10;
}
#inside{
	white-space: nowrap;

	color:#5B5B5B;
	position: absolute;
	padding: 1.3333px;
	left: 10.5555px;
	top: 28.4444px;
	font-size: 24.5555px;

	-ms-transform: scale(1.31123) matrix3d(0.373513, -0.0440105, 0, -0.000202461, -0.0851682, 0.616234, 0, -0.00123197, 2.17, 0.21, 1, 0.02, 13.81, 2.11, 0, 0.98);
	-moz-transform: scale(1.31123) matrix3d(0.373513, -0.0440105, 0, -0.000202461, -0.0851682, 0.616234, 0, -0.00123197, 2.17, 0.21, 1, 0.02, 13.81, 2.11, 0, 0.98);
	-webkit-transform: scale(1.31123) matrix3d(0.373513, -0.0440105, 0, -0.000202461, -0.0851682, 0.616234, 0, -0.00123197, 2.17, 0.21, 1, 0.02, 13.81, 2.11, 0, 0.98);
	transform: scale(1.31123) matrix3d(0.373513, -0.0440105, 0, -0.000202461, -0.0851682, 0.616234, 0, -0.00123197, 2.17, 0.21, 1, 0.02, 13.81, 2.11, 0, 0.98);

	-ms-transform-origin: 0.1111px 0.2222px 0.3333px;
	-moz-transform-origin: 0.1111px 0.2222px 0.3333px;
	-webkit-transform-origin: 0.1111px 0.2222px 0.3333px;
	transform-origin: 0.1111px 0.2222px 0.3333px;
}

#select {
	transform: rotate(1.23deg);
}

#progress {
	transform: scale(3.14);
	position: absolute;
	top: 300px;
	left: 200px;
}

#button {
	padding: 4.937px;
	margin: 9.876px;
}

.testRect {
	outline: 2px dotted lightblue;
}

</style>
</head>
<body>

<div id="overlay"> // new overlay wrapping everything

<div id="inside">
<h1 data-name="rect 0" class="testRect">https://browserleaks.com<i>/rects</i></h1>
<span data-name="rect 1" class="testRect"><strong>Element.getClientRects (̿▀̿&thinsp;̿Ĺ̯̿̿▀̿ ̿)̄ </strong></span><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<span data-name="rect 2" class="testRect">F i n g e r p r i n t i n g ?</span>
</div>
<select id="select" data-name="select" class="testRect">
	<option>&minus;&#1726;-</option>
</select>
<progress id="progress" data-name="progress bar" class="testRect">test</progress>
<button id="button" data-name="empty button" class="testRect"></button>

</div> // new div being closed

</body>
</html>

```

To use it in the main document, just add `display: none;` to `#overlay` and in code, drop all the iframe stuff and just do this
```js
	function getElements(){
		return Array.from(document.querySelectorAll(".testRect"))
	} // change to document

	// unhide
	document.getElementById("overlay").style.display = "block"
	// run all your tests
	createTest(blah blah, function(element){return element.getClientRects()[0]})
	// hide divrect
	document.getElementById("overlay").style.display = "none"
```

**Comment by Thorin-Oakenpants** [comment]
oh, and make sure you don't have any styling conflicts: I had to change my css for TZP to use `.btn` instead of `button` and apply classes instead <button class="btn">

**Comment by kkapsner** [comment]
You do not even need to toggle the display. A `opacity: 0` and `z-index: -1` are sufficient.

I think I will have both tests. The loading of the iframe is no performance issue for me. But I would prefer if the values would not change from my previous version.

For that the #overlay must have a slightly different CSS: ```#overlay {
  position: fixed;
  top: 0px;
  left: 0px;
  padding: 8px;
}```

**Comment by kkapsner** [comment]
I updated my test page.

**Comment by Thorin-Oakenpants** [comment]
Ahhh .. `8px` .. that was it. Done to match: I didn't really want to differ from your hash, as it's a good check. Now we're both back in sync :)

> `opacity: 0` and `z-index: -1` are sufficient

Sweet: Also done

**Comment by kkapsner** [comment]
Great.
