### ISSUE TITLE
dates

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/TorZillaPrint#63]
@kkapsner and @sereneblue FYI and WTF is up with a date object in an array from a worker: read on

Everything (except geo) that is done in the language/date-time-format section is also checked in a worker: exact same code/function
- The document function produces an array of 38 items (0 to 37). I can `.join()` this and hash it
- The worker does the same, and I can `.join()` is and pass it back in a message to the document

When the document gets the worker's array, it can compare the two arrays, item by item
- item 0 is `navigator.languages` and to compare I have to `toString()` them
- everything else is straight up `array1[index] !== array2[index]`

```js
// res = document array
// e.data = array from worker

	if (i == 0) {
		// languages object
		if (res[i].toString() !== e.data[i].toString()) {
			// does not match: do stuff
		}
	} else if (i == 8) {
		// date object
		// if I use toString to compare: TypeError can't access property "date"
		// using toString = stupid anyway, that's item 9

		// without toString they are always different, even if they are the same

	} else {
		if (res[i] !== e.data[i]) {
			// does not match: do stuff
		}
	}
```

However, this fails for index item 8, which is a date object
basic code
```js
let d = new Date("January 30, 2019 13:00:00")
if (item == 8) {return d }
```
The item pushed to both arrays is `d` - a date

I do not have any problems with the document array, I can get it's hash and join it and debug it etc. But when I try to do anything with the array passed back from the worker, I get the same error `TypeError can't access property "date"` - even if I trap the error, it aborts the rest of the function

Any ideas what is going on? Currently the code is bypassing comparing item 8, and I'm not comparing overall hashes to denote they are different and to see details

---

Here's a pic: I have RFP on so results are in UTC-0 and I'm en-US. I am spoofing as Traditional Chinese and timezone Shanghai

So
- `date/time` is ignored (item 8) but if I could compare it, it would be different and the same as the one below it
- `[dayPeriod] **Intl.DateTimeFormat` has a bug
   - there are two instances of `at night`
   - when spoofing as Paris timezone, I had two lots of `in the afternoon`
- some times don't seem to get spoofed (AFAICT)
   - `toGMTString` and `toUTCString`
- numbering and calendar don't seem to be spoofed
- the language parts don't get spoofed (e.g. Wednesday vs Mercredi (fr))
   - e.g. `Intl.RelativeTimeFormat`
   - I'm guessing that's by design for now
- formatting doesn't get spoofed
   - I'm guessing that's by design for now

Anyway, you can use this now to test Chameleon time stuff

![time](https://user-images.githubusercontent.com/16656956/84732084-423f1700-af8a-11ea-98a4-40e73469713e.png)

**Comment by Thorin-Oakenpants** [comment]
dayPeriod seems a bit more out of whack that I thought

![dayPeriod](https://user-images.githubusercontent.com/16656956/84813834-12325b00-b000-11ea-941a-381994f44b08.png)

```js
	// dayPeriod: 1569103: nightly-only FF78+
	function get_day_period(date) {
		return new Intl.DateTimeFormat(undefined, {dayPeriod: "long"}).format(date)
	}
	let tmp35 = "",
		dayA = get_day_period(new Date("2019-01-30T08:00:00")),
		dayB = get_day_period(new Date("2019-01-30T12:00:00"))
	if (dayA == dayB) {
		tmp35 = zNS
	} else {
		// in the morning, noon, in the afternoon, in the evening, at night
		tmp35 = dayA + ", " + dayB
			+ ", " + get_day_period(new Date("2019-01-30T15:00:00"))
			+ ", " + get_day_period(new Date("2019-01-30T18:00:00"))
			+ ", " + get_day_period(new Date("2019-01-30T22:00:00"))
		}
		return tmp35
```

**Comment by Thorin-Oakenpants** [comment]
So issue 1: comparing: I'm guessing this will an easy fix (need to google harder)

```js
	} else if (i == 8) {
		// date object
		// if I use toString to compare: TypeError can't access property "date"
		// using toString = stupid anyway, that's item 9

		// if I use the else fallback below, it's always different, even when it shouldn't be
		console.debug("doc", res[i])
		console.debug("wrk", e.data[i])
		try {
			if (res[i] == e.data[i]) {console.debug("match")} else {console.debug("no-match")}
		} catch(k) {
			console.debug("item 8 error", k.name, k.message)
		}
	}
```

![debug](https://user-images.githubusercontent.com/16656956/84815339-676f6c00-b002-11ea-9f4e-adecf5e7dea2.png)

issue 2 is why doing this crashes the script
```js
  // item 8 (date object) causes an error
  let wHash2 = sha1(e.data.slice(8,38).join("-"))
```

**Comment by kkapsner** [comment]
As far as I read the documentation (https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm) date objects should work.
Have you tried the `.getTime()` method?

Event if you compare two date objects from the document they always be different. If you want to know if the two objects represent the same time you have to compare `.getTime()`.

**Comment by Thorin-Oakenpants** [comment]
Cool, getTime is all I needed - but NFI why the display shows the spoofed time, but the array used to write the displayed values has the RFP (or real) time

![getTime](https://user-images.githubusercontent.com/16656956/84818156-90453080-b005-11ea-837e-5b5cdf540cd6.png)

**Comment by Thorin-Oakenpants** [comment]
this is nuts

main document
```js
	// output
	for (let i=0; i < 38; i++) {
		let result = get_item(i)
		if (result == undefined) {result = zB4}
		if (result == "undefined") {result = zB5}
		if (i == 8) {console.debug("doc: item 8 array value", result)}
		res.push(result)
		document.getElementById("ldt"+i).innerHTML = result
	}
```

![nutbar-crazypants](https://user-images.githubusercontent.com/16656956/84819542-b8359380-b007-11ea-86c0-ccca996447b1.png)

WTF is going on here? Right after I get the result I add it to the array and display it: why are they different?

This is using Chameleon? Have I found a loophole to bypass date objects spoofing?

**Comment by Thorin-Oakenpants** [comment]
This is doing my head in, maybe it's a limitation of Chameleon, or it's web ext APIs

This is all in doc, so ignore the service worker.

When I check the `result` variable just before pushing to the array, it is different or "leaking" - that's the first debug line

The hash is `res.slice(8,38)` and shows the first value (item 8) is the same value being displayed as used in the overall hash, which is the spoofed one - this is the second debug line

But when I check `res[8]` later on, it's not the same: it's "leaking" - this is the third debug line

![coffee-needed](https://user-images.githubusercontent.com/16656956/84820717-950be380-b009-11ea-85dc-da1f910f2247.png)

**Comment by Thorin-Oakenpants** [comment]
just on `getTime()` - this is not a perfect way to compare

> getTime() always uses UTC for time representation. For example, a client browser in one timezone, getTime() will be the same as a client browser in any other timezone

RFP on = `1548853200000` but when off, my timezone is hours different, and I get a different number.

But if two results have the same timezone (e.g. `+1`) but different names (e.g. `Berlin` vs `Brussels`) then the difference won't be picked up - right?

**Comment by Thorin-Oakenpants** [comment]
```js
console.debug("doc: item 8  array", ""+res[i], "\n", res[i])
console.debug("wrk: item 8  array", ""+e.data[i], "\n", e.data[i])
```

```
// doc
doc: item 8  array Wed Jan 30 2019 21:00:00 GMT+0800 (China Standard Time) 
 Date Wed Jan 30 2019 13:00:00 GMT+0000 (Coordinated Universal Time)

// wrk
compare 8 TypeError can't access property "date", this[window.Dcmd1v] is undefined
```

In order to compare, I essentially have to turn them into strings. But as you can see, any attempt to read e.data date object as a string causes an error (even trying to hash the array causes an error), this error can be trapped, but still causes the code to abort

And I don't understand why res[8] has two values

**Comment by Thorin-Oakenpants** [comment]
BTW: the error only happens when spoofing: so I'm 99% convinced this is caused by Chameleon

**Comment by Thorin-Oakenpants** [comment]
Maybe item 8 is semi-redundant, since it's basically the same as toString: I mean it's a string when displayed, and I need it as a string to compare. I could string the result in the worker but not the document - but I'm not sure if that would defeat the purpose of the test. It would allow me to compare and output the second line, and hash the worker array etc to notify of differences.

I could also add it as a Date object as a final item in the worker to do things with after everything else has finished

I **think** I can leverage the document array value (which isn't spoofed) but need to think about it.

**Comment by Thorin-Oakenpants** [comment]
I'll just keep to talking to myself 👍 

So I added getTime to timezone, and it seems Chameleon doesn't spoof that
![getTime](https://user-images.githubusercontent.com/16656956/84848775-509d3980-b043-11ea-91cc-46fc3fc55719.png)

```js
	let d = new Date("January 30, 2019 13:00:00"),
		d2 = new Date("July 30, 2018 13:00:00")

	} else if (item == 6) {
		return d.getTimezoneOffset() +' | '+ d2.getTimezoneOffset()
			+ " | "+ ((d.getTime() - 1548853200000)/60000)
			+ " | "+ ((d2.getTime() - 1532955600000)/60000)
	}
```

The two values are those of UTC 0 six months apart using my set date-times

**Comment by Thorin-Oakenpants** [comment]
OK, I've sorted it out: date objects don't have any timezone-name info eg `Australian Western Standard Time` vs `China Standard Time`, they're simply date-times, and getTime won't cut it. So the only way to compare the items is to use strings - end of story.

- the doc still outputs the date object
- the worker uses ` "" + date ` (not `toString` but I suspect it has the same effect?) - since I only use it to compare (and it needs to be a string to do so) and outputting it if different is a string anyway, so IDK. Ended up confusing the F out of myself.

As for the console displaying the leaked value, I'm pretty sure I can't leverage that for anything because as soon as it's used in JS, it gets spoofed? I thought it could be used for getTime, but Chameleon doesn't spoof that, so i can't check

🎉 
![tada](https://user-images.githubusercontent.com/16656956/84851391-a7a60d00-b049-11ea-8a66-f95ce6bbf406.png)

**Comment by kkapsner** [comment]
> So I added getTime to timezone, and it seems Chameleon doesn't spoof that

That's correct. It should not be changed. `.getTime` returns the number of milliseconds since 1.1.1970 00:00:00 GMT

> OK, I've sorted it out: date objects don't have any timezone-name info eg `Australian Western Standard Time` vs `China Standard Time`, they're simply date-times, and getTime won't cut it. So the only way to compare the items is to use strings - end of story.

Kind of. In your test you specify the time to check: "January 30, 2019 13:00:00" - that is meant to be in the your timezone and not UTC. So by simply looking at the hour of your output (`.getHours` or the string) you see that it's not 13 but 21 and thus the output if faked.

**Comment by Thorin-Oakenpants** [comment]
> Kind of...

I don't quite follow. Is the test faulty?

**Comment by kkapsner** [comment]
No the test is fine. But you can detect spoofing without looking at the worker data.

**Comment by Thorin-Oakenpants** [comment]
Yup. The worker is just autorun in my nightly (no workers blocked in that puppy) and mirrors the same 38 items. For now it's detecting the spoof (on the main doc: as in the pics) because @sereneblue hasn't covered it: and if he does, **then** the worker will pick it up, until/if extensions get access to workers

PS: Seems CB has a randomness signature (well two of them) .. it's all happening in #65 .. get your butt in there :)

**Comment by kkapsner** [comment]
> get your butt in there

I know - but I need some quiet minutes (maybe hours...) to digest all of that.
