### ISSUE TITLE
domrect randomizing detection [done], canvas randomizing characteristics

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/TorZillaPrint#65]
@kkapsner Just throwing this out there before I try it

snip

**Comment by Thorin-Oakenpants** [comment]
interesting: this is live btw: check your console
- the `dr` number = the four methods
- the four properties measures are bottom/left/right/top
- the number `1` or `2` is the measuring run: 1 is at 0px, 2 is at `0.25`


Here I have CB randomizing domrect
 - the difference between the pairs of measurments is not 0.25

```
dr1:bottom:1:31.349235826134503
dr1:bottom:2:31.599691154051033
dr1:left:1:7.779085714440035
dr1:left:2:8.037432965042324
dr1:right:1:58.19132470898594
dr1:right:2:58.44967195958823
dr1:top:1:10.283017923560617
dr1:top:2:10.533473251477147
dr2:bottom:1:31.349235826134503
dr2:bottom:2:31.599691154051033
dr2:left:1:7.779085714440035
dr2:left:2:8.037432965042324
dr2:right:1:58.19132470898594
dr2:right:2:58.44967195958823
dr2:top:1:10.283017923560617
dr2:top:2:10.533473251477147
dr3:bottom:1:31.349235826134503
dr3:bottom:2:31.599691154051033
dr3:left:1:7.779085714440035
dr3:left:2:8.037432965042324
dr3:right:1:58.19132470898594
dr3:right:2:58.44967195958823
dr3:top:1:10.283017923560617
dr3:top:2:10.533473251477147
dr4:bottom:1:31.349235826134503
dr4:bottom:2:31.599691154051033
dr4:left:1:7.779085714440035
dr4:left:2:8.037432965042324
dr4:right:1:58.19132470898594
dr4:right:2:58.44967195958823
dr4:top:1:10.283017923560617
dr4:top:2:10.533473251477147
```

for comparison, here's without randomizing
```
dr1:bottom:1:31.350006103515625
dr1:bottom:2:31.600006103515625
dr1:left:1:7.7833404541015625
dr1:left:2:8.033340454101562
dr1:right:1:58.19999694824219
dr1:right:2:58.44999694824219
dr1:top:1:10.283340454101562
dr1:top:2:10.533340454101562
dr2:bottom:1:31.350006103515625
dr2:bottom:2:31.600006103515625
dr2:left:1:7.7833404541015625
dr2:left:2:8.033340454101562
dr2:right:1:58.19999694824219
dr2:right:2:58.44999694824219
dr2:top:1:10.283340454101562
dr2:top:2:10.533340454101562
dr3:bottom:1:31.350006103515625
dr3:bottom:2:31.600006103515625
dr3:left:1:7.7833404541015625
dr3:left:2:8.033340454101562
dr3:right:1:58.19999694824219
dr3:right:2:58.44999694824219
dr3:top:1:10.283340454101562
dr3:top:2:10.533340454101562
dr4:bottom:1:31.350006103515625
dr4:bottom:2:31.600006103515625
dr4:left:1:7.7833404541015625
dr4:left:2:8.033340454101562
dr4:right:1:58.19999694824219
dr4:right:2:58.44999694824219
dr4:top:1:10.283340454101562
dr4:top:2:10.533340454101562
```

**Comment by Thorin-Oakenpants** [comment]
```
dr1:left:1:7.7833404541015625
dr1:left:2:8.033340454101562
```

Interesting to note some values (non-spoofed) round, losing one decimal place: that's easy to work around. Ball is in your court @kkapsner 🏀  :)

**Comment by Thorin-Oakenpants** [comment]
![sweeeeeet](https://user-images.githubusercontent.com/16656956/85092147-9f300c80-b1d8-11ea-8718-1d1f8b71ddfb.png)

@kkapsner once again, I need help with promises (waiting for the hashes, not the measurements). I can't output the random notation until after that. Currently using a shitty [timeout](https://github.com/ghacksuserjs/TorZillaPrint/commit/1530a1e09ba1209582514684424bce8d0f163b14#diff-53c9a39a9f108365e61bfff7434693f6R91)

What I ideally need is for `run(1)` and `run(2)` (scroll up) to return something when finished?

**Comment by Thorin-Oakenpants** [comment]
https://canvasblocker.kkapsner.de/test/detectionTest.html

What do `known`, `changed` and `recreated` domrect tests do exactly?

**Comment by Thorin-Oakenpants** [comment]
@abrahamjuliot  

Unlike other test sites (no idea where they came up with their list, but they do jack shit in FF), I'm using my own math functions for Firefox (I already know if the browser is FF, so I don't need all the crap the other sites tests for) - namely the ECMA 1st edition set of cos functions (which I found in an obscure Japanese research paper) create some entropy. The ECMA 6th edition has almost no entropy (except it helps overall by being different to chrome/opera etc and it changed in 68, and sometimes it changes with 32bit builds or OS architecture)

Overall, so far: I have approx 20 unique FF math hashes: but it's really only half that: 10 pre FF68, 10 post FF68

Anyway, I digress. Do you (or do you plan to) spoof math functions? Do you (or can you) spoof only when certain values are used? The reason I ask, is because if you do, I think I can detect it. But... if you're not going to do it, then I won't bother (for now)

**Comment by abrahamjuliot** [comment]
No, I think Math object is sacred and should be left alone, but I have done some testing in that area. It might be possible by using proxy on the Math object to detect polyfills.

**Comment by Thorin-Oakenpants** [comment]
It's simpler than that: it's like me asking the code if 1 + 2 = 3 and it replies with 2.9874645641. i.e if you're randomizing the mathematical proof will fail

I prefer to use straight up math to expose something:
- here with domrect: the diff after shifting everything 0.25px !== 0.25
- in textMetrics width: the char twice !== 2x the char

**Comment by abrahamjuliot** [comment]
Very true. An alternative approach to fraction randomization is to count the decimals of the property. If it exceeds 10 (for example) add noise to the 8th and 9th decimal place. This wouldn't work for Math. I don't see anyway practical way detect a Math polyfill operation.

**Comment by Thorin-Oakenpants** [comment]
> Side note: I tested this domrect randomization detection in Chrome and Tor. Not sure why, but Chrome is flagged random without randomization.

I am so often putting stuff behind my global var `isFF`, because I only care that this works in FF. That said, Here's a debug. Chrome doesn't like the `left`/`right` (5 and 6) properties.

```js
const properties = ["x","y","width","height","top","left","right","bottom"]
```

dr15 (= dr method 1, property 5(e.g.left), difference, run2 value, run1 value
```
dr15 0.2499995231628418 8.051027297973633 7.801027774810791
dr16 0.2499995231628418 51.4489688873291 51.19896936416626
dr25 0.2499995231628418 8.051027297973633 7.801027774810791
dr26 0.2499995231628418 51.4489688873291 51.19896936416626
dr35 0.2499995231628418 8.051027297973633 7.801027774810791
dr36 0.2499995231628418 51.4489688873291 51.19896936416626
dr45 0.2499995231628418 8.051027297973633 7.801027774810791
dr46 0.2499995231628418 51.4489688873291 51.19896936416626
```

**Comment by Thorin-Oakenpants** [comment]
> I don't see any practical way to detect or spoof a Math polyfill operation

I don't follow. Let's say you spoof `Math.sqrt()` ... I'll just use Pythagoras to prove you're full of shit :)

**Comment by Thorin-Oakenpants** [comment]
I updated the code, so the **random notation** is only output on FF, and I output to console.log an analysis of the differences if they are not 0.25

here's chrome (no spoofing)
![chrome](https://user-images.githubusercontent.com/16656956/85183941-48c8d980-b27d-11ea-873e-1f90892de9ba.png)

here's FF (spoofing) - just the first part (each dr1, dr2, dr3 etc is the same)
![ff](https://user-images.githubusercontent.com/16656956/85183939-45cde900-b27d-11ea-854e-0c9e370af852.png)

Not interested really in why chrome doesn't quite like left/right. And then what happens in Safari etc. I could possibly monitor how close to 0.25 it is (e.g. chromes results are all the same, but CB's are all different), but it's just not worth my time :)

**Comment by abrahamjuliot** [comment]
> ...Let's say you spoof `Math.sqrt()` ... I'll just use Pythagoras to prove you're full of shit :)

That's true too. Spoofing native math methods can be detected with math. But, we can detect excessive native math methods reads and self warn. Pollyfills go under the radar.

> I updated the code, so the random notation is only output on FF, and I output to console.log an analysis of the differences if they are not 0.25

Awesome work!

**Comment by Thorin-Oakenpants** [comment]
canvas: it's a work in progress
- https://thorin-oakenpants.github.io/testing/canvas.html
- the big pic is so you can see WTF is going on
- the tiny 10x10 (100 pixels) is what is being tested
- the colors are random on each test
- I think I got it covered (rgb and a), I hope I did the alpha right
- if hashes are the same = no manipulation

I said detecting "stealth randomizing" earlier - but that's not entirely correct. It's detecting "manipulation" (and by extension, pun intended, why would you do that if you're not anti-FPing?)

So the idea is to check the various methods for being tampered with if they're not random on multiple passes (and incorporated into the overall hash in lieu of the hash)

I could even randomize the size of the canvas. And I don't think there is any way you can stop this, as it's a pixel by pixel test - but I'm not an expert on canvas here

Class, discuss!!

**Comment by Thorin-Oakenpants** [comment]
I updated the [canvas test](https://thorin-oakenpants.github.io/testing/canvas.html)
- RFP changes 98-100 of each r,g,b,a (out of 100)
- CB default changes under half for r,g,b and doesn't touch a

I plan to add more analysis to see if I can get stable (bucketized) FPing of canvas tampering.
- see if there's any pattern to which cells get changed
- percentage of cells changed
- max diffs +/- per channel
   - I can see at a quick glance that CB nudges the values by only 1 or 2, but RFP is like a mad man
- when a cell changes does it change all of rgba or just rgb, or only one or two of rgb

And I'm not sure what settings CB does to these metrics, but I'll sure have fun

**Comment by abrahamjuliot** [comment]
bookmarked it.

**Comment by Thorin-Oakenpants** [comment]
nothing in that repo is permanent - I generally only keep things there to test before I add them to TZP. But some stuff I might keep, like my [versions](https://thorin-oakenpants.github.io/testing/versions.html)

Maybe I should move all that stuff into a `test` folder here when they're polished?

**Comment by Thorin-Oakenpants** [comment]
heh, I went for 10 times the size .. the perf sucks
![well-that-sucks](https://user-images.githubusercontent.com/16656956/85224803-53d65380-b3bc-11ea-8833-ba1253fd7d94.png)

**Comment by Thorin-Oakenpants** [comment]
So, the top is RFP random, and the bottom is CB (defaults)

RFP
- randomizes every r,g,b and a value, and thus every cell. If it says 97 or 98 or 99 that's coincidence. - It also uses the full range possible, i.e you can see it changes the four channel values by 1 to whatever (255?), the highest absolute difference will depend on the random values generated in the test image
- it pretty much adds or subtracts 50/50
- alpha test values are always 255, so they can only go down

CB
- randomizes r or g or b (never a)
- not all cells are randomized
- I haven't added a check for this yet, but I'm willing to bet that a cell **NEVER** gets r+g+b changed <-- that could be a tell tale?
- the range is only ever +1 or -1
- split in +/- is about 50/50

![Hmmm](https://user-images.githubusercontent.com/16656956/85276154-e3d5d500-b470-11ea-87ec-ce1fd4329583.png)

**Comment by Thorin-Oakenpants** [comment]
RFP = top, CB below

![alrighty](https://user-images.githubusercontent.com/16656956/85338628-2d0a4100-b4d2-11ea-9847-ee06bd8bd442.png)

So I'm thinking of outputting a canvas manipulation FP, but I'm not sure how stable would be, and I can see @kkapsner adding countermeasures :)
- full or partial: true/false
   - for RFP to luck out and only change 99 cells out of the 100, it would have to hit 1/256 four times (I thinks that's 1 in 4.3 billion): luckily RFP seems to never give 255 for an alpha (but I need to check that)
   - for an extension, depending on the number of channels it changes, that could be a 1 in 256 shot but...
- channels changed: string: e.g. "rgb"
- combos altered: bucketized
   - e.g. if RFP lucks out on randomizing some channel values, then it can end up as 3 or even 4, [see pic below] so I need some way to counter this: I think I know how: if  r g b and a are all over 95% changed and cells changed = all, then it was meant to be the lot? Or I could run a second pass or third pass?
- variance (diff spread: i.e how random is it): bucketized

So for example
 - RFPs FP would be e.g. `true-rgba-one->150`
 - CB's FP would be e.g. `false-rgb-max-<3`

rfp: when it doesn't changing every single r + g + b + a value
![rfp](https://user-images.githubusercontent.com/16656956/85340009-d05c5580-b4d4-11ea-9f94-28978a5a4ead.png)

There are still other factors I want to build in the FP: ideas welcome. And I guess I'll be testing other canvas extensions to see what they do.

I also can't see any of CB's settings that affect this FP

**Comment by Thorin-Oakenpants** [comment]
> I also can't see any of CB's settings that affect this FP

ahh, there's a "fake alpha" setting. This jumps the combos altered to 15, which is the whole range. I think I can rework the combo part of the hash to a string where each combo needs to be above a certain threshold: need to think about it more

**Comment by Thorin-Oakenpants** [comment]
some notes so I don't lose them: some basic testing of various canvas extensions. My notes are in order of testing, and it was only when I did scriptsafe last that I noticed it only ever substracted, so I guess that variable should be added to the FP

<details><summary>click me if you dare</summary><p>

🔸 canvas defender
- no options: noise settings are sticky, but you can create new noise when you want or at set intervals
- always changes all cells
- never uses alpha
- always seems to use rgb only: i.e statistically every cell gets an r + b + g change
- diffs vary per noise but always under 30 and usually/always diff for r vs g vs b
   - examples: `23,3,8`, `21,15,8`, `18,7,24`

🔸 canvas fingerprint defender
- no options
- same as RFP: changes all 4 channels, all cells
- diffs is wildy variable: sometimes it's stuff all (40's, 50's), sometimes its the lot

🔸 canvas blocker (no fingerprint)
- no options
- didn't even work

🔸 trace
- options: RGBA values: 0 = random, otherwise you can set a specific rgba value
- random
   - all cells, by 1 for g only
   - all cells, rgb, by 1 or 2
   - all cells, gb by 1 or 2
- set one or all of the rgba values as static: didn't even work

🔸 privacy possum (isn't it meant to throw garbage results?)
- after learning my test page has canvas, it fails to work
   - "cannot inject content script /js/initialize_contentscripts.js into url..."

🔸 scriptsafe
- options: blank readout, random readout, block readout
- random
   - changes all cells, statistically always uses rgba on all cells
   - diffs is the lot: always over 250
   - it only ever subtracts

</p></details>

**Comment by Thorin-Oakenpants** [comment]
@kkapsner  [said](https://github.com/ghacksuserjs/TorZillaPrint/issues/63#issuecomment-650525340)
> I know - but I need some quiet minutes (maybe hours...) to digest all of that

So I'm just playing around until I get things perfected, learning as I go. Currently building in reading back a png (from toDataURL) pixel by pixel without using canvas. But what I'm aiming for is two things
- detecting that each method is altered by added noise
- determining a `noise fingerprint`

What I think CB could do, is
- randomly decide to include the alpha channel
- randomly decide to do all or some pixels with alpha changed
- randomly decide to modify all or some of the pixels (currently CB does about 75-85% of them)
- randomly decide between rgb all, or randomizing combos of channels of r,g,b to change: this needs clarification
   - by that I mean per pixel: you can't just leave a channel out
   - there are 7 combos: `r`, `rg`, `rb, `rgb`, `g`, `gb`, `b`
   - I'm not sure on the consequences of this: but given around 20% of pixels aren't even changed currently, I don't think there's any inherent weakness in this: at worse, always weigh 2 or more channels changed as more likely
- randomly pick a uniform difference (e.g. -1 to +1, or -5 to +5) or use a random spread of what to add or subtract
  - spread: that is +1, then -5, then -2, then +3 .. etc
- randomly only subtract or add or both
- if you're only subtracting or adding but can't (e.g. 255 can't be added to): for the whole image either roll over (255+1 = 0), or use the reverse (255+1 becomes 255-1)

Any output would need to be consistent across each method and second runs etc (use cache)

This would make a noise FP likely impossible AFAICT. You probably don't even need all of those, but currently there are some tells (percentage of changed pixels, only 1 value diff both + and - )

**Comment by Thorin-Oakenpants** [comment]
maybe I'm misunderstanding this, but faking input doesn't seem to work
- CB settings: General: fake ; APIs: protected part: input ; features: all checked

I still get the same values: @kkapsner : the only item I'm checking is getImageData [quick link](https://thorin-oakenpants.github.io/testing/canvas.html)

**Comment by Thorin-Oakenpants** [comment]
@kkapsner So I'm wondering why FF and chrome return different `toDataURLs` and `toBlobs`
- test: https://thorin-oakenpants.github.io/testing/canvas.html
- known hashes

here's FF: 771 bytes
```
data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAACyklEQVQ4jQXBsWoVOhzA4f/VWtt6bEOpcq6WQ8QDlmIhV0Q7HDA6lIIoudBB6hL0DgoiWYTeRYIILoKZHMQhi6BbBnEO6AMEnyD3DfIGv/t9IiKIEkQLYgSxgjhBvCBBkChIEiQLUgSpgjRBuiBDEBHFH0pxSitOG8WSVZxximWvOBsUK1GxmhRrWXGuKCZVcb4p1rtiYyhERHNKaZa0ZtloVqxmzWkmXrMeNCpqNpNmK2suFs20ai41zXbXzIZGRAynlWFZG1aNYWING86w6Q0XgmEaDZeTYZYNV4phXg3XmmG3G/aGQUQsS8qyoi0TY1HWsuUsU2/ZDhYdLfNk2cmW68ViquVms+x3y2JYRMRxRjnWtGPDOLas40/nmHnH1eDYiY695LiRHbeLY1Edd5vjoDvuD4eIeJaVZ6I9m8YztZ6Z88y9Zzd4TPTcSp5F9twrnsPqedg8R91zPDwiEjirAus6cMEEtm3gqgvs+sBfIbAfA3dS4CAHHpTAUQ08boEnPfB8BEQksqIiSkemJqJtZMdFjI/sh4iNkcMUcTnyqER8jTxrkdAjJyMiIolVldjUicsmMbeJPZe45RN3QuIwJv5OieOceFoSL2riVUu87ol3IyEimTWV2dKZmcns2MwNl1n4zEHIuJg5Tpl/cuZlyZzUzJuWed8zH0dGRArnVOGiLlwxheu2cNsV7vnCg1B4FAtPU+FlLvxbCm9r4UMrfOqFL6MgIpWJqkx1ZW4qxlYWrnLoK0eh4mPlRaqc5MrbUkm18rlVvvbK91ERkcZ51bikG9dM46Zt3HWNh77xODSexcar1HiTGx9K43NtfGuNH73xczREpLOuOtu6s2s6+7Zz4DpHvvMkdELsvE6d97nzqXS+1s6P1vnVO79HR0QGG2ow04M9M1jYwX03OPaD52FwEgfv0uBjHnwpg+918LMNfvfBf2PwPzS4J1/xW548AAAAAElFTkSuQmCC
```

Chrome: 188 bytes
```
data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAg0lEQVQ4T53OSxWDUBAE0XkBAuGTRAISkICESEACEpCABCQgAQlIQEIcNKWhFzW7vmdSRCi+XLPEUomxXUSvB4AbHwzKANwARuUAbgA/FQBuAJOeAG4As0oAN4BFFYAbwKoXgBvAphrADWBXA+AGcKgFcAM41QG4AVx6A7gB/PUBcLsBnIwticXKnhQAAAAASUVORK5CYII=
```

decode images here
- https://base64.guru/converter/decode/image/png

What am I doing wrong?

**Comment by Thorin-Oakenpants** [comment]
CB defaults: i.e stealth

Notes
 - `mozGetAsFile` is also covered when supported
 - overall hash doesn't change (except I have yet to do isPoint)
 - "tampered" is only used when the second pass == first pass: i.e not overtly random
 - limited to FF only because, see above post

![tampering](https://user-images.githubusercontent.com/16656956/86089633-1d719600-ba98-11ea-9179-afdeab462914.png)
