### ISSUE TITLE
get_fpjs2() returns 'no fonts detected' on Android

### ISSUE THREAD

**Issue by abrahamjuliot** [ghacksuserjs/TorZillaPrint#69]
I'm testing `get_fpjs2()` and it returns 0 fonts in FF & TB Android.

[https://jsfiddle.net/yv2k06pq/9/](https://jsfiddle.net/yv2k06pq/9/)

All fonts tested match the base fonts: https://jsfiddle.net/yv2k06pq/9/

![image](https://user-images.githubusercontent.com/6946045/88466858-84ab1c00-ce85-11ea-98c1-50f2cee0f52e.png)

Similarly, In TZP OS tests, I'm getting 'no fonts detected' on Android

![image](https://user-images.githubusercontent.com/6946045/88465224-2d517f80-ce76-11ea-9015-d2e69caa4880.png)

**Comment by abrahamjuliot** [comment]
Interesting, if with google fonts tested, 7 fonts are present.

https://jsfiddle.net/7xwkgn5q/1/

![image](https://user-images.githubusercontent.com/6946045/88469313-268e3100-cea5-11ea-814a-999c4e281611.png)

**Comment by Thorin-Oakenpants** [comment]
> I'm getting `no fonts detected` on Android

That's because it's only checking for one font .. see the `[0/1]` ... or click the hyperlink for `fonts_android_all`
