### ISSUE TITLE
fonts FF80+ & RFP

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/TorZillaPrint#71]
@abrahamjuliot 

I'll just throw this in a new issue, as my reminder to find out why it's happening. As mentioned earlier, I said the creep font test gave me different results with RFP on/off, and it shouldn't. So I dug deeper. Now I don't actually have FF80 anymore, I'm already on 81, and Beta/Dev are still on 79, but since I noted this several days ago, I can assume it started in 80: unless the cause is Nightly specific (they often put things behind release channels rather than prefs)

So I tested FF68 .. and 78, 79Dev, 79Beta
  - I always get `70 + 106` fonts in all instances, with and without RFP on

80+ Nightly
  - RFP off: `70 + 106` as expected: control value
  - RFP on: a much reduced `39 + 60` (see pic)

top: RFP on | bottom RFP off
![Nightly](https://user-images.githubusercontent.com/16656956/88607996-3dcd4a00-d070-11ea-97f5-00026afd00fe.png)

---

Here's creep's diffs: again, it only happens on 80/81 nightly
 - FF79Dev/Beta and lower stables: always `39`
 - `31` in nightly 80/81

![Nightly-creep](https://user-images.githubusercontent.com/16656956/88608045-5b021880-d070-11ea-8e20-0405c752799c.png)

See the diffs, those same diffs (if applicable) appear in my diffs: e.g. dropping `Arial Unicode MS`

---

So ... I wonder what changed in 80?

**Comment by abrahamjuliot** [comment]
This is a mystery 🤔

I tested and observed this on creep before updating to 81. In 80 RFP off, 2 additional fonts detected (MingLiU-ExtB, ZWAdobeF). In 81 RFP on, 1 additional font detected (ZWAdobeF).

My test in 81 on TZP: 
- RFP off: 2 additional fonts detected `53 + 103` (Franklin Gothic Medium, Ink Free). Note, these 2 fonts are not in my lists. 

![image](https://user-images.githubusercontent.com/6946045/88613410-3bec9200-d042-11ea-8112-0ff17d5d3f12.png)

- RFP on: `53 + 101`

![image](https://user-images.githubusercontent.com/6946045/88613589-aac9eb00-d042-11ea-86c1-491e099be8a2.png)

- diffs

![image](https://user-images.githubusercontent.com/6946045/88613884-596e2b80-d043-11ea-989e-464910b279fd.png)

**Comment by abrahamjuliot** [comment]
> In 81 RFP *off*

correction above

**Comment by earthlng** [comment]
could be because of this: https://bugzilla.mozilla.org/show_bug.cgi?id=1653987

**Comment by Thorin-Oakenpants** [comment]
^^ Yes, Jonathan Kew already alerted me to it, and it doesn't make sense IMO and needs revisiting. Flew under my radar as not part of the meta uplift.

Several main issues
 - the whitelist pref and font visibility clash (items need to be on both in order to be allowed)
   - this breaks the font protection on Tor Browser when they move to rapid release and hit 80+
 - the visibility could or should be based on spoof_english: there's no diff to entropy really. If you're en-US you use base, else you use Base + LangPacks. non en-US users probably need the lang packs
 - are the fonts in base sufficient for displaying chars

This approach needed more discussion than just assuming RFP users can live with base fonts

**Comment by earthlng** [comment]
> and it doesn't make sense IMO and needs revisiting

why? SGTM

**Comment by Thorin-Oakenpants** [comment]
> why? SGTM

OK, I'll quantify that: I'm not saying that tying vis to RFP is a bad idea, just that it needs more work
 - I don't think many knew this was being applied: where is the input from Tor Uplift: only 2 people are cc'd in on it and I think tom added himself after the fact (I cc him in on my emails)
 - given RFP is not front facing, riding the trains and getting feedback about tofu/broken glyphs is acceptable

one: conflict with whitelist
- At this stage, if you are using the whitelist, then items need to be in both lists
   - i.e most restrictive, and there is no way to allow fonts if need for non-Western chars
- Tor Browser is OK, because they can patch around it, and it doesn't affect them (if at all) until at least FF80+ (TB I think is going to move to rapid release at some stage)
- TB has old dated font lists based on Windows 7 and Mac (Linux doesn't get affected the same way: the whitelist isn't static per se)
- The `Base` + `LangPack` font lists are based on Windows 10 only and as for Linux, it's based on only **two** distros
- Whitelists from TB should cover the languages (35 including en-US) they package: they bundle some fonts (bundled fonts are auto allowed with the vis pref: but not the whitelist) and overall their list means almost every language renders on websites
- not a big deal, as long as we know how/why this happens
    - except that you can't expand beyond the `Base` fonts

two: are the fonts sufficient
- because of `one` above, you have no way to control the vis pref and are stuck with `Base` fonts at most (less if you use the whitelist and omit items from `Base`)
- is `Base` sufficient to render non-Western: how are CJK users going to handle pages of broken glyphs: What about windows 7 users (yeah, I know it's EOL, but its still supported by FF and other browsers) who don't have the needed non-Western fonts that only come bundled with Win10?
- tl;dr: font breakage because the list is too narrow

I was going to suggest that en-US users (just look at the web content setting: not the spoof_english pref because en-US builds never use that) get limited to vis = `1` but non en-US users get vis = `2` (because non en-US users are probably going to be reading stuff in their own language) - but that's a bit moot really: all languages should be rendered if possible, and be readable/usable (legible? I'm not a font expert, but I believe it really makes a difference for non-western, e.g. CJK) .. and it's probably more about non-Western .. as default fonts like Arial, Times New Roman etc cover a lot of chars (diacritics etc for European and so on). I guess I'm thinking about Hebrew, Arabic, CJK etc ..... and then Linux I expect to have a lot of issues (since it's only based on two distros)

That said, I've said my bit to JK and TR and GK and MF, and it's up to them: riding the trains is fine, let the feedback begin (I expect some breakage: maybe lots with Linux)

**Comment by earthlng** [comment]
yeah I'm actually really surprised that they went straight to the more risky Base-only list instead of easing into it by using RFP=vis:2 first. Good times to be a privileged Westerner, huh? 👍 ;)

**Comment by Thorin-Oakenpants** [comment]
> Good times to be a privileged Westerner

man, woman, elephant, hydroxy, alien DNA ... how did I do?

> surprised that they went straight to the more risky Base-only

Not sure if it's risky: since it's not front facing and TB is not affected (yet) .. just wondering why no Tor Uplift members knew about it .. or why perhaps other font Moz experts like Henri didn't glance over it (maybe they did in team meetings). Anyway, time will tell

**Comment by Thorin-Oakenpants** [comment]
@earthlng et al FYI

So I compared the unicode glyphs test. I think, but would need to check, that 802x2300 is a tofu .. 

![glyphs](https://user-images.githubusercontent.com/16656956/89094128-64f98380-d3b0-11ea-8729-17f183847ced.png)

`FFFD` = not sure yet
`097F` = **DEVANAGARI** LETTER BBA
`17DD` = **KHMER** SIGN ATTHACAN
`0D02` = **MALAYALAM** SIGN ANUSVARA
`0B82` = **TAMIL** SIGN ANUSVARA
`115A` = **HANGUL** CHOSEONG KIYEOK-TIKEUT
`FBEE`  = **ARABIC** LIGATURE YEH WITH HAMZA ABOVE WITH WAW ISOLATED FORM
`10A0` = **GEORGIAN** CAPITAL LETTER AN
`0700` = **SYRIAC** END OF PARAGRAPH

That's a few alphabets affected .. just testing 43 glypghs

**Comment by Thorin-Oakenpants** [comment]
Yup  `802x2300` for me is tofu. If you go to https://www.bamsoftware.com/talks/fc15-fontfp/fontfp.html#demo and scroll down to "Code Point Selection" you can mouse over each codepoint to see the result

**Comment by Thorin-Oakenpants** [comment]
FYI: telemetry extended until FF88
```
BASE_FONT_FAMILIES_PER_PAGE
LANGPACK_FONT_FAMILIES_PER_PAGE
USER_FONT_FAMILIES_PER_PAGE
WEB_FONT_FAMILIES_PER_PAGE
FALLBACK_TO_PREFS_FONT
FALLBACK_TO_BASE_FONT
FALLBACK_TO_LANGPACK_FONT
FALLBACK_TO_USER_FONT
MISSING_FONT
MISSING_FONT_LANGPACK
MISSING_FONT_USER
```
