### ISSUE TITLE
pluralRules

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/TorZillaPrint#76]
https://tc39.es/ecma402/#pluralrules-objects : zero, one, two, few, many, other

So I tested `211` locales, using the numbers 0-100 inclusive: this gave me 21 unique results. Increasing above 100 didn't produce any more results.

I took the `21` locales (which produce 21 unique results), and then determined which of the 101 numbers I needed. Turns out I need `11` of them.

So 11 numbers is enough to get the most entropy possible in Firefox for:
```js
	let res= [], list = [0,1,2,3,4,6,7,11,20,21,100]
	list.forEach(function(item) {
		try {
			res.push(item +": "+ new Intl.PluralRules(undefined).select(item))
		} catch(e) {
			res.push(item +": "+ "error")
		}
	})	
	console.debug(res.join(", "))
	// en: other, one, other, other, other, other, other, other, other, other, other
	// ar: zero, one, two, few, few, few, few, many, many, many, other
```

warning, the test code is messy AF

<details><summary>testing code</summary><p>

```js
	let list = [], hashes = [], unique = []
	// 212 locales
	let locales = ['aa','ab','ach','ae','af','ak','am','an','ar','as','ast','av','ay','az','ba','be',
		'bg','bh','bi','bm','bn','bo','br','bs','ca','cak','ce','ch','ckb','co','cr','crh','cs','csb',
		'cu','cv','cy','da','de','dsb','dv','dz','ee','el','en','eo','es','et','eu','fa','ff',
		'fi','fj','fo','fr','fur','fy','ga','gd','gl','gn','gu','gv','ha','haw','he','hi','hil','ho',
		'hr','hsb','ht','hu','hy','hye','hz','ia','id','ie','ig','ii','ik','io','is','it','iu','ja','jv',
		'ka','kab','kg','ki','kk','kl','km','kn','ko','kok','kr','ks','ku','kv','kw','ky','la','lb','lg',
		'li','lij','ln','lo','lt','ltg','lu','lv','mai','meh','mg','mh','mi','mix','mk','ml','mn','mr',
		'ms','mt','my','na','nb','nd','ne','ng','nl','nn','no','nr','nso','nv','ny','oc','oj','om','or',
		'os','pa','pi','pl','ps','pt','qu','rm','rn','ro','ru','rw','sa','sc','sd','sg','si','sk','sl',
		'sm','so','son','sq','sr','ss','st','su','sv','sw','ta','te','tg','th','ti','tig','tk','tlh',
		'tn','to','tr','trs','ts','tt','tw','ty','ug','uk','ur','uz','ve','vi','vo','wa','wo','xh','yi',
		'yo','za','zam','zh','zh-Hans','zh-Hant','zh-cn','zh-hk','zh-sg','zh-tw','zu',]

	console.debug(locales.length)

	//21 unique hashes
	locales = ['ar','br','bs','cs','cy','en','fr','ga','gd','gv','he','is','kw','lt','lv','mt','pl','ro','ru','sl','zh',]

	//locales = ['ar']

	for (let i=0; i < 101; i++) {list.push(i)}
	list = [0,1,2,3,4,6,7,11,20,21,100]

	// track when each instance is first found
	let f0 = true, f1 = true, f2 = true, f3 = true, f4 = true, f5 = true
	var found = []

	locales.forEach(function(l) {
		let res = []
		// reset per locale
		f0 = true, f1 = true, f2 = true, f3 = true, f4 = true, f5 = true
		let debug = ""
		// loop numbers
		list.forEach(function(item) {
			try {
				let str = new Intl.PluralRules(l).select(item)
				res.push(item +": "+ str)
				// first found
				/*
				ar:  0: zero 1: one 2: two 3: few 11: many 100: other
				br:  0: other 1: one 2: two 3: few
				bs:  0: other 1: one 2: few
				cs:  0: other 1: one 2: few
				cy:  0: zero 1: one 2: two 3: few 4: other 6: many
				en:  0: other 1: one
				fr:  0: one 2: other
				ga:  0: other 1: one 2: two 3: few 7: many
				gd:  0: other 1: one 2: two 3: few
				gv:  0: few 1: one 2: two 3: other
				he:  0: other 1: one 2: two 20: many
				is:  0: other 1: one
				kw:  0: zero 1: one 2: two 3: few 4: other 21: many
				lt:  0: other 1: one 2: few
				lv:  0: zero 1: one 2: other
				mt:  0: few 1: one 11: many 20: other
				pl:  0: many 1: one 2: few
				ro:  0: few 1: one 20: other
				ru:  0: many 1: one 2: few
				sl:  0: other 1: one 2: two 3: few
				zh:  0: other
				// numbers needed
				0,1,2,3,4,6,7,11,20,21,100
				*/
				if (f0) {
					if (str == "zero") {
						f0 = false
						debug += " " + item +": " +str
					}
				}
				if (f1) {
					if (str == "one") {
						f1 = false
						debug += " " + item +": " +str
					}
				}
				if (f2) {
					if (str == "two") {
						f2 = false
						debug += " " + item +": " +str
					}
				}
				if (f3) {
					if (str == "few") {
						f3 = false
						debug += " " + item +": " +str
					}
				}
				if (f4) {
					if (str == "many") {
						f4 = false
						debug += " " + item +": " +str
					}
				}
				if (f5) {
					if (str == "other") {
						f5 = false
						debug += " " + item +": " +str
					}
				}
			} catch(e) {
				res.push(item +": "+ "error")
			}
		})
		if (locales.length == 1) {
			console.debug(res.join("\n"))
		}
		let hash = sha1(res.join())
		unique.push(hash)
		hashes.push(hash + ": " + l)
		//console.debug(l + ": " +debug)

	})
	// unique
	unique = unique.filter(function(item, position) {return unique.indexOf(item) === position})
	unique.sort
	console.debug("unique hashes", unique.length)
	// sort
	//hashes.sort()
	//console.debug(hashes.join("\n"))

```

</p></details>

**Comment by Thorin-Oakenpants** [comment]
progress... I had a feeling that using just those `11` numbers wasn't quite right - so I built a test, so I could check and also use it on chrome to see if it changed anything (I already knew chrome had quite different grouping and more unique hashes), and to expand the numbers to see if anything else popped up, etc.

Unfortunately in my tests I used a global variable name in the wrong place (from copy pasting some code to reuse it in a different function) and never changed it. This meant that all my checks were using the wrong results from the global array. This led me down the wrong rabbit hole where I wasted many hours pissing around with preceding numbers and other things.

Terms
- `results` = the string returned such as `0: other, 1: one, 2: other`
- `locales` = the locale string per result, such as `hr, sr, dsb`
- `unique hashes`.. these are `counts` of the hashes of the result strings - I was counting them as a check

Initially I used the `counts` as a check. I was comparing `11` numbers with the main test of `101` numbers. This was a mistake in hindsight. And even when I added in the `results` hash comparison .. this too is immaterial. What I needed is to make sure that the entropy isn't altered - and that means that the sets of locales per hash should remain the same - no point there still being 21 unique groups if the distribution changes, and of course the result strings will change when we drop most numbers (look at the test e.g. clearly `... 31: one, 32: few, 35: many ...` will drop off)

So the only thing that matters is that the same locales get grouped identically. That is not the case using `11` numbers - I will do a compare of the arrays used for the `locale hashes` to see what changed

Here's the test - https://thorin-oakenpants.github.io/testing/pluralrules.html : there's also a "sanity" test you can uncomment at the end of the script: that's because I was lazy and wrote two functions (one for the main test of 101 numbers, and one to run checks) - and I wanted to make sure that each function behaved the same - I should really rewrite it as one function and pass a parameter

I can't say that this was fun: I made so many wrong assumptions and bad choices

![progress](https://user-images.githubusercontent.com/16656956/90985256-4b3ffc00-e56a-11ea-9ae7-f159f9b7334b.png)

**Comment by Thorin-Oakenpants** [comment]
@abrahamjuliot , I don't have a decent comparison tool - it looks like about a dozen locales jumped around

101 (or 64) numbers used
```
original code buckets
 - ab, ach, ae, af, an, ast, av, ay, az, ba, bg, bh, bi, ca, cak, ce, ch, ckb, co, cr, crh, csb, cu, cv, da, de, dv, ee, el, en, eo, es, et, eu, fi, fj, fo, fur, fy, gl, gn, ha, haw, hil, ho, ht, hu, hz, ia, ie, ik, io, it, iu, ka, kg, kk, kl, kr, ks, ku, kv, ky, la, lb, lg, li, lij, ltg, meh, mh, mix, ml, mn, mr, na, nb, nd, ne, ng, nl, nn, no, nr, nso, nv, ny, oc, oj, om, or, os, pi, ps, rm, sa, sc, sd, sm, so, son, sq, ss, st, sv, sw, ta, te, tig, tk, tlh, tn, tr, trs, ts, ty, ug, ur, uz, ve, vo, wa, xh, yi, za, zam, cy
 - ak
 - am, as, bn, fa, ff, fr, gu, hi, hy, hye, kab, kn, ln, mg, pa, pt, si, ti, tw, zu, bs
 - ar
 - be
 - bm
 - bo, dz, id, ig, ii, ja, jv, ki, km, ko, kok, lo, lu, mai, mi, ms, my, qu, rn, rw, sg, su, tg, th, to, tt, vi, wo, yo, zh, zh-Hans, zh-Hant, zh-cn, zh-hk, zh-sg, zh-tw, ga
 - br
 - cs
 - gv
 - he
 - hr, sr, dsb
 - hsb, sl, kw
 - is
 - lt
 - lv
 - mk, gd
 - mt
 - pl
 - ro
 - ru, uk, aa
```

11 numbers used
```
first code buckets
 - aa
 - ab, ach, ae, af, an, ast, av, ay, az, ba, bg, bh, bi, ca, cak, ce, ch, ckb, co, cr, crh, csb, cu, cv, da, de, dv, ee, el, en, eo, es, et, eu, fi, fj, fo, fur, fy, gl, gn, ha, haw, hil, ho, ht, hu, hz, ia, ie, ik, io, it, iu, ka, kg, kk, kl, kr, ks, ku, kv, ky, la, lb, lg, li, lij, ltg, meh, mh, mix, ml, mn, mr, na, nb, nd, ne, ng, nl, nn, no, nr, nso, nv, ny, oc, oj, om, or, os, pi, ps, rm, sa, sc, sd, sm, so, son, sq, ss, st, sv, sw, ta, te, tig, tk, tlh, tn, tr, trs, ts, ty, ug, ur, uz, ve, vo, wa, xh, yi, za, zam, br
 - ak
 - am, as, bn, fa, ff, fr, gu, hi, hy, hye, kab, kn, ln, mg, pa, pt, si, ti, tw, zu, be
 - ar
 - bm
 - bo, dz, id, ig, ii, ja, jv, ki, km, ko, kok, lo, lu, mai, mi, ms, my, qu, rn, rw, sg, su, tg, th, to, tt, vi, wo, yo, zh, zh-Hans, zh-Hant, zh-cn, zh-hk, zh-sg, zh-tw, ga
 - bs
 - cs
 - cy
 - dsb
 - gd
 - gv
 - hr, sr, he
 - hsb, sl, is
 - kw
 - lv
 - pl
 - ro
 - ru, uk, lt
 - sk, mt
```

**Comment by abrahamjuliot** [comment]
This is fascinating. About a dozen jumps looks about right [here](https://www.diffchecker.com/cv9T19VQ).

**Comment by Thorin-Oakenpants** [comment]
Using `11` numbers is fine: the locale buckets stay the same

![tada](https://user-images.githubusercontent.com/16656956/91053478-66fedd00-e612-11ea-80f8-f8e0c6819127.png)

I should have paid more attention. I can't believe I wasted so much time over this, and made so many fuckups. My shitty code wasn't correctly putting the first/last (?) item in the right locales buckets (I even dropped recording the very first or very last locale - the above samples above only contain 210 locales). You can see it in the diffs checker - the fact the items in each bucket aren't properly sorted gives it away

```
- hr, sr, dsb
- hsb, sl, kw
```

should be
```
- last item from previous line, hr, sr
- dsb, hsb, sl
- kw, etc
```

I simplified and re-built the test page code, and use a single function I call three times (for the main test and the subsequent two re-runs) ... that way every test uses the exact same code
