### ISSUE TITLE
research math78+ test

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/TorZillaPrint#78]
@abrahamjuliot : https://ghacksuserjs.github.io/TorZillaPrint/math.html - quick basic first version

ToDo
* [x] add ECMA 6th edition tests - use creep: see https://github.com/abrahamjuliot/creepjs/issues/36
* [x] add a control result (e.g. FF78 64bit build on 64bit windows)
* [x] list results !== control
* [x] list function !== polyfill
* [x] add readable test name in display
* [x] use user assigned numbers so it's scalable
* [x] output numbers where !== control (ignore where polyfill !== function)
   - over all our tests, we record these numbers
   - at the end, all the test numbers in play may still have some redundancy but will ensure max entropy: and those not recorded can be dropped
* [x] add hash and numbers !== control to display output (so it's in the copy to clipboard)
* [x] pretty up the output so it's easier to visually scan
* [x] improved diffs usability by adding function info
* [x] add TZP's ECMA 1st edition `cos` tests: hash + output separately with short codes
   - if we're going to be testing, I want this piggybacked on
* [x] add polyfills
- [x] increase tests
- [x] programmatically calculate the polyfill based on the each test
- [x] tabulated results into columns in both display and diffs
- [x] polyfill results use the user-assigned number + `p1` or `p2` etc to denote which polyfill
- [x] output `cos`, `sin`, `tan` main tests as an additional separate result/hash for TZP analysis
- [x] finalize tests
- [x] add choosing a "control" set
- add polyfill alternatives
   - nah, for now

**THEN** .. when our code is settled and we start testing - see #79 
* set up a list of browsers, browser versions, build-architecture, OS, OS-architecture to test
   - note: we only need start from FF78 with Gecko
* each new hash, assign a letter (short code) and add to the database
   - future unknown hashes we can then highlight as `[NEW]`

NOTE: numbers with `p1`/`p2` etc means the polyfill result

Here's some results (only added 3 polyfills at this stage)
```
Win7 64bit-OS
==============
	64bit ESR60, FF60-67
		8653818e4e1eb30d97cefaca26ee69096f603974
		18, 20p, 46p
	64bit ESR68, ESR78, FF68-80, Dev81, Beta81, Nightly81
		e8ea8fed47f4075829ac813f0c5f5a7c55c64d34 - everything matches
	64bit TB68, TB78
		70d0e68663eea3dfdc35bb5c916b672505992cb6 
		17, 38, 39
	32bit TB68, TB78
		aadd9848fdf763970cff42f6ac3005ab0a123c1b 
		17, 38, 39, 56
	64bit TB60
		a67bc48f4268611c8cac8f574965c42baab04d32
		17, 18, 38, 39, 20p, 46p
	32bit TB60
		c484820e0bdbbeb96880135ecd9e1d42c249d962
		10p, 20p, 6, 9, 10, 17, 20, 38, 39, 47, 53, 56, 58, 60, 61, 62, 63, 64, 65, 66, 67, 68

	64bit CHROME83, OPERA70
		hash 21df3e85b281c1b1e7b55f4685cf6ac338eb8a88
		25, 31, 37, 60, 61, 62, 63, 64, 65, 66, 67, 68

ANDROID
	64bit I assume: TB68, FF80, Nightly82 - same as control

```

**Comment by Thorin-Oakenpants** [comment]
updated it
- we don't need an "all" hash, we have a function hash and a polyfill hash: that's enough, but we could add it in if it makes it easier
- I added control values (`ESR78/FF78 - 64bit build on 64bit windows7`): this gives us a baseline as to what items cause entropy
   - excuse the typo in the picture, I will fix it. The control is FF78 not 68
- in the display results (the ones you can copy to clipboard), I color anything not matching control as that pale red
- I always display a second value if a polyfill is used
- I output what polyfills do not match function
- I output what functions do not match control
- I output what polyfills do not match control

Here is FF/ESR60
![ESR60](https://user-images.githubusercontent.com/16656956/91656474-76fe3d00-eaa8-11ea-9058-8b55fc36feb6.png)

**Comment by Thorin-Oakenpants** [comment]
added a "numbers" output so we know which tests are in play. `p` after a number denotes it was the polyfill.

Here's some results
```
Win7 64bit-OS
==============
	64bit ESR60, FF60-67
		8653818e4e1eb30d97cefaca26ee69096f603974
		18, 20p, 46p
	64bit ESR68-80, Dev81, Beta81, Nightly81
		e8ea8fed47f4075829ac813f0c5f5a7c55c64d34 - everything matches
	64bit TB68, TB78
		70d0e68663eea3dfdc35bb5c916b672505992cb6 
		17, 38, 39
	32bit TB68, TB78
		aadd9848fdf763970cff42f6ac3005ab0a123c1b 
		17, 38, 39, 56
	64bit TB60
		a67bc48f4268611c8cac8f574965c42baab04d32
		17, 18, 38, 39, 20p, 46p
	32bit TB60
		c484820e0bdbbeb96880135ecd9e1d42c249d962
		10p, 20p, 6, 9, 10, 17, 20, 38, 39, 47, 53, 56, 58, 60, 61, 62, 63, 64, 65, 66, 67, 68

	64bit CHROME83, OPERA70
		hash 21df3e85b281c1b1e7b55f4685cf6ac338eb8a88
		25, 31, 37, 60, 61, 62, 63, 64, 65, 66, 67, 68
```

So next up we need to add more polyfills. Then I think we're ready (besides my ECMA1 TZP stuff) to test and record results: we give each hash we get a short code. And if's it's not one we've seen before, we append `NEW` in bright red to alert us to update our code and results

Results can be stored as a list of `shortcode: browsers` - we could even add it as an array to output on the page. And what we'll need as well is a list of browsers etc to check off

**Comment by Thorin-Oakenpants** [comment]
@abrahamjuliot ,, it's looking good. I'm up to finalizing the list of math tests, and adding all the polyfills - so waiting on you to finish at your end with what you want and are happy with (and how to code the polyfills).

Then it's a matter of testing. I have my 32/64 bit FF's and TBs on windows 32/64 bit. I have Mint32 and Mint64. I know someone who can test Fedora32 (they just need to copy to clipboard and email the results, which also comes in handy on Android), and I know someone else with a Mac - both Moz engineers. And I have those Linux VMs (debian, ubuntu). And I can install more - I have isos already downloaded for CentOS, deepin, elementaryOS, fedora, gentoo, kubuntu, lubuntu, MXLinux - but TBH I'm not a linux expert and some might be a waste of time (e.g. if we have ubuntu, do we need kubuntu - etc).

I can always ask for pastes of the clipboard from the users at ghacks user.js (and maybe nudge a few moz devs)

Waiting on you.... PS: comment and improvement ideas welcome

**Comment by abrahamjuliot** [comment]
This test looks really nice. Here are the polyfills. =)

These are all compiled from MDN with minor structure changes. 

```js
/*
Math.acosh
Math.asinh
Math.atanh
Math.cosh
Math.cbrt
Math.expm1
Math.hypot
Math.log1p
Math.log2
Math.log10
Math.sinh
Math.tanh
*/

const acosh = x => Math.log(x + Math.sqrt(x * x - 1))

const asinh = x => {
    const absX = Math.abs(x)
    if (absX < Math.pow(2, -28)) {
        return x
    }
    const w = (
        absX > Math.pow(2, 28) ? Math.log(absX) + Math.LN2 :
        absX > 2 ? Math.log(2 * absX + 1 / Math.sqrt(x * x + 1)) :
        Math.log1p(absX + (x * x) / (1 + Math.sqrt(1 + (x * x))))
    )
    return x > 0 ? w : -w
}

const atanh = x => Math.log((1 + x) / (1 - x)) / 2

const cosh = x => (Math.exp(x) + Math.exp(-x)) / 2

const cbrt = x => x < 0 ? -Math.pow(-x, 1 / 3) : Math.pow(x, 1 / 3)

const expm1 = x => Math.exp(x) - 1

const hypot = (...arguments) => {
    let i, s = 0,
        max = 0,
        isInfinity = false,
        len = arguments.length
    for (i = 0; i < len; ++i) {
        const arg = Math.abs(+arguments[i])
        if (arg === Infinity) {
            isInfinity = true
        }
        if (arg > max) {
            s *= (max / arg) * (max / arg)
            max = arg
        }
        s += arg === 0 && max === 0 ? 0 : (arg / max) * (arg / max)
    }
    return isInfinity ? Infinity : (max === Infinity ? Infinity : max * Math.sqrt(s))
}

const log1p = x => {
    const nearX = (x + 1) - 1
    return (
        x < -1 || x !== x ? NaN :
        x === 0 || x === Infinity ? x :
        nearX === 0 ? x :
        x * (Math.log(x + 1) / nearX)
    )
}

const log2 = x => Math.log(x) * Math.LOG2E

const log10 = x => Math.log(x) * Math.LOG10E

const sinh = x => (Math.exp(x) - Math.exp(-x)) / 2

const tanh = x => {
    const a = Math.exp(+x)
    const b = Math.exp(-x)
    return a == Infinity ? 1 : b == Infinity ? -1 : (a - b) / (a + b)
}
```

**Comment by Thorin-Oakenpants** [comment]
^^ cool. Do you want me to expand the tests to match your current list - it was 103 a little while ago?

**Comment by Thorin-Oakenpants** [comment]
hah ...`Uncaught SyntaxError: 'arguments' can't be defined or assigned to in strict mode code`

**Comment by Thorin-Oakenpants** [comment]
hmmm

```js
	function hypotA(value1, value2) {
		let i, n = 0, args = arguments, len = args.length
		for (i = 0; i < len; i++) {
			n += args[i] * args[i]
		}
		return Math.sqrt(n)
	}

	function hypotB(array) {
		let i, s = 0,
			max = 0,
			isInfinity = false,
			len = array.length
		for (i = 0; i < len; ++i) {
			const arg = Math.abs(+array[i])
			if (arg === Infinity) {
				isInfinity = true
			}
			if (arg > max) {
				s *= (max / arg) * (max / arg)
				max = arg
			}
			s += arg === 0 && max === 0 ? 0 : (arg / max) * (arg / max)
		}
		return isInfinity ? Infinity : (max === Infinity ? Infinity : max * Math.sqrt(s))
	}

	console.debug("A: " + hypotA(5.860847362277284e+38, 5.860847362277284e+38) )
	console.debug("B: " + hypotB([5.860847362277284e+38, 5.860847362277284e+38]) )
```

gives two different results
```
	// A vs B gives different results (FF control)
	// A: 8.288489826731114e+38
	// B: 8.288489826731116e+38 <-- does not match function
```

**Comment by abrahamjuliot** [comment]
> expand the tests

I think the more the better. But, some may prove useless. Howevre, I am finding differences between FF Windows, MacOS and Android, mostly through more cos and sin tests, and then the ES6 tests prevent Safari from blending in with FF on MacOS.

> hypot

I prefer `hypotB` (MDN's), but both can be used and both have potential to differ from `Math.hypot` depending on the input and the environment.

**Comment by Thorin-Oakenpants** [comment]
>  But, some may prove useless. However, I am finding differences between FF Windows, MacOS and Android, mostly through more cos and sin tests, ...

Yup. My `cos` values are a **minimum** set for max entropy - from that research paper where they tested loads. There will be tons of them are differ between engines

The thing is you **only need one** (well, probably three or four for fallback/depth) difference between **engines** (and even then that is not needed as you can get the browser engine via other means) ... what is really important is differences between architecture that causes entropy within each engine bucket. I found chrome to be very resistant to this (e.g. as if they bundle their own math library the same for all builds), and Safari will be much the same: a pretty much locked down and limited OS/hardware.

> I think the more the better. ...

OK. I'm adding new items to `fns = [` .. so I can auto generate the polyfills. Not sure how to add multiple polyfill tests (I doubt we'll do more than two, so i can do that)
```
		// [item number for easy reference, function, value, description, control, poly, poly control value...]
```

multiple polyfill methods .. there's also the `asinh` polyfill which uses `Math.log1p` ... it could use the `log1p` polyfill

**Comment by Thorin-Oakenpants** [comment]
OK, so I'm using the `fns` array to auto generate polyfills. I can extend it to include a 2nd (or more) alternative polyfills, but for now I'm just doing the one

e.g.
```js
var fns = [ //...
	[ 40, 'acosh', [1e308], "1e300", 709.889355822726, "Infinity"],
	[ 41, 'acosh', [Math.PI], "Math.PI", 1.811526272460853, 1.8115262724608532],
	[ 42, 'acosh', [Math.SQRT2], "Math.SQRT2", 0.881373587019543, 0.8813735870195432],
```

Is there an easier way to do this by passing the function name and just using one line?
```js
// replace this
		if (fn[5] !== undefined && fn[5] !== "") {
			poly1Control = fn[5].toString()
			if (fnName == "acosh") {
				poly1Result = (acosh(...fn[2])).toString()
			} else if (fnName == "asinh") {
				poly1Result = (asinh(...fn[2])).toString()
			} else if (fnName == "GIANT_BANANA") {
				poly1Result = (GIANT_BANANA(...fn[2])).toString()
			} // etc etc etc
		}

//with something like this
		if (fn[5] !== undefined && fn[5] !== "") {
			poly1Control = fn[5].toString()
			poly1Result = (   fnName(...fn[2])   ).toString()
		}
```

I can't seem to work out how to use the string to call the polyfill

**Comment by Thorin-Oakenpants** [comment]
@abrahamjuliot  - almost all done (gimme a final test list)
- in my control browser, I get `26` polyfills which don't match the function
- chrome vs control: I get `48` non-matches (non are polyfills) and there's a lot of redundacy
   - differences between engines is easy :)  tests will tell what happens between browser + architectures + OS

Still to do
- update tests to a final version to match yours: currently at `102` - same as you were about a two days ago
   - **NOTE** - I said `103` but you had a duplicate line, the last `pow` one
- add secondary polyfills - `hypotA` and `asinhA` - these get denoted with `p2` and end up in a third column in the data section

**Comment by Thorin-Oakenpants** [comment]
so far my initial findings are that the polyfills aren't making a difference (i.e: within FF) and that it's the ECMA 1st Edition `cos`, `sin`, `tan` that do. I already have some `cos` ones that according to research are the minimum set. That minimum set of TZP cos values also changes when you change to chrome or safari.

as it currently stands
```
FF Android
b7b5b5144d9a308b21ecfb13d7497df358dd2e5b
cos: 185, 186, 187, 188, 189, 190, 192,
sin: 345, 346,
tan: 402, 403, 404, 405, 406, 407
```

My TZP cos values gets at least 8 different FF results (codes A to H) that I know of. It will interesting to see if changes in the main test `cos`, `sin` and `tan` are the same per code (A to H) - which would make them redundant (for entropy within FF)

note: "standartan" is as per source
> According to the ECMAScript draft, which was defined on November 27, 2017, the implementation of IEEE 754-2008, which has floating-point standartan, atanh, atan2, cbrt, cos, cosh, exp, expm1, hypot, log, log1p, and ld is recommended. However, for acos, acosh, asin, asinh, atan, atanh, atan2, cbrt, cos, cosh, exp, expm1, hypot, log, log1p, log2, log10, pow, random, sin, sinh, sqrt, tan, and tanh, the computational result depends on the platform because they are implemented using the math library provided by the platform.
>
> In this paper, we used math object methods with a large number of digits in the computational result. In particular, we used Math.sin, Math.cos, Math.tan, Math.log, Math.exp, and Math.sqrt for the verification experiments. In addition, we conducted an exhaustive investigation using two types of method arguments
> - Argument 1:  10<sup>0</sup> ,10<sup>1</sup> ,...,10<sup>299</sup> ,10<sup>300</sup>
> - Argument 2:  −10<sup>0</sup> ,−10<sup>1</sup> ,...,−10<sup>299</sup> , −10<sup>300</sup>

And here's a little breakdown of what math functions gave entropy
```
Math object : Number of classifications
   Math.cos : 13
   Math.sin : 12
   Math.tan : 11
   Math.exp : 4
   Math.log : 2
  Math.sqrt : 2
```

Seems like anything sin and tan can do, can be covered by cos: And the rest didn't **add** anything new

I'm in the process of "zipping" up (well, rar actually) some papers for you @abrahamjuliot for your "resources" - to be dumped on a dropbox public folder. That math paper is one of them

**Comment by abrahamjuliot** [comment]
> papers

Sweet! I've been starving for math resources. Research seems rare on this subject.

**Comment by abrahamjuliot** [comment]
> update tests

I think my tests, currently at `102` now, will remain static for a season. I'm interested in testing advanced functions from js libraries and complex functions with no native Math methods. I have a test that loops through 10000 cases and then I compare browsers in nodejs (comparing in the browser is too slow, eats up ~2g of ram and then freezes up).

**Comment by Thorin-Oakenpants** [comment]
I send you a message for the download link

**Comment by Thorin-Oakenpants** [comment]
I **might** add the ability to select a control set from a dropdown - and add a re-run button: e.g
 - FF78-64bit Windows-64bit
 - Chrome-whatever-stable is-64bit on Windows-64bit
 - Safari on a Mac

That way it's easier to pinpoint entropy per engine. I don't need it, and it seems pretty simple to implement - what do you think?

**Comment by abrahamjuliot** [comment]
I like that idea, if it's simple to implement.

**Comment by Thorin-Oakenpants** [comment]
alrighty .. I've piggybacked the tests cos/sin/tan into TZP (they're still also in the main test). This way I can confirm that every time I get a letter in FF,  I always get the same corresponding hash for the new ones
 - i.e `A` always gets `da51d38c6fcfc30599124515a36779c0d021a58d`

![piggybacked](https://user-images.githubusercontent.com/16656956/92181098-fe94d480-ee37-11ea-89ac-3d80823597de.png)

Next I'm adding in a control set: this should be easy. Then you can easily for any entropy within engines

**Comment by Thorin-Oakenpants** [comment]
@abrahamjuliot - waiting on your to give me some mac results. I've added the control sets. Load the test in Safari, open the console log, run the firefox or chrome button and paste me back the two lists - thanks

**Comment by abrahamjuliot** [comment]
Safari =)

[Log] CONTROL LIST: tzp
'-0.3741957749963415','-0.7854805190645292','0.7914463018528903','-0.7672248942219131','-0.7415825695514535','0.5403023058681398','0.7086865671674247','-0.7482651726250322','0.9924450321351935','-1','-0.10868049424995659','-0.8913089376870335','-0.7108118501064331','-0.536911695749024','-0.40677759702517235','-0.7017203400855446','0.4362848063618998','-0.6982689820462377','-0.6982689820462377','-0.6534063185820198','0.4537557425982784','0.6459044007438142','0.994076732536068','1.2246467991473532e-16','-0.7181630308570677','-0.765996413898051','0.9989410140273756','0.10135692924965616','-0.37463575478582023','-0.9892668187780498','0.5086861259107567','-1.2246467991473532e-16','0.686676154645243','1.6182817135715875','-3.353712870537602','-1.922295546179998','-1.922295546179998','2.5824856130712437'

[Log] CONTROL LIST: new
'1.4474840516030245','0.7853981633974483','709.889355822726','Infinity','1.811526272460853','1.8115262724608532','0.8813735870195432','0.8813735870195432','0.12331227519187199','691.4686750787736','691.4686750787736','1.8622957433108482','1.885022066017804','1.1071487177940906','1.2626272556789115','0.5493061443340549','0.5493061443340549','5e-311','1.0038848218538872','4.641588833612779','1.4645918875615234','0.9924450321351935','-1','-0.10868049424995659','-0.8913089376870335','-0.7108118501064331','-0.536911695749024','-0.40677759702517235','-0.7017203400855446','0.4362848063618998','-0.6982689820462377','-0.6982689820462377','-0.6534063185820198','0.4537557425982784','0.6459044007438142','1.5430806348152437','1.5430806348152437','11.591953275521519','11.591953275521519','9.199870313877772e+307','1.0469199669023138e+308','1.7182818284590453','22.140692632779267','1.1308844209474893','23.140692632779267','9.539392014169456','9.539392014169458','8.288489826731116e+38','8.288489826731116e+38','100.14767208675259','100.14767208675259','101.76102278593319','101.76102278593319','100.0096085986525','100.0096085986525','100.01040630344929','100.01040630344929','100.00999950004999','100.00999950004999','100.0024999687508','100.0024999687508','100.00377216279416','100.00377216279416','-2.0955709236097197','1.1447298858494002','0.11600367575630613','0.11600367575630613','1.4210804127942926','1.4210804127942926','-0.9100948885606021','-0.9100948885606022','0.49714987269413385','0.49714987269413385','0.4342944819032518','0.4342944819032518','1.965773398945507','1.965773398945507','-0.1591745389548616','-0.1591745389548616','0.8822181462033635','0.8822181462033635','0.15917453895486158','0.15917453895486158','1.7926429945344482','1.792642994534448','-0.36221568869946325','-0.3622156886994632','0.48288235131479357','0.4828823513147936','-0.15051499783199057','-0.15051499783199057','0.15051499783199063','0.1505149978319906','0.15051499783199063','0.1505149978319906','0.994076732536068','1.2246467991473532e-16','-0.7181630308570677','-0.765996413898051','0.9989410140273756','0.10135692924965616','-0.37463575478582023','-0.9892668187780498','1.1752011936438014','1.1752011936438014','11.548739357257746','11.548739357257748','7.544137102816975','7.544137102816975','0.75','0.75','1.9978980091062795','1.9978980091062797','9.199870313877772e+307','Infinity','0.44807597941469024','0.4480759794146903','0.7675231451261164','0.7675231451261164','1.9350668221743568','1.9350668221743568','1.0469199669023138e+308','Infinity','0.3507135583350036','1.7724538509055159','0.5086861259107567','-1.2246467991473532e-16','0.686676154645243','1.6182817135715875','-3.353712870537602','-1.922295546179998','-1.922295546179998','2.5824856130712437','0.12238344189440876','0.12238344189440872','0.99627207622075','0.9962720762207501','1.022089333584519e+91','1.9275814160560206e-50','3.7200759760208555e-44','8269017203802394','6.003867926738829e-37','1.20933355845501e-16','1.6655929347585955e+36','1125899906842616.2','8.881784197001191e-16'

- Safari Version 13.0.5 (15608.5.11)
- macOS Catalina 10.15.3 (19D76)

I'm running Catalina in a 64bit VMware running in a 64bit Win10 running in single system Bootcamp on a Macbook Pro Device.

**Comment by Thorin-Oakenpants** [comment]
done and updated. Yeah, it'll be interesting to see if a VM has any affect, but I don't think it does. I used a couple of free trials on some testing labs online to get results on Mac and they were backed up by real Mac users. I unfortunately couldn't get MacOS-in-a-VM to work on my Windows AMD

The only thing left is possibly adding the alternative polyfills. But quite frankly I think we can leave them out: it seems as if polyfills aren't doing anything for entropy **within** engines (and we don't need them for entropy **between** engines)

So I think we just need to start collecting results. BTW, my portable chrome was actually version 72 32bit. I only use it for local file testing. I updated it to 85, no changes from the chrome control set. I then installed chrome 85 64bit - and it too matches the chrome control set.

I need a breather ... and to think how we can run these and how the format to record them
- do we always record all results against the FF control, or against the engine it's being tested in
- format: I think we just need the browser/OS details, the TZP hashes and numbers, the main test hashes and number?
- as we get more results we can start assigning letters/numbers into a table where y = browser tested and x = assigned letter?

I say just start winging it. Test against FF and report results. I'll start a new topic. BTW, you should have write access to edit the results
