### ISSUE TITLE
math results

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/TorZillaPrint#79]
### BROWSER LIST

Windows 7 64bit
* [x] TB60 64+32bit
* [x] TB68 64+32bit
* [x] TB78 64+32bit
* [x] ESR60-68-78, FF60-82 64bit
* [x] ESR60-68-78, FF60-82 32bit
* [x] Chrome 72/85 64+32bit

Windows 7 32bit (VM)
* [ ] TB60 32bit
* [ ] TB68 32bit
* [ ] TB78 32bit
* [ ] ESR60-68-78, FF60-82 32bit
* [ ] Chrome 85 32bit

Windows 10 64bit
* [ ] spot check against windows 7 64bit results: it should be the same

Android (aarch64)
* [x] TB68
* [x] FF68, Fenix78+

MacOS
* [x] FF78+, TB78 (macOS 10.15)
* [ ] Safari
* [ ] Chrome 85 64bit

Linux 32bit
* TBA

Linux 62bit
* TBA

**Comment by Thorin-Oakenpants** [comment]
### MAIN RESULTS

**Comment by Thorin-Oakenpants** [comment]
Interesting, so far, that in the TZP tests, the `B` entropy is already increased from one to two by adding any one of 400, 402, 407 (which are `tan`) .. so that's one up on that math research 👍  I'm sure you can follow by code structure there, first letter is the original test, second is the extras. First result for original code each gets the same letter for the second - but if I find anymore, then I start assigning new ones from Z up

**Comment by Thorin-Oakenpants** [comment]
@abrahamjuliot .. I think before we go any further, we should ditch the TZP + TZP extended. I can already what I need to see. I'm going to get at least one result for each of my `A`-`H` and now I have a `Z` as well. It's a bit messy dealing with two lots

We should just merge my eight cos tzp tests into the main test and deal with one result per browser.

**Comment by Thorin-Oakenpants** [comment]
Note that I have a `GG` and a `DG` (and there will be a `DD`, 99% sure).. whereas both of those in the main test are F20. So that confirms that the original TZP cos tests add entropy to the main test

I'll get busy merging it all into a single test. And I will add in the same cos tests from TZP as sin and tan, because WTF not :)

**Comment by Thorin-Oakenpants** [comment]
@abrahamjuliot - I need a new mac control set from your console

math version 2 done
- now a single test - no TZP original or TZP extended
- added original TZP cos tests into the single test
- added sin and tan with the TZP cos values
   - yes, they change as well, but until we do full on results analysis we don't know if they're redundant
- replaced user defined numbers with math function name + test number in that function
   - e.g. cos0, cos1 ... sin0, sin1...
- numbers in play is easier to read and see exactly what is being used
  - new line per math function
  - function name once, then numbered items: e.g:
  - > sin: 10, 11, 12, 13, 14, 15
 sinh: 5, 9
- perf added for the lulz

I've added some v2 hashes. I need a coffee

**Comment by abrahamjuliot** [comment]
Looks good. Here's Safari

[Log] CONTROL LIST:
 '1.4474840516030245','0.7853981633974483','709.889355822726','Infinity','1.811526272460853','1.8115262724608532','0.8813735870195432','0.8813735870195432','0.12331227519187199','691.4686750787736','691.4686750787736','1.8622957433108482','1.885022066017804','1.1071487177940906','1.2626272556789115','0.5493061443340549','0.5493061443340549','5e-311','1.0038848218538872','4.641588833612779','1.4645918875615234','-0.3741957749963415','-0.7854805190645292','0.7914463018528903','-0.7672248942219131','-0.7415825695514535','0.5403023058681398','0.7086865671674247','-0.7482651726250322','0.9924450321351935','-1','-0.10868049424995659','-0.8913089376870335','-0.7108118501064331','-0.536911695749024','-0.40677759702517235','-0.7017203400855446','0.4362848063618998','-0.6982689820462377','-0.6982689820462377','-0.6534063185820198','0.4537557425982784','0.6459044007438142','1.5430806348152437','1.5430806348152437','11.591953275521519','11.591953275521519','9.199870313877772e+307','1.0469199669023138e+308','1.7182818284590453','22.140692632779267','1.1308844209474893','23.140692632779267','9.539392014169456','9.539392014169458','8.288489826731116e+38','8.288489826731116e+38','100.14767208675259','100.14767208675259','101.76102278593319','101.76102278593319','100.0096085986525','100.0096085986525','100.01040630344929','100.01040630344929','100.00999950004999','100.00999950004999','100.0024999687508','100.0024999687508','100.00377216279416','100.00377216279416','-2.0955709236097197','1.1447298858494002','0.11600367575630613','0.11600367575630613','1.4210804127942926','1.4210804127942926','-0.9100948885606021','-0.9100948885606022','0.49714987269413385','0.49714987269413385','0.4342944819032518','0.4342944819032518','1.965773398945507','1.965773398945507','-0.1591745389548616','-0.1591745389548616','0.8822181462033635','0.8822181462033635','0.15917453895486158','0.15917453895486158','1.7926429945344482','1.792642994534448','-0.36221568869946325','-0.3622156886994632','0.48288235131479357','0.4828823513147936','-0.15051499783199057','-0.15051499783199057','0.15051499783199063','0.1505149978319906','0.15051499783199063','0.1505149978319906','-0.9273497301314577','-0.6188863822787812','-0.6112387023768895','0.6413781736901984','0.6708616046081811','0.8414709848078965','-0.7055234578073583','0.66339975236386','0.994076732536068','1.2246467991473532e-16','-0.7181630308570677','-0.765996413898051','0.9989410140273756','0.10135692924965616','-0.37463575478582023','-0.9892668187780498','1.1752011936438014','1.1752011936438014','11.548739357257746','11.548739357257748','7.544137102816975','7.544137102816975','0.75','0.75','1.9978980091062795','1.9978980091062797','9.199870313877772e+307','Infinity','0.44807597941469024','0.4480759794146903','0.7675231451261164','0.7675231451261164','1.9350668221743568','1.9350668221743568','1.0469199669023138e+308','Infinity','0.3507135583350036','1.7724538509055159','2.4782474632176816','0.7879079967710035','-0.772305968131876','-0.8359715365344824','-0.9046350765956541','1.557407724654902','-0.9955366596368417','-0.8865837628611646','0.5086861259107567','-1.2246467991473532e-16','0.686676154645243','1.6182817135715875','-3.353712870537602','-1.922295546179998','-1.922295546179998','2.5824856130712437','0.12238344189440876','0.12238344189440872','0.99627207622075','0.9962720762207501','1.022089333584519e+91','1.9275814160560206e-50','3.7200759760208555e-44','8269017203802394','6.003867926738829e-37','1.20933355845501e-16','1.6655929347585955e+36','1125899906842616.2','8.881784197001191e-16'

**Comment by Thorin-Oakenpants** [comment]
done, if you want to make sure it matches Safari on a macOS

**Comment by abrahamjuliot** [comment]
matches 👍 

![image](https://user-images.githubusercontent.com/6946045/92349255-5cb8f600-f08a-11ea-9355-03815c2d32cd.png)

**Comment by Thorin-Oakenpants** [comment]
hah .. just noticed we left off the polyfill for `expm1` .. but it shouldn't make a difference: it was one that helped entropy in FF67 or lower, and they're obsolete now

**Comment by Thorin-Oakenpants** [comment]
@abrahamjuliot .. if you can generate a new safari control list, that'd be cool

I added in the missing `expm1` and `cbrt` polyfill functions (and results), and added two missing polyfill results in `cosh`. This makes it easy for porting to TZP where all the comparing is dropped and I don't need to check for any control values.

**Comment by abrahamjuliot** [comment]
Here's Safari :)

[Log] CONTROL LIST:
 '1.4474840516030245','0.7853981633974483','709.889355822726','Infinity','1.811526272460853','1.8115262724608532','0.8813735870195432','0.8813735870195432','0.12331227519187199','691.4686750787736','691.4686750787736','1.8622957433108482','1.885022066017804','1.1071487177940906','1.2626272556789115','0.5493061443340549','0.5493061443340549','5e-311','1.0038848218538872','4.641588833612779','4.641588833612778','1.4645918875615234','1.4645918875615231','-0.3741957749963415','-0.7854805190645292','0.7914463018528903','-0.7672248942219131','-0.7415825695514535','0.5403023058681398','0.7086865671674247','-0.7482651726250322','0.9924450321351935','-1','-0.10868049424995659','-0.8913089376870335','-0.7108118501064331','-0.536911695749024','-0.40677759702517235','-0.7017203400855446','0.4362848063618998','-0.6982689820462377','-0.6982689820462377','-0.6534063185820198','0.4537557425982784','0.6459044007438142','1.5430806348152437','1.5430806348152437','11.591953275521519','11.591953275521519','9.199870313877772e+307','Infinity','1.0469199669023138e+308','Infinity','1.7182818284590453','1.718281828459045','22.140692632779267','22.140692632779267','1.1308844209474893','23.140692632779267','9.539392014169456','9.539392014169458','8.288489826731116e+38','8.288489826731116e+38','100.14767208675259','100.14767208675259','101.76102278593319','101.76102278593319','100.0096085986525','100.0096085986525','100.01040630344929','100.01040630344929','100.00999950004999','100.00999950004999','100.0024999687508','100.0024999687508','100.00377216279416','100.00377216279416','-2.0955709236097197','1.1447298858494002','0.11600367575630613','0.11600367575630613','1.4210804127942926','1.4210804127942926','-0.9100948885606021','-0.9100948885606022','0.49714987269413385','0.49714987269413385','0.4342944819032518','0.4342944819032518','1.965773398945507','1.965773398945507','-0.1591745389548616','-0.1591745389548616','0.8822181462033635','0.8822181462033635','0.15917453895486158','0.15917453895486158','1.7926429945344482','1.792642994534448','-0.36221568869946325','-0.3622156886994632','0.48288235131479357','0.4828823513147936','-0.15051499783199057','-0.15051499783199057','0.15051499783199063','0.1505149978319906','0.15051499783199063','0.1505149978319906','-0.9273497301314577','-0.6188863822787812','-0.6112387023768895','0.6413781736901984','0.6708616046081811','0.8414709848078965','-0.7055234578073583','0.66339975236386','0.994076732536068','1.2246467991473532e-16','-0.7181630308570677','-0.765996413898051','0.9989410140273756','0.10135692924965616','-0.37463575478582023','-0.9892668187780498','1.1752011936438014','1.1752011936438014','11.548739357257746','11.548739357257748','7.544137102816975','7.544137102816975','0.75','0.75','1.9978980091062795','1.9978980091062797','9.199870313877772e+307','Infinity','0.44807597941469024','0.4480759794146903','0.7675231451261164','0.7675231451261164','1.9350668221743568','1.9350668221743568','1.0469199669023138e+308','Infinity','0.3507135583350036','1.7724538509055159','2.4782474632176816','0.7879079967710035','-0.772305968131876','-0.8359715365344824','-0.9046350765956541','1.557407724654902','-0.9955366596368417','-0.8865837628611646','0.5086861259107567','-1.2246467991473532e-16','0.686676154645243','1.6182817135715875','-3.353712870537602','-1.922295546179998','-1.922295546179998','2.5824856130712437','0.12238344189440876','0.12238344189440872','0.99627207622075','0.9962720762207501','1.022089333584519e+91','1.9275814160560206e-50','3.7200759760208555e-44','8269017203802394','6.003867926738829e-37','1.20933355845501e-16','1.6655929347585955e+36','1125899906842616.2','8.881784197001191e-16'

**Comment by Thorin-Oakenpants** [comment]
^^ done

**Comment by abrahamjuliot** [comment]
Here's the vm results:

macOS Catalina 64 bit vm w/FF control:

FF 80/TB 68
 hash: 84ad7bbb52342b6c224c0fe45977184bc943bb92 [NEW]
 func: f8d1be2d402ea061ef402d5dcb40dfacd39465ce
 poly: 0cde3749d8f342c858af1eef6b48f2e2be985440
  cos: 0, 1, 2, 3, 4, 5, 6, 7, 12, 13, 15, 16, 17, 18, 20
  sin: 0, 1, 10, 12, 13, 15
  tan: 0, 1, 2, 3, 4, 5, 6, 7, 8, 11, 12


Safari 13.0.5
 hash: 4423be6d9bec5550ad38ea9dde7ef2daf0609e0f [NEW]
 func: e3a6576f61c99a2fc903b3645c3fb5ceba71a953
 poly: ef29201529896b56fcde1885d4c1980c8ad5d195
 acos: 0
acosh: 2
 atan: 0
atanh: 0, 0p1
 cbrt: 1
  cos: 0, 1, 2, 3, 4, 5, 6, 7, 12, 13, 15, 16, 17, 18, 20
 cosh: 2, 3
expm1: 0
hypot: 1, 2, 3, 4, 5, 6, 7, 8
  sin: 0, 1, 10, 12, 13, 15
 sinh: 1, 5, 8, 9
  tan: 0, 1, 2, 3, 4, 5, 6, 7, 8, 11, 12
 tanh: 0
  pow: 0, 1, 2, 3, 4, 5, 6, 7, 8

Chrome 85 [C1]

**Comment by Thorin-Oakenpants** [comment]
thanks - all added to issue #80 .. and to the two new ones to the code base
