### ISSUE TITLE
building: canvas section

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/TorZillaPrint#8]
OK. Holy moly ... lets get the expert in here 

@kkapsner have a quick look [here](https://ghacksuserjs.github.io/TorZillaPrint/TorZillaPrint.html) in a new tab, and scroll down to the canvas section. It lists 10 methods

How hard (or easy) would it be for you to create a canvas.js to return the a value or "not supported" for all those. Each section has it's own js file in `/js/` and all you need to do is just edit the html file to add the script file and id the `<td>` elements (I assume that's how you'd do it)

I would of course invite you here and give you admin rights (I trust you man!)... or if you don't want that then by all means fork and do a PR.

:kiss: :suckup: :freebeer: 

PS: I would want the algorithm used to be the same as Panopticlick, so a 10x10 white returns a hash of `a273d6a847f0e2a57fa0161158f12fed`. Do you have that? Or would I need to go dig it out of panopticlick's code?

:extrasuckingup: :kiss:

**Comment by Thorin-Oakenpants** [comment]
PS: i haven't done the readme, but this is solely for Tor Browser and Firefox, ESR60+, stable. Don't care about other browsers/engines or old releases. If that helps simplify code.

**Comment by kkapsner** [comment]
Extracting the Panopticlick algorithm is quite simple. I will just copy it. But I think having a separate hash for every canvas function is not useful (Panopticlick also uses a mix of these).
Let's see what I can do there.

PS: I do not mind having write rights on this repo.

**Comment by Thorin-Oakenpants** [comment]
you have an invite: https://github.com/ghacksuserjs/TorZillaPrint/invitations - made you an admin

As for the has function used, it actually doesn't matter. At some stage we'll add in a json export so users can compare results - e/g tor users on different platforms. For some reason I thought the panopticlick one would be a good idea because I know it's the `a273d6a...` one ... but that's just silly now I think of it.

What I will do, is put in a spanned row with the 10x10 white canvas result (so people know that's the spoofed one by RFP), or you could code a prefixed `✓ ` in front of 10x10 whites.

Also a quick question - because iframes are so often overlooked (and I plan on build this feature in on a lot of things), you can add a third column (35%, 33, 32) and output iframe results in column 3. I will handle a second row with column headers if need be. I even have the background color picked out :)

**Comment by Thorin-Oakenpants** [comment]
PS: feel free to stick your own license in your canvas.js like I did here: https://github.com/ghacksuserjs/TorZillaPrint/blob/master/js/math.js

**Comment by Thorin-Oakenpants** [comment]
relevant [bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1422890)

I can't remember which API is controlled by `gfx.offscreencanvas.enabled`, the default in FF is false, but in my tests in a nilla profile I will enable that

If we need iframe tests, here's a mockup
![canavs-iframe](https://user-images.githubusercontent.com/16656956/50538390-1d24d180-0b67-11e9-97c7-e7e61c2ff36f.png)

here's an idea to put in a checkmark column for the 10x10 white protected values
![canavs-check](https://user-images.githubusercontent.com/16656956/50538481-6590bf00-0b68-11e9-9b34-bd466e14e49e.png)

or a combo of 5 columns

or no checkmark column but something like this
![canvas-subheader](https://user-images.githubusercontent.com/16656956/50538590-8d345700-0b69-11e9-97f6-5c97cb9b209a.png)

which I prefer. I need to add description lines under a couple of section headers anyway, so we can drop the checkmark business, and you can use any hash algorithm you like

**Comment by Thorin-Oakenpants** [comment]
just let me know what you want in terms of columns (2 or 3) and I'll get it sorted out

**Comment by kkapsner** [comment]
Actually I do not care about the gui/layout at the moment. I will first create an API that provides the hashes (iframes and other window objects will be supported). You can decide which layout you want - I will then adapt to it.

**Comment by kkapsner** [comment]
First draft:
![grafik](https://user-images.githubusercontent.com/1105157/50547858-018ef900-0c43-11e9-9ecc-2f0d5858de29.png)
(I actually don't mind sharing the hashes as they are random... CB in place).

**Comment by kkapsner** [comment]
Are you running the test with a local file? RFP does not work with the file:// protocol (i.e. local files). You need some sort of web server involved.

**Comment by kkapsner** [comment]
isPointInPath changes for me when enabling RFP.

**Comment by Thorin-Oakenpants** [comment]
I'm just doing some tests now I can use the live web results. So far with RFP on, CB (with fake) doesn't affect any values. BRB, need to test nilla FF

**Comment by Thorin-Oakenpants** [comment]
Test results:

nilla FF - all 6 leak like a sieve

nilla FF with RFP, nilla TB (which has RFP), my main FF with RFP (and no CB), and my main FF with RFP and CB set to fake (all methods): all these return the same

```
toDataURL, toBlob, mozGetAsFile
   d87b36e65e37d411ac204db663f0ec05fe94bf7b6df537bab3f11052d1621ecc
getImageData
   ae8d89f4cb47814af5d79e63a1a60b3f3f28d9309189b7518f1ecc23d8bda282
isPointInPath, isPointInStroke
   957c80fa4be3af7e53b40c852edf96a090f09958cc7f832aaf9a9fd544fb69a8
```

**Comment by Thorin-Oakenpants** [comment]
@tomrittervg 
is this normal? don't think I've ever seen it before: this is Tor Browser with RFP protecting canvas - I get two prompts but I ignore them. 1 thousand console logs?

![canvas1k](https://user-images.githubusercontent.com/16656956/50588812-aa279d80-0e7b-11e9-982d-4b4ea401f5bb.png)

**Comment by kkapsner** [comment]
1000 is a weird number - there should be 1805.

**Comment by Thorin-Oakenpants** [comment]
That was in Tor Browser - maybe they did something extra to the RFP code? PS: in TB, if I save the RFP prompt to "block" (i.e let RFP protect me), then subsequent loads do not output anything to the console

Here is nilla FF with RFP (I did not get any prompts?) which shows all 1805
![canvas2](https://user-images.githubusercontent.com/16656956/50592489-35109400-0e8c-11e9-890b-eef8d96af3fe.png)

**Comment by Thorin-Oakenpants** [comment]
ahhh ... privacy.resistFingerprinting.autoDeclineNoUserInputCanvasPrompts
- FF default is true
- TB default is false

If I set TB to true, then I get 1805

**Comment by Thorin-Oakenpants** [comment]
FYI: https://trac.torproject.org/projects/tor/ticket/29028 ... TB will flip it to default true in the next release

**Comment by kkapsner** [comment]
I think the canvas section is finished - close this issue and merge the canvas branch if you like.

**Comment by Thorin-Oakenpants** [comment]
Thanks :kiss:  .. just one nit

nilla FF64
getContext	2d: supported, **webgl: supported, webgl2: supported**
[webgl] readPixels	ac9ablahblahblah7f3

TB 8.0.4
getContext	2d: supported, **webgl: not supported, webgl2: not supported**
[webgl] readPixels	error while testing

when webGL is not supported (from line 1) would it be better to bypass the test and return "not supported", and/or catch the error (because webgl might be supported by webgl2 not?) and return "not supported"

It doesn't really matter since the result returned is consistent
